openrocket/openrocket

- core/resources/l10n/messages.properties
- core/src/net/sf/openrocket/file/openrocket/importt/DocumentConfig.java
- core/src/net/sf/openrocket/file/openrocket/savers/FinSetSaver.java
- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
- swing/src/net/sf/openrocket/gui/adaptors/MaterialModel.java
- swing/src/net/sf/openrocket/gui/configdialog/BodyTubeConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/EllipticalFinSetConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/FinSetConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/FreeformFinSetConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/InnerTubeConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/LaunchLugConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/NoseConeConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/RingComponentConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/RocketComponentConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/ShockCordConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/TransitionConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/TrapezoidFinSetConfig.java
Add second material to FinSet, made materialPanel functional (no side effects) so that it could be better controlled in the dialogs.  Added several adhesive material bulk properties and added mass properties calcs to the FinSet.
> Fin fillets

- core/src/net/sf/openrocket/simulation/extension/impl/JavaCode.java
Some debugging code was accidentally left over in my scripting branch.
> Remove accidental debugging code

- core/resources/l10n/messages_es.properties
> Adding missing Spanish translation

- core/resources/l10n/messages.properties
- core/src/net/sf/openrocket/file/openrocket/importt/OpenRocketLoader.java
- core/src/net/sf/openrocket/file/rocksim/importt/RocksimLoader.java
- core/src/net/sf/openrocket/startup/Preferences.java
- swing/src/net/sf/openrocket/gui/dialogs/preferences/GeneralPreferencesPanel.java
- swing/src/net/sf/openrocket/gui/main/BasicFrame.java
- swing/src/net/sf/openrocket/gui/main/ExportDecalDialog.java
- swing/src/net/sf/openrocket/gui/main/SaveAsFileChooser.java
- swing/src/net/sf/openrocket/gui/main/StorageOptionChooser.java
- swing/src/net/sf/openrocket/gui/util/FileHelper.java
Revise save mechanics to only allow saving in ORK format.  To save in Rkt format, one must use the "Export" menu item.
> Save dialogs

- core/src/net/sf/openrocket/file/openrocket/importt/IgnitionConfigurationHandler.java
- core/src/net/sf/openrocket/file/openrocket/importt/MotorMountHandler.java
- core/src/net/sf/openrocket/rocketcomponent/AxialStage.java
- core/src/net/sf/openrocket/rocketcomponent/FlightConfigurationID.java
- core/src/net/sf/openrocket/rocketcomponent/IgnitionEvent.java
- core/src/net/sf/openrocket/rocketcomponent/ParallelStage.java
- core/src/net/sf/openrocket/rocketcomponent/Rocket.java
- core/test/net/sf/openrocket/rocketcomponent/FinSetTest.java
Take a look, and let's triage again.
> Restored Automatic Ignition Event, plus a few other small fixes. 

- core/src/net/sf/openrocket/motor/MotorConfiguration.java
- core/test/net/sf/openrocket/aerodynamics/BarrowmanCalculatorTest.java
- swing/OpenRocket Swing.iml
- swing/test/net/sf/openrocket/IntegrationTest.java
1) Fixes BarrowmanCalculator Unit Test
2) Partial Fix for Swing Unit tests (this test now fails because the simulation produces a different answer.)
> 2 Small fixes to address test suite failures

- core/resources/l10n/messages.properties
- core/src/net/sf/openrocket/file/openrocket/savers/RocketSaver.java
- core/src/net/sf/openrocket/motor/MotorConfiguration.java
- core/src/net/sf/openrocket/rocketcomponent/FlightConfiguration.java
> Moved 'no motors' text to translation system.

- core/src/net/sf/openrocket/masscalc/MassCalculator.java
- core/src/net/sf/openrocket/motor/Motor.java
- core/src/net/sf/openrocket/motor/ThrustCurveMotor.java
- core/src/net/sf/openrocket/motor/ThrustCurveMotorPlaceholder.java
- core/src/net/sf/openrocket/simulation/AbstractSimulationStepper.java
- core/src/net/sf/openrocket/simulation/BasicEventSimulationEngine.java
- core/src/net/sf/openrocket/simulation/MotorClusterState.java
- core/src/net/sf/openrocket/utils/MotorCorrelation.java
- core/src/net/sf/openrocket/utils/MotorDigester.java
- core/test/net/sf/openrocket/file/motor/TestMotorLoader.java
average thrust while simulating.
> Use actual burn time for determination of burnout event.  Compute

- core/src/net/sf/openrocket/masscalc/MassCalculator.java
- core/src/net/sf/openrocket/masscalc/MassData.java
- core/test/net/sf/openrocket/masscalc/MassCalculatorTest.java
- core/test/net/sf/openrocket/masscalc/MassDataTest.java
These should be uncontroversial:
[Minor] added exception throws upon detected invalid inertia values during simulation
[Minor] Removed dead / debug code from mass calculation code
> Cleaning up the code from: PR #273

- core/src/net/sf/openrocket/motor/MotorConfiguration.java
- core/src/net/sf/openrocket/motor/MotorConfigurationSet.java
- core/src/net/sf/openrocket/rocketcomponent/FlightConfiguration.java
- core/src/net/sf/openrocket/rocketcomponent/Rocket.java
- core/test/net/sf/openrocket/rocketcomponent/RocketTest.java
This commit fixes the IntegrationTest failures (#294), as well as several other minor bugs
> Fix issue #294

- core/src/net/sf/openrocket/aerodynamics/AerodynamicForces.java
- core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java
- core/src/net/sf/openrocket/aerodynamics/FlightConditions.java
- core/src/net/sf/openrocket/aerodynamics/Warning.java
- core/src/net/sf/openrocket/aerodynamics/WarningSet.java
- core/src/net/sf/openrocket/aerodynamics/barrowman/FinSetCalc.java
- core/src/net/sf/openrocket/appearance/Appearance.java
- core/src/net/sf/openrocket/appearance/AppearanceBuilder.java
- core/src/net/sf/openrocket/util/AbstractChangeSource.java
and some refactoring of the files
> adds documentation to aerodynmics package 

- swing/src/net/sf/openrocket/gui/configdialog/AxialStageConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/MassComponentConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/NoseConeConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/RailButtonConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/RingComponentConfig.java
- swing/src/net/sf/openrocket/gui/dialogs/CustomMaterialDialog.java
- swing/src/net/sf/openrocket/gui/dialogs/PrintSettingsDialog.java
- swing/src/net/sf/openrocket/gui/dialogs/WarningDialog.java
- swing/src/net/sf/openrocket/gui/dialogs/flightconfiguration/DeploymentSelectionDialog.java
Fixes a small number of minor superficial warnings, several spots each. 
None of these change functionality. 
- some other minor changes.
> Warning cleanup ( reduced from 219 to 185 )

- swing/src/net/sf/openrocket/gui/main/SimulationPanel.java
Implement code to copy the simulation results to the system clipboard. Again this is a convienence function for the user who needs to copy results to a spreadsheet or document say for L3 projects.
> Copy Simulation Results to Clipboard

- core/src/net/sf/openrocket/rocketcomponent/AxialStage.java
- core/src/net/sf/openrocket/rocketcomponent/ComponentAssembly.java
- core/src/net/sf/openrocket/rocketcomponent/ParallelStage.java
- core/src/net/sf/openrocket/rocketcomponent/PodSet.java
- core/src/net/sf/openrocket/rocketcomponent/RocketComponent.java
- core/src/net/sf/openrocket/rocketcomponent/position/AngleMethod.java
- core/src/net/sf/openrocket/rocketcomponent/position/AxialMethod.java
- core/src/net/sf/openrocket/rocketcomponent/position/RadiusMethod.java
- core/test/net/sf/openrocket/rocketcomponent/ParallelStageTest.java
- swing/src/net/sf/openrocket/gui/configdialog/ComponentAssemblyConfig.java
- Removed unnecessary positioning methods from the UI
(but not from the underlying code)
- Fixed the Localized descriptions of these new positioning methods
> Alpha6 - Minor Fixes, as requested on the mailing lists.

- swing/src/net/sf/openrocket/gui/dialogs/ScaleDialog.java
- swing/src/net/sf/openrocket/gui/dialogs/preset/ComponentPresetChooserDialog.java
- swing/src/net/sf/openrocket/gui/main/ExampleDesignFile.java
- swing/test/net/sf/openrocket/IntegrationTest.java
pulled together a few more bug fixes.
> Alpha7 - Aggregate further bugfixes - #330, #378

- core/src/net/sf/openrocket/rocketcomponent/TubeFinSet.java
Adds a missing interface inheritance in TubeFinSet.
> [fixes #470] May load TubeFinSet components again.

- swing/src/net/sf/openrocket/gui/configdialog/FreeformFinSetConfig.java
(re)Enables drag-editing of the fin's first point.
> [fixes #454] Allows dragging of first point

- core/src/net/sf/openrocket/rocketcomponent/FreeformFinSet.java
- core/test/net/sf/openrocket/rocketcomponent/FreeformFinSetTest.java
- May now load fin point-sets which start or end outside of the underlying base.
- in these exceptional cases, these "outside" points are bridged by points limited to the underlying mount-component.
> [fixes #471] Refactoring FreeformFinSet

- swing/src/net/sf/openrocket/gui/configdialog/FreeformFinSetConfig.java
- swing/src/net/sf/openrocket/gui/scalefigure/FinPointFigure.java
> Fix 474, 488  (rendering and editing issues with free-form fins)

- swing/src/net/sf/openrocket/gui/adaptors/BooleanModel.java
- swing/src/net/sf/openrocket/gui/adaptors/DoubleModel.java
- swing/src/net/sf/openrocket/gui/configdialog/BodyTubeConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/NoseConeConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/TransitionConfig.java
Seems to fix all the issues I can reproduce from:
https://github.com/openrocket/openrocket/issues/329
Request further testing:
https://transfer.sh/AHq7S/OpenRocket.jar
> [fixes #329] refactors some event-handling in component config dialogs

- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
- core/test/net/sf/openrocket/rocketcomponent/FreeformFinSetTest.java
- core/test/net/sf/openrocket/rocketcomponent/TrapezoidFinSetTest.java
> [fixes #500] May Calculate CG for fins on zero-dimension mounts

- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
- core/src/net/sf/openrocket/rocketcomponent/FreeformFinSet.java
- core/src/net/sf/openrocket/rocketcomponent/Transition.java
- core/test/net/sf/openrocket/masscalc/MassCalculatorTest.java
- core/test/net/sf/openrocket/rocketcomponent/FreeformFinSetTest.java
- swing/src/net/sf/openrocket/gui/configdialog/FreeformFinSetConfig.java
allows moving the fins via offsets beyond the mount's front / tail
> Fixes #498 - Refactor of FreeformFinSet[Test]

- .travis.yml
…and didn't even work, besides.
> [rollback] disables upload.sh in .travis.yml, as it was hanging (for 20+m)

- .idea/artifacts/openrocket_jar.xml
- .idea/misc.xml
- .idea/runConfigurations/Openrocket_UI_Jar.xml
- core/OpenRocket Core.iml
- core/src/de/congrace/exp4j/Variable.java
- core/test/net/sf/openrocket/communication/UpdateInfoTest.java
- lib-test/OpenRocket Test Libraries.iml
- swing/OpenRocket Swing.iml
no source code changes, just adding the right libraries to the right Intellij *.iml, *.iml project files.
This also  allows intellij to generate a release jar.
> Fixes Intellij builds jars for java 9/11/13

- core/src/net/sf/openrocket/file/openrocket/importt/AnglePositionSetter.java
- core/src/net/sf/openrocket/file/openrocket/savers/FinSetSaver.java
- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
- core/src/net/sf/openrocket/rocketcomponent/position/AnglePositionable.java
- core/src/net/sf/openrocket/util/MathUtil.java
- core/test/net/sf/openrocket/rocketcomponent/FinSetTest.java
- swing/src/net/sf/openrocket/gui/configdialog/EllipticalFinSetConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/FreeformFinSetConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/TrapezoidFinSetConfig.java
- swing/src/net/sf/openrocket/gui/rocketfigure/FinSetShapes.java
- Discovered while debugging #538 
- Also addresses: #565
> [review-requested][fix] Adds explicit Angle Unit Conversion to/from FinSet cant and base angles.

- core/src/net/sf/openrocket/rocketcomponent/BodyTube.java
- core/src/net/sf/openrocket/rocketcomponent/FlightConfiguration.java
- core/src/net/sf/openrocket/rocketcomponent/InnerTube.java
- core/src/net/sf/openrocket/rocketcomponent/MotorMount.java
- core/test/net/sf/openrocket/rocketcomponent/FlightConfigurationTest.java
- swing/src/net/sf/openrocket/gui/print/DesignReport.java
- swing/src/net/sf/openrocket/gui/print/PrintFigure.java
- swing/src/net/sf/openrocket/gui/rocketfigure/SymmetricComponentShapes.java
- swing/src/net/sf/openrocket/gui/rocketfigure/TransitionShapes.java
- swing/src/net/sf/openrocket/gui/rocketfigure/TubeShapes.java
- swing/src/net/sf/openrocket/gui/scalefigure/RocketFigure.java
This pull requests addresses a few issues with the print/export as PDF function. As identified in #531, an attempt to print or export as pdf will result in an IlllegalStateException being raised.
1. Correct the logic for detecting if a motor has an invalid FlightConfigurationId and throw an IllegalStateException only in the case that it has an error.
2. Fix the lookup for the stageMass. The wrong value was passed to the MassCalculator.getCGAnalysis(..) which resulted in a NullPointerException.
3. Fix issues with drawing rocket diagram in print/pdf
4. Clean up some of the code in DesignReport, including some refactoring TODOs in the addMotorData method.
> [Fixes #531] Fix printing/export as pdf

- swing/src/net/sf/openrocket/gui/rocketfigure/RailButtonShapes.java
- Added code to handle view rotation from the left-hand slider
> [fixes #656] Rail Buttons now properly display in 2d side views

- swing/src/net/sf/openrocket/gui/dialogs/ScaleDialog.java
There's no picture to show, because the rocket looks the same as before (in fact I had to undo-redo to see the size change :)
> [fixes #638] Scale Rocket now scales the radial distance of pods & parallel stages

- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
- swing/src/net/sf/openrocket/gui/figure3d/RocketRenderer.java
- It looked like this was due to the buggy fin-tab (i.e. crosses the body boundary) 
- upon setting fin-tab to zero-size, the fin renders correctly
- Therefore, the fin tab is simply disabled here.
> [Fixes #618] "Transparent" Fin now renders correctly

- core/resources/l10n/messages.properties
- core/src/net/sf/openrocket/aerodynamics/Warning.java
- core/src/net/sf/openrocket/aerodynamics/barrowman/FinSetCalc.java
Adds a new error message to warn users about mounting fins on phantom bodies:
Runnable jar:
https://drive.google.com/open?id=1wY6ydj5zBnv4VT6QQlKepTxEuNWOLmQC
This is a purely cosmetic change; as such it's subjective.
> [Resolve #571] Add message fins-on-phantom-bodies

- core/src/net/sf/openrocket/util/StringUtil.java
- core/test/net/sf/openrocket/util/StringUtilTest.java
I added parameter and return value desriptions for the method `StringUtil.isEmpty(String s).`
Also, I added a test class `StringUtilTest` to test this method (this method didn't have a test before).
Test is successful.
The app overall seems to compile without problems.
> Enhanced the javadoc of StringUtil's method and added a test.

- swing/src/net/sf/openrocket/gui/dialogs/ComponentAnalysisDialog.java
oops.   Meant to include these in #676
> [fix] removes excess debugging lines from PR #676

- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
- core/test/net/sf/openrocket/masscalc/MassCalculatorTest.java
Fixes #679 by removing extra multiplication by number of fins, updates unit tests to match
> fixes Fin MOI calculations 

- swing/src/net/sf/openrocket/gui/scalefigure/AbstractScaleFigure.java
- swing/src/net/sf/openrocket/gui/scalefigure/ScaleScrollPane.java
Ultimate cause is some very odd behavior from JViewPort (Java 11 Standard Library)
This code is in effect, a workaround for that odd behavior.  It IS therefore 2/3 ugly hack :(
Also, refined some of the zoom calculations to be more exact.
https://drive.google.com/file/d/1bVQ1hOgXNf39FcTyJnzCHLj9XDL4Elgi/view?usp=sharing
> [fixes #696] Fixes occassional zitter when auto-zooming at some sizes

- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
- core/src/net/sf/openrocket/rocketcomponent/InnerTube.java
- core/src/net/sf/openrocket/rocketcomponent/MassObject.java
- core/src/net/sf/openrocket/rocketcomponent/ParallelStage.java
- core/src/net/sf/openrocket/rocketcomponent/RingComponent.java
- core/src/net/sf/openrocket/rocketcomponent/TubeFinSet.java
- core/src/net/sf/openrocket/rocketcomponent/position/AngleMethod.java
- core/src/net/sf/openrocket/simulation/SimulationOptions.java
- core/src/net/sf/openrocket/startup/Preferences.java
- core/src/net/sf/openrocket/util/MathUtil.java
- core/src/net/sf/openrocket/util/WorldCoordinate.java
- core/test/net/sf/openrocket/util/MathUtilTest.java
- swing/src/net/sf/openrocket/gui/components/compass/CompassSelectionButton.java
- swing/src/net/sf/openrocket/gui/components/compass/CompassSelector.java
- swing/src/net/sf/openrocket/gui/figure3d/RocketFigure3d.java
Should be a non-functional change.  All it changes are the function names.
> Refactor out deprecated functions.

- swing/src/net/sf/openrocket/gui/configdialog/ComponentConfigDialog.java
- swing/src/net/sf/openrocket/gui/dialogs/motor/thrustcurve/MotorFilterPanel.java
- swing/src/net/sf/openrocket/gui/main/RocketActions.java
1. fix -- rocket sometimes sends events to deleted ComponentConfigDialog
2. fix - rocket-motor-selection updates its units
> [fixes #733][fixes #724] Fix the motor-selection-dialog unit updating

- core/src/net/sf/openrocket/rocketcomponent/RocketComponent.java
- core/test/net/sf/openrocket/rocketcomponent/FreeformFinSetTest.java
- core/test/net/sf/openrocket/rocketcomponent/RocketTest.java
- swing/src/net/sf/openrocket/gui/configdialog/EllipticalFinSetConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/FreeformFinSetConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/TrapezoidFinSetConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/TubeFinSetConfig.java
> [Fixes #726] Fixes multiple issues when changing Fin-Offset-Methods

- core/resources/build.properties
- core/src/net/sf/openrocket/document/Simulation.java
- core/src/net/sf/openrocket/optimization/rocketoptimization/RocketOptimizationFunction.java
- core/src/net/sf/openrocket/optimization/rocketoptimization/domains/StabilityDomain.java
- core/src/net/sf/openrocket/optimization/rocketoptimization/modifiers/FlightConfigurationModifier.java
- core/src/net/sf/openrocket/optimization/rocketoptimization/modifiers/GenericComponentModifier.java
- core/src/net/sf/openrocket/optimization/rocketoptimization/parameters/StabilityParameter.java
- core/src/net/sf/openrocket/optimization/services/DefaultSimulationModifierService.java
- core/src/net/sf/openrocket/rocketcomponent/FlightConfiguration.java
- core/src/net/sf/openrocket/rocketcomponent/RecoveryDevice.java
- core/src/net/sf/openrocket/rocketcomponent/Rocket.java
- core/src/net/sf/openrocket/rocketcomponent/RocketComponent.java
- swing/src/net/sf/openrocket/gui/dialogs/optimization/GeneralOptimizationDialog.java
- swing/src/net/sf/openrocket/gui/dialogs/optimization/OptimizationWorker.java
- swing/src/net/sf/openrocket/gui/main/BasicFrame.java
- swing/src/net/sf/openrocket/gui/simulation/SimulationEditDialog.java
- swing/src/net/sf/openrocket/gui/simulation/SimulationRunDialog.java
https://drive.google.com/file/d/1SnGZY9PUC86x4rIgK-Vx4S7oS9WtD9dv/view?usp=sharing
> [fixes #701] Re-enables Rocket Optimizer

- core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java
- core/src/net/sf/openrocket/rocketcomponent/FlightConfiguration.java
On multistage rockets, there can be a next symmetric component that is not active.  Check for that.
I think this is the last fix required to close #768.
> Last fix on issue 768

- core/src/net/sf/openrocket/masscalc/MassCalculation.java
- core/test/net/sf/openrocket/masscalc/MassCalculatorTest.java
fixes more corner cases when performing mass calculations.
> Fixes #754 #755 -- Overriding Center-of-Mass x coordinate, mass works better

- swing/src/net/sf/openrocket/gui/figureelements/RocketInfo.java
- swing/src/net/sf/openrocket/gui/print/DesignReport.java
- swing/src/net/sf/openrocket/gui/scalefigure/RocketPanel.java
Fixes Issue #786 
Caused by the FlightConfiguration not updating figure display code.
> [fixes# 786] Updates config when drawing extras on 2D RocketFigure

- core/resources/l10n/messages.properties
- core/src/net/sf/openrocket/file/openrocket/savers/LaunchLugSaver.java
- core/src/net/sf/openrocket/file/openrocket/savers/RocketComponentSaver.java
- core/src/net/sf/openrocket/file/rocksim/export/LaunchLugDTO.java
- core/src/net/sf/openrocket/file/rocksim/importt/LaunchLugHandler.java
- core/src/net/sf/openrocket/rocketcomponent/LaunchLug.java
- core/test/net/sf/openrocket/file/rocksim/importt/RocksimLoaderTest.java
- core/test/net/sf/openrocket/rocketcomponent/LaunchLugTest.java
- swing/src/net/sf/openrocket/gui/configdialog/LaunchLugConfig.java
- swing/src/net/sf/openrocket/gui/print/FinMarkingGuide.java
- eliminated redundant angle-offset property in LaunchLug
- eliminated redundant accessors for same; and unified calling code to use the remaining accessors
> [fixes #801][fixes #751][fixes #752] Fixes multiple issues with LaunchLug component & ConfigDialog

- core/resources/build.properties
> [doc] Update version string to '20-11-alpha-16'

- core/src/net/sf/openrocket/motor/ThrustCurveMotor.java
> correct linear interpolation of motor CG

- swing/src/net/sf/openrocket/gui/figureelements/RocketInfo.java
The GlyphVector.getVisualBounds() does not include leading or trailing
spaces. Account for this when drawing stability information by
increasing the unitwidth by the length of one space.
Additionally, the code is inefficient in that it creates a new Font
object each and every time a new text string is created for graphical
display. This is unnecessary and adds overhead to the VM memory
requirements.
Fixes #880
> Add extra spacing for stability information text

- core/src/net/sf/openrocket/file/CSVExport.java
This fixes #912 by having `PrintWriter` follow the UTF-8 character set for CSV export.
I found this solution method on Stack Overflow: https://stackoverflow.com/questions/29556253/keep-unicode-characters-in-java-string
> Fix proper UTF-8 encoding for CSV export

- .github/workflows/build.yml
Make sure to do github action runs on pull requests
> Github actions on pull requests

- swing/src/net/sf/openrocket/gui/configdialog/AppearancePanel.java
Edited the ability for the 3D Finished preview to change its color in real-time when changing a component's appearance. When 'OK' is clicked in the appearance window, the color is applied, if cancel is clicked, the initial color will be reverted.
Fixes #879 
Here is the [jar](https://www.dropbox.com/s/c7i2nye5cheitin/OpenRocket_issue-879.jar?dl=0) for testing.
> [fixes #879] Added real-time color change appearance

- swing/src/net/sf/openrocket/gui/figure3d/photo/PhotoSettingsConfig.java
Added real-time color changing in Photo Studio. Same method as #944.
[Jar file](https://www.dropbox.com/s/dth2cx3hc1nze6l/OpenRocket-954.jar?dl=0) for testing.
> [fixes #954] Add real-time color change Photo Studio

- core/src/net/sf/openrocket/unit/PercentageOfLengthUnit.java
- core/src/net/sf/openrocket/unit/UnitGroup.java
* create a new class PercentageOfLengthUnit
* add new unit to stability units
> Allow rocket info to show stability margin as percentage of length

- swing/src/net/sf/openrocket/gui/plot/SimulationChart.java
- swing/src/net/sf/openrocket/gui/plot/SimulationPlot.java
In my opinion, the current plot appearance has a somewhat outdated look, not to mention that it is pretty hard to read the data. This PR updates the appearance to make it cleaner and more in sync with how e.g. MATLAB-plots look like. In addition, it also adds a tooltip for data points on the plot. Hovering on a line of the plot will give you a popup of the data value of that point.
Here is the old appearance:
Here is the new one:
Here is a [jar file](https://www.dropbox.com/s/qgbtvtsh757iyta/OpenRocket-better_plot.jar?dl=0) for testing.
> Improved plot appearance + tooltip

- core/src/net/sf/openrocket/util/Color.java
- swing/src/net/sf/openrocket/gui/rocketfigure/RailButtonShapes.java
- swing/src/net/sf/openrocket/gui/rocketfigure/RocketComponentShape.java
This PR fixes #816 where it was not possible to select the rail button from the side view.
The problem was the following:
How the RailButton figure is built up in the side view is as follows: the rail button shape itself is basically 3 cylinders stacked on top of each other. However, in the side view, this cylindrical 3D view is created by using ellipses and lines. This can be best seen if you rotate the view a bit. Each cylinder's top and bottom face is just an ellipse. These ellipses are then connected using straight lines (these are kind of the side faces of the 3D cylinder).
The problem why you can't select the rail button is because what you see is not one shape. By this I mean that if you are at 0° side view and try to select the middle part of the rail button, you aren't actually …
> [fixes #816] Fix select rail button side view

- swing/src/net/sf/openrocket/gui/rocketfigure/FinSetShapes.java
This PR fixes #1093 by adding back view support for fin tabs.
When testing, also be sure to play with the fin cant.
Here is a [jar file](https://drive.google.com/file/d/1UixwqI2Nk6YJvwlAzhyRk6YlMhKldkSG/view?usp=sharing) for testing.
> [fixes #1093] Add back view for fin tabs

- core/resources/build.properties
- swing/src/net/sf/openrocket/gui/dialogs/AboutDialog.java
Test jar at https://drive.google.com/file/d/1k5IGTelyPsUqeVsYCRTRWrrg1DRVQ8Y7/view?usp=sharing
> Update version string to 22.xx.BETA, add Justin Hanney to developers list in About dialog

- core/resources/build.properties
Updates the build version to 22.03.beta.01. I think it's fitting if we would do the release in March (considering OR 15.03).
> Update build version to March

- .idea/misc.xml
The misc.xml (used in IntelliJ to load the project settings like the Java version to be used) got lost from a PR I once made, so this PR just adds it back.
> Add misc.xml

- core/src/net/sf/openrocket/rocketcomponent/RocketComponent.java
- swing/src/net/sf/openrocket/gui/components/StageSelector.java
This PR fixes #1208 by adding a StageSelector button for parallel stages.
Here is a [jar file](https://github.com/openrocket/openrocket/suites/5512653750/artifacts/176654147) for testing.
> [fixes #1208] Add StageSelector button for ParallelStage

- core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java
> Create CalcMap based on all components, not just active ones

- swing/src/net/sf/openrocket/gui/dialogs/AboutDialog.java
Was using About Dialog to compare old version to new version and happen to look through the open source section.  Noticed a few missing dependencies that are being used and also some formatting issues.
> About Dialog Clean

- install4j/22.xx/openrocket-22.xx.install4j
The application name still needed to be edited to the new beta
> Update install4j application name

- install4j/22.xx/openrocket-22.xx.install4j
There was still one small name-change that needed to be done to the install4j config file
> Update install4j application name (once more)

- swing/src/net/sf/openrocket/gui/print/FinMarkingGuide.java
> Fin marking guide -- Fixes Issue #1259 No Rail Button location on Fin Marking Guide

- swing/src/net/sf/openrocket/gui/print/FinMarkingGuide.java
This PR simply removes the import comment from Craig's PR #1289. It would have just kept bothering me if I didn't fix this 🙃
> Remove import comment FinMarkingGuide

- swing/resources-src/datafiles/legacy_components/Front_Range_Rocket_Recovery.orc
- swing/resources-src/datafiles/legacy_components/Rocketman.orc
Addition of Front Range Recovery and The Rocketman parachutes.
> Additional parachute manufacturer's data

- swing/resources-src/datafiles/legacy_components/Spherachutes_Parachutes.orc
- swing/resources-src/datafiles/legacy_components/b2_Rocketry_Parachutes..orc
Adds b2Rocketry and Spherachutes product lines
> Additional parachute manufacturer products

- core/resources/l10n/messages.properties
- core/src/net/sf/openrocket/aerodynamics/Warning.java
- core/src/net/sf/openrocket/aerodynamics/barrowman/TubeCalc.java
> check for tubes with inner radius of 0; set pressure drag to 0 and set a warning

- core/src/net/sf/openrocket/aerodynamics/barrowman/TubeCalc.java
- core/src/net/sf/openrocket/aerodynamics/barrowman/TubeFinSetCalc.java
> Check for inner radius of tube == 0 to avoid NaN in pressure drop

- core/src/net/sf/openrocket/rocketcomponent/Transition.java
- install4j/22.xx/openrocket-22.xx.install4j
This PR fixes #1340 by clearing the transition preset on a shape or type change.
> [fixes #1340] Clear Transition preset on shape and type change

- core/src/net/sf/openrocket/rocketcomponent/Parachute.java
Simplified code by replace new if statements with else statements. No change in functionality.
> Minor change in parachute packed length and diameter code

- ReleaseNotes.md
Will keep updating until the last minute.
> Updated release notes for beta 3

- swing/src/net/sf/openrocket/gui/dialogs/preferences/SimulationPreferencesPanel.java
Small UI fix to update the ComboBox to display the selected item in: Preferences --> Simulation --> Simulation Options --> Geodetic Calculations
> Small UI Fix To Update ComboBox To Display Selection

- core/resources/l10n/messages.properties
- swing/src/net/sf/openrocket/gui/scalefigure/RocketPanel.java
> Include stability label in rocket view ribbon

- core/src/net/sf/openrocket/simulation/BasicTumbleStatus.java
Fixes #1356 
Previously, the tumble simulation aerodynamic code didn't account for either inactive components nor components with multiple instances.  The result was the every aerodynamic component in the rocket was counted exactly once, so the entire rocket was considered in looking at drag on a booster stage.  Also, if there were pods, each pod would only be counted once.
While this addresses this issue, tumble recovery still shows very high decelerations.  After comparing the code with Sampo's thesis it appears to be correct, and the final landing speeds are reasonable.  I'm guessing that the aerodynamic model being used for the tumbling stages is simply not accurate at high speeds, and those big decelerations will continue until we can get a model that's more appropriate when the …
> update iteration through rocket components to account for inactive components and instances

- core/resources/l10n/messages.properties
- swing/src/net/sf/openrocket/gui/configdialog/InnerTubeConfig.java
Uniform dialog for inner tube configuration pane, to match mass components.
> Uniform dialog for inner tube

- ReleaseNotes.md
Beta four release notes.  Good stuff.
> Release notes for beta 4, draft 1

- core/src/net/sf/openrocket/aerodynamics/AerodynamicCalculator.java
- core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java
- core/src/net/sf/openrocket/masscalc/MassCalculator.java
- core/src/net/sf/openrocket/motor/IgnitionEvent.java
- core/src/net/sf/openrocket/rocketcomponent/AxialStage.java
- core/src/net/sf/openrocket/rocketcomponent/FlightConfiguration.java
- core/src/net/sf/openrocket/rocketcomponent/ParallelStage.java
- core/src/net/sf/openrocket/rocketcomponent/Rocket.java
- core/src/net/sf/openrocket/rocketcomponent/RocketComponent.java
- core/src/net/sf/openrocket/simulation/BasicEventSimulationEngine.java
- core/src/net/sf/openrocket/simulation/FlightEvent.java
- core/src/net/sf/openrocket/simulation/MotorClusterState.java
- core/test/net/sf/openrocket/aerodynamics/BarrowmanCalculatorTest.java
- core/test/net/sf/openrocket/rocketcomponent/FlightConfigurationTest.java
- core/test/net/sf/openrocket/simulation/DisableStageTest.java
This PR fixes #1477 by not including inactive stages in calculateForceAnalysis.
Note: unintentionally this is already the start of fixing #1460, so I will leave this PR as a draft and add more commits as I go.
> [#1477 & #1460] Don't include inactive stages in calculations

- swing/src/net/sf/openrocket/gui/dialogs/ScaleDialog.java
> [#1520] Add check for selection options size

- core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java
This borders on embarrassing:  while working on #1171 today, it finally dawned on me that when we iterate through all the instances of a component when calculating drag we're wasting time: all we need to do is multiply the component's drag by the number of instances.
This is separate enough from the issue of getting drag coefficient overrides to work I wanted to make it its own PR.
> Multiply component drag by number of instances

- core/test/net/sf/openrocket/simulation/DisableStageTest.java
Still sometimes a failed test due to this
> Increase test error margin

- swing/src/net/sf/openrocket/gui/main/RocketActions.java
> [#1523] Fix copy order

- swing/src/net/sf/openrocket/gui/configdialog/FinSetConfig.java
> [#1600] Calculate auto tab for all inner tubes

- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
- swing/src/net/sf/openrocket/gui/figure3d/geometry/FinRenderer.java
- swing/src/net/sf/openrocket/gui/print/PrintableFinSet.java
This PR fixes #1618 and fixes #1597.
> [#1618 & #1597] Correct fin tab display on curved parent tube & fixes 3D issues for fin tabs

- swing/src/net/sf/openrocket/gui/figureelements/RocketInfo.java
This PR fixes #1638.
https://user-images.githubusercontent.com/11031519/188316614-52e00682-aece-4ee1-bf3a-81926f8cdf19.mov
> [#1638] Use RocketInfo mach for figure extra

- swing/src/net/sf/openrocket/gui/main/DesignPanel.java
> [#1648] Set component tree min width to 140px

- core/src/net/sf/openrocket/rocketcomponent/MassObject.java
- swing/src/net/sf/openrocket/gui/dialogs/ScaleDialog.java
> [#1649] Fix scaling of MassObject with autoRadius

- swing/src/net/sf/openrocket/gui/dialogs/ScaleDialog.java
This PR fixes #1651. The problem was the order in which scaling was done. For fin sets, first the fin points were scaled down, which would clip the tab length because the tab length before scaling down would now be larger than the fin length, and then the clipped tab length was further scaled down. So now, the scaling order is changed to first perform scaling according to the super class (for fins just FinSet), and afterwards the component-class (e.g. FreeFormFinSet).
> [#1651] Always do super component scales first

- swing/src/net/sf/openrocket/gui/dialogs/ScaleDialog.java
> [#1663] Fix duplicate scaling of multi-selection children

- core/src/net/sf/openrocket/rocketcomponent/RailButton.java
- swing/src/net/sf/openrocket/gui/dialogs/ScaleDialog.java
This PR fixes #1661 and adds scaling for rail buttons.
> [#1661] Add scaling for rail buttons

- swing/src/net/sf/openrocket/gui/configdialog/RocketComponentConfig.java
> permit negative drag coefficient overrides

- swing/src/net/sf/openrocket/gui/main/SimulationPanel.java
> [#1681] Fix sim table spotlight when no simulations

- swing/src/net/sf/openrocket/gui/dialogs/motor/thrustcurve/MotorFilterPanel.java
This PR fixes #1643 and unit rounds the diameter labels.
> [#1643] Round motor filter panel diameter labels

- ReleaseNotes.md
Here are the (lengthy) release notes for beta 5.
> Beta5 release notes

- swing/src/net/sf/openrocket/gui/main/ComponentAddButtons.java
This PR increases the font size of the component add button text, for better legibility.
> Increase component add button text size

- .gitignore
- swing/src/net/sf/openrocket/gui/dialogs/ComponentAnalysisDialog.java
> [#1704] Add change listener for stage selector in component analysis

- swing/src/net/sf/openrocket/gui/main/SimulationPanel.java
> [#1731] Catch out-of-range sim table click earlier on

- core/build.xml
- core/doc/techdoc/chapter-conclusion.tex
- core/resources/datafiles/tours/creating_design/creating_design.tour
- core/src/net/sf/openrocket/appearance/AppearanceBuilder.java
- core/src/net/sf/openrocket/database/Databases.java
- core/src/net/sf/openrocket/file/GeneralRocketLoader.java
- core/src/net/sf/openrocket/file/openrocket/savers/AxialStageSaver.java
- core/src/net/sf/openrocket/models/atmosphere/AtmosphericConditions.java
- core/src/net/sf/openrocket/preset/xml/BaseComponentDTO.java
- core/src/net/sf/openrocket/rocketcomponent/FlightConfigurationId.java
- core/src/net/sf/openrocket/rocketcomponent/FreeformFinSet.java
- core/src/net/sf/openrocket/simulation/BasicEventSimulationEngine.java
- core/src/net/sf/openrocket/simulation/FlightDataType.java
- core/src/net/sf/openrocket/util/TestRockets.java
- core/test/net/sf/openrocket/aerodynamics/BarrowmanCalculatorTest.java
- core/test/net/sf/openrocket/file/rocksim/importt/TubeFins1.rkt
- core/test/net/sf/openrocket/file/rocksim/importt/TubeFins2.rkt
- core/test/net/sf/openrocket/masscalc/MassCalculatorTest.java
- core/web/html/actions/updates.php
- core/web/htp/contact.htp
- core/web/htp/news.htp
Found via `codespell -q 3 -S ./swing,./**/l10n,*.eps -L bu,cant,cna,fo,gool,iif,reencode,wallthickness`
> Fix various typos 

- swing/src/net/sf/openrocket/gui/adaptors/DoubleModel.java
- swing/src/net/sf/openrocket/gui/dialogs/optimization/GeneralOptimizationDialog.java
- swing/src/net/sf/openrocket/gui/dialogs/optimization/OptimizationPlotDialog.java
> [#1746] Fix "Seek value of" unit selector in rocket optimizer

- core/src/net/sf/openrocket/rocketcomponent/Transition.java
- swing/src/net/sf/openrocket/gui/configdialog/TransitionConfig.java
This PR fixes #1761. The issue was caused by PR #1377, which fixed #1375, but caused issue #1761 🙃.
> [#1761] Fix Transition/Nose cone shape parameter resetting

- core/OpenRocket Core.iml
> Add opencsv lib reference in IntelliJ config

- core/src/net/sf/openrocket/communication/ReleaseInfo.java
- core/src/net/sf/openrocket/communication/UpdateInfoRetriever.java
- core/test/net/sf/openrocket/communication/UpdateInfoTest.java
- swing/src/net/sf/openrocket/gui/dialogs/UpdateInfoDialog.java
This PR adds unit tests for the software updater and fixes #1701.
> [#1701] Add unit tests for software updater

- swing/src/net/sf/openrocket/gui/main/RocketActions.java
This PR fixes #1722 (no functional changes).
> [#1722] Remove select component null checks

- core/src/net/sf/openrocket/file/rocksim/importt/FinSetHandler.java
- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
Fixes #1553, I had to remove the final keyword from the finset, I'm not sure it was explicitly needed, but if so, I can probably make it work.
> Fixed trapezoidal fins on transitions not being imported from Rocksim

- swing/src/net/sf/openrocket/gui/dialogs/optimization/GeneralOptimizationDialog.java
> [#1781] Multi-component parameter additions/deletions in rocket optimizer

- swing/src/net/sf/openrocket/gui/scalefigure/RocketPanel.java
> [#1787] Deselect components when no components clicked

- swing/src/net/sf/openrocket/gui/adaptors/IntegerModel.java
This PR fixes #1794 by clamping IntegerModel values to min and max, similar to what was done in PR #1615.
> [#1794] Clamp IntegerModel to min and max on set

- swing/src/net/sf/openrocket/gui/configdialog/FreeformFinSetConfig.java
This PR fixes #1841.
https://user-images.githubusercontent.com/11031519/202481742-506b0100-7970-476b-bd4c-4cadf1737fed.mov
> [#1841] Wrap fin shape editor table and figure in split pane

- core/resources/l10n/messages.properties
- swing/src/net/sf/openrocket/gui/configdialog/FreeformFinSetConfig.java
- swing/src/net/sf/openrocket/gui/main/SimulationPanel.java
This PR fixes #1840. Since you can't delete the first or last fin point, the delete action is disabled for those items.
https://user-images.githubusercontent.com/11031519/202504014-1ada50e6-ecdd-4acb-ada5-96c3c8ed02ae.mov
> [#1840] Add context menu for fin point deletion

- swing/src/net/sf/openrocket/gui/plot/SimulationPlot.java
- swing/src/net/sf/openrocket/gui/simulation/SimulationEditDialog.java
- swing/src/net/sf/openrocket/gui/simulation/SimulationRunDialog.java
- swing/src/net/sf/openrocket/gui/simulation/SimulationWorker.java
> [#1820] Don't switch to simulation plot if "Simulate & Plot" resulted in faulty simulation

- swing/src/net/sf/openrocket/gui/main/SimulationPanel.java
> [#1813] Update previous selection on sim addition/deletion

- core/resources/l10n/messages.properties
- core/src/net/sf/openrocket/file/openrocket/importt/DocumentConfig.java
- core/src/net/sf/openrocket/file/openrocket/savers/RailButtonSaver.java
- core/src/net/sf/openrocket/preset/ComponentPreset.java
- core/src/net/sf/openrocket/rocketcomponent/RailButton.java
- core/src/net/sf/openrocket/rocketcomponent/RocketComponent.java
- swing/src/net/sf/openrocket/gui/adaptors/DoubleModel.java
- swing/src/net/sf/openrocket/gui/configdialog/RailButtonConfig.java
- swing/src/net/sf/openrocket/gui/figure3d/geometry/ComponentRenderer.java
- swing/src/net/sf/openrocket/gui/rocketfigure/RailButtonShapes.java
This PR fixes #1567 and implements a rail button screw.
https://user-images.githubusercontent.com/11031519/206908350-c272c66b-a97c-4229-92e7-b0debfe0edf4.mp4
I also noticed that the height sliders in the rail button config panel were not scaled linearly and that the minimum and maximum value of the sliders did not adjust dynamically. This PR fixes that as well.
> [#1567] Implement rail button screw

- core/resources/l10n/messages.properties
- core/src/net/sf/openrocket/rocketcomponent/ExternalComponent.java
Corrects polished value and adds 4 additional surfaces.
> Corrects polished value and adds 4 additional surfaces

- core/src/net/sf/openrocket/rocketcomponent/ExternalComponent.java
Sorry @JoePfeiffer, I hadn't pushed the comments yet, I wanted to make sure that the comments were okay with you before doing so.
> Surface roughness comments

- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
- core/test/net/sf/openrocket/rocketcomponent/FreeformFinSetTest.java
- swing/src/net/sf/openrocket/gui/scalefigure/FinPointFigure.java
Reverts openrocket/openrocket#1883
Funny title :)
> Revert "Revert "[#1021] Add extra root point(s) if fin is outside parent's bounds""

- README.md
- core/resources/l10n/messages_ar.properties
- swing/src/net/sf/openrocket/gui/dialogs/AboutDialog.java
- swing/src/net/sf/openrocket/gui/util/SwingPreferences.java
this file is the translation in arabic for open rocket
> messages_ar.properties

- core/src/net/sf/openrocket/file/rocksim/export/FinSetDTO.java
- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
> [#1907] Fix RockSim fin tab offset

- swing/src/net/sf/openrocket/gui/configdialog/FreeformFinSetConfig.java
This PR fixes #1896 (I think -- I didn't encounter the issue on my machine).
> [#1896] Increase freeform fin set table width

- core/.classpath
- swing/.classpath
> [#1960] Fix wrong naming of library

- swing/test/net/sf/openrocket/IntegrationTest.java
I guess there was a sim change recently that caused the altitude to increase slightly. It's not the first time that the sim fails here.
I ran the tests 300 times without failures.
> Update unit tests slightly

- core/.classpath
**W**hen added those files - all errors has gone
> Add JAR files to proper work of project load

- core/src/net/sf/openrocket/document/OpenRocketDocument.java
- core/src/net/sf/openrocket/document/Simulation.java
- core/src/net/sf/openrocket/file/openrocket/importt/SingleSimulationHandler.java
- core/src/net/sf/openrocket/optimization/services/DefaultSimulationModifierService.java
- swing/src/net/sf/openrocket/gui/main/BasicFrame.java
- swing/src/net/sf/openrocket/gui/main/FlightConfigurationPanel.java
- swing/src/net/sf/openrocket/gui/main/SimulationPanel.java
This fixes #2001. Change to a simulation now mark the document as being in an unsaved state.
https://user-images.githubusercontent.com/11031519/216088208-dee6f34a-42a1-4275-b039-fbe4c0536b3a.mov
> [#2001] Add document save change on sim edit

- swing/src/net/sf/openrocket/gui/configdialog/RocketConfig.java
This PR updates the thrust curves and parts database (well that was already up-to-date) for the final 22.02 release.
> Update thrust curves & parts database

- swing/src/net/sf/openrocket/communication/AssetHandler.java
- swing/src/net/sf/openrocket/gui/configdialog/RocketConfig.java
- swing/src/net/sf/openrocket/gui/dialogs/UpdateInfoDialog.java
- swing/src/net/sf/openrocket/gui/dialogs/preferences/LaunchPreferencesPanel.java
This PR changes the install button from the software updater from downloading the release directly from the GitHub-page to redirecting to the openrocket.info website.
> Redirect software updater download button to website

- ReleaseNotes.md
Here are the final release notes for 22.02.  It was very hard to decide what makes the cut here; I'm happy to add or remove as requested by anyone.
> Final release notes

- swing/src/net/sf/openrocket/gui/configdialog/RailButtonConfig.java
> [#2033] Fix negative slider value in instance separation

- swing/src/net/sf/openrocket/gui/scalefigure/RocketFigure.java
- swing/src/net/sf/openrocket/gui/scalefigure/RocketPanel.java
This PR fixes #2050.
https://user-images.githubusercontent.com/11031519/218621687-b0ca95e0-684b-49cf-ac5f-b618a05e0952.mov
> [#2050] Fix carets rotation in top view

- core/src/net/sf/openrocket/rocketcomponent/ComponentAssembly.java
- swing/src/net/sf/openrocket/gui/rocketfigure/ComponentAssemblyShapes.java
- swing/src/net/sf/openrocket/gui/rocketfigure/ParallelStageShapes.java
- swing/src/net/sf/openrocket/gui/rocketfigure/PodSetShapes.java
This PR fixes #2047.
https://user-images.githubusercontent.com/11031519/218484112-b9a46dc2-5a6d-4325-99bc-bb64c63e80e8.mov
> [#2047] Fix pod set & booster markers

- core/resources/l10n/messages.properties
- core/resources/l10n/messages_nl.properties
- core/resources/l10n/messages_uk_UA.properties
> [#2062] Change axial method "Tip of the nose cone" to "Tip of the rocket"

- core/resources/l10n/messages.properties
- swing/src/net/sf/openrocket/gui/dialogs/motor/thrustcurve/MotorInformationPanel.java
This PR fixes #2069.
https://user-images.githubusercontent.com/11031519/221323250-b8536d60-a1b1-4fce-b3b9-0591dc5d5ddc.mov
> [#2069] Add motor type to motor details

- core/src/net/sf/openrocket/simulation/DefaultSimulationOptionFactory.java
- core/test/net/sf/openrocket/simulation/SimulationConditionsTest.java
- core/test/net/sf/openrocket/startup/MockPreferences.java
This PR fixes #2103, there was one stupid type when setting the default flight conditions (which existed there since 2014, whoops ._.).
> [#2103] Fix type in default pressure setter

- core/src/net/sf/openrocket/rocketcomponent/FlightConfiguration.java
- core/src/net/sf/openrocket/rocketcomponent/Rocket.java
- core/test/net/sf/openrocket/rocketcomponent/RocketTest.java
> [#2101] Copy config name when copy/load rocket

- core/src/net/sf/openrocket/unit/UnitGroup.java
- swing/src/net/sf/openrocket/gui/configdialog/RocketComponentConfig.java
> [#2094] Display CD override with 3 decimals

- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
- core/src/net/sf/openrocket/rocketcomponent/FreeformFinSet.java
- swing/src/net/sf/openrocket/gui/configdialog/FinSetConfig.java
This PR fixes #2126.
https://user-images.githubusercontent.com/11031519/226393635-c042f27a-6d01-44d7-8289-98ec496c1692.mov
> [#2126] Apply freeform conversion to config listeners

- core/src/net/sf/openrocket/simulation/SimulationOptions.java
- core/src/net/sf/openrocket/startup/Preferences.java
- swing/src/net/sf/openrocket/gui/adaptors/BooleanModel.java
- swing/src/net/sf/openrocket/gui/dialogs/preferences/LaunchPreferencesPanel.java
- swing/src/net/sf/openrocket/gui/simulation/SimulationConditionsPanel.java
This PR fixes #2104. 
https://user-images.githubusercontent.com/11031519/227043260-b00937c2-8abb-47ea-a215-8ce09f29f38e.mp4
> [#2104] Display ISA values in temp & pressure fields

- swing/src/net/sf/openrocket/gui/scalefigure/RocketPanel.java
> [#2108] Don't dispose config dialog when no components selected in 3D view

- swing/src/net/sf/openrocket/gui/configdialog/BulkheadConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/CenteringRingConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/InnerTubeConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/RingComponentConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/SleeveConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/ThicknessRingComponentConfig.java
> [#2142] Set length setting as first item

- swing/src/net/sf/openrocket/gui/dialogs/flightconfiguration/MotorMountConfigurationPanel.java
- swing/src/net/sf/openrocket/gui/dialogs/flightconfiguration/MotorMountTableModel.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/MotorConfigurationPanel.java
This PR fixes #2152.
https://user-images.githubusercontent.com/11031519/228614393-942ef287-94a0-4f1c-b9dd-2c635ead431a.mov
> [#2152] Fix table column width changing

- swing/src/net/sf/openrocket/gui/dialogs/preferences/PreferencesDialog.java
- swing/src/net/sf/openrocket/gui/scalefigure/RocketPanel.java
- swing/src/net/sf/openrocket/gui/scalefigure/ScaleScrollPane.java
This PR fixes #2151.
https://user-images.githubusercontent.com/11031519/228605547-36b0ba0b-f9ca-4352-9b16-05d03315fcfb.mov
> [#2151] Update the ruler unit upon a unit change in prefs

- core/src/net/sf/openrocket/models/atmosphere/InterpolatingAtmosphericModel.java
This PR is a quick & dirty fix for #2180 (see comments over there).
> [#2180] Recompute layers if null

- core/src/net/sf/openrocket/rocketcomponent/BodyTube.java
- core/src/net/sf/openrocket/rocketcomponent/TubeFinSet.java
> [#2218] Apply outer/inner diameter preset to tube fin

- core/src/net/sf/openrocket/rocketcomponent/StageSeparationConfiguration.java
Reverts openrocket/openrocket#1860. Fixes #2235.
> Revert "Disallow stage separation at launch"

- core/src/net/sf/openrocket/rocketcomponent/Parachute.java
> Use MassObject API to set parachute length, radius from preset

- swing/src/net/sf/openrocket/gui/figure3d/geometry/TransitionRenderer.java
This PR fixes #2279.
https://github.com/openrocket/openrocket/assets/11031519/a1ae8591-07b9-4edd-a60c-e8cda5b5b74f
> [#2279] Change transition 3D fine-rendering based on aft/fore

- swing/src/net/sf/openrocket/gui/figure3d/geometry/FinRenderer.java
> [#2286] Fix fin tab face culling

- core/src/net/sf/openrocket/rocketcomponent/Transition.java
- core/src/net/sf/openrocket/util/TestRockets.java
- core/test/net/sf/openrocket/masscalc/MassCalculatorTest.java
- core/test/net/sf/openrocket/simulation/FlightEventsTest.java
This PR fixes #2282.
https://github.com/openrocket/openrocket/assets/11031519/4e193086-e480-4ba9-8530-fb5eaa797368
> [#2282] Update shoulder diameter when transition diameter changes

- core/src/net/sf/openrocket/rocketcomponent/FlightConfiguration.java
- core/src/net/sf/openrocket/rocketcomponent/Rocket.java
> [#2303] Copy raw name from flight config

- swing/src/net/sf/openrocket/gui/main/ComponentAddButtons.java
> [#2311] Center text in component add button

- core/src/net/sf/openrocket/unit/UnitGroup.java
- swing/src/net/sf/openrocket/gui/configdialog/NoseConeConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/TransitionConfig.java
@neilweinstock found an issue with the interpreting of PR #2134. Instead of changing the increment of the length in inches, I should have changed the increment of the shape parameter. This is now fixed in this PR.
> Fix PR #2134

- ReleaseNotes.md
- core/resources/build.properties
For review.  I'm not sure if these are too long, or if they should be better categorized, or what.
> Release notes for 23.09 beta 1

- swing/src/net/sf/openrocket/gui/dialogs/preferences/PreferencesDialog.java
> Store updated units preferences if needed

- core/src/net/sf/openrocket/rocketcomponent/Transition.java
> Include radius clamping in clamping exclude

- swing/src/net/sf/openrocket/gui/configdialog/RocketComponentConfig.java
- swing/src/net/sf/openrocket/gui/dialogs/preferences/GeneralPreferencesPanel.java
- swing/src/net/sf/openrocket/gui/dialogs/preset/ComponentPresetTable.java
- swing/src/net/sf/openrocket/gui/util/GUIUtil.java
This PR fixes #2381. There was also a bug in the dark UI where the component config dialog did not properly close after using the "Cancel" button, which is now fixed.
> [#2381] Use proper view index in table selection

- swing/src/net/sf/openrocket/gui/main/RocketActions.java
This PR fixes a confusion from TRF [here](https://www.rocketryforum.com/threads/wanted-beta-testers-for-the-next-release-of-openrocket.181945/post-2496881) regarding the "Select all of same color" feature. Previously, when the currently selected component had its appearance set to default, using "Select all of same color" would only select other components **of the same type** that also had the default appearance checked. In the post on TRF, both the nose cone and transition used the default appearance and had the same white color, but the same-color selection did not work.
This PR now ensures that when the currently selected component has the default appearance, it will check for all other components that **also have the default appearance** and have the same default appearance, …
> Also check color when using default material

- core/src/main/java/info/openrocket/core/simulation/FlightDataType.java
Oops -- #2491 screwed up test for equality of FlightDataTypes
> Fix FlightDataType test for equality

- swing/src/main/java/info/openrocket/swing/gui/scalefigure/RocketPanel.java
> [#2500] Fix issues with double-clicking

- swing/src/main/java/info/openrocket/swing/gui/scalefigure/RocketPanel.java
This PR fixes #2093. You can now rotate the 2D views by clicking and dragging in the design view. The behavior is identical to using the rotation slider in the design view.
The sensitivity is set so that moving the mouse upwards the same distance as the height of the design view will result in a 180° rotation. E.g. if you start your drag in the middle of the design view and drag up to the top of the design view, you will rotate 90°.
https://github.com/user-attachments/assets/e857c21f-e0be-43de-98c5-ee5eefcef051
> [#2093] Allow 2D views to be rotated by click-dragging

- swing/src/main/java/info/openrocket/swing/gui/simulation/FlightDataComboBox.java
- swing/src/main/java/info/openrocket/swing/gui/simulation/SimulationPlotPanel.java
- swing/src/main/java/info/openrocket/swing/gui/widgets/GroupableAndSearchableComboBox.java
This PR fixes the issue mentioned by @JoePfeiffer here: https://github.com/openrocket/openrocket/pull/2527#issuecomment-2283889341.
> Fix simplot vars

- install4j/23.09/openrocket-23.09.install4j
- swing/src/main/java/info/openrocket/swing/gui/theme/UITheme.java
- swing/src/main/java/info/openrocket/swing/startup/OSXSetup.java
- swing/src/main/java/info/openrocket/swing/startup/OpenRocket.java
- swing/src/main/resources/themes/FlatDarculaLaf.properties
- swing/src/main/resources/themes/FlatLaf.properties
- swing/src/main/resources/themes/IntelliJTheme$ThemeLaf.properties
This PR adds some very minor UI improvements, mainly in improving border colors.
> Small UI improvements

- core/src/main/resources/l10n/messages.properties
- swing/src/main/java/info/openrocket/swing/gui/configdialog/AppearancePanel.java
- swing/src/main/java/info/openrocket/swing/gui/util/ColorConversion.java
This PR fixes part of #2224, namely adding a hex color selection input in the appearance panel next to the color button.
https://github.com/user-attachments/assets/d152a3e2-f8e6-4052-a396-c40c70b8bb67
> [#2224] Add hex color input field in appearance panel

- swing/src/main/java/info/openrocket/swing/gui/figure3d/geometry/MassObjectRenderer.java
> [#2550] Fix mass object radial rotation in 3D view

- core/src/main/java/info/openrocket/core/rocketcomponent/RocketComponent.java
> [#2532] Fire outdated sim on stage rename

- core/src/main/java/info/openrocket/core/rocketcomponent/FinSet.java
- core/src/main/java/info/openrocket/core/rocketcomponent/FreeformFinSet.java
- core/src/main/java/info/openrocket/core/rocketcomponent/NoseCone.java
- swing/src/main/java/info/openrocket/swing/gui/dialogs/ScaleDialog.java
- swing/src/main/java/module-info.java
This PR fixes #2463. Additionally, it also fixes fin tab length/offset scaling.
>  [#2463] Fix shoulder radius scaling issue when smaller than 1 + fin tab length/offset scaling

- swing/src/main/java/info/openrocket/swing/gui/util/Icons.java
> [#2565] Check if icon is imageicon for icon disabling

- ReleaseNotes.md
This was supposed to be a draft PR but I fumbled.  Don't merge yet until there's been time for review.
> Release notes for 24.12b1

- docs/source/dev_guide/architecture.rst
- docs/source/dev_guide/contributing_to_the_docs.rst
- docs/source/dev_guide/development_overview.rst
- docs/source/dev_guide/file_specification.rst
- docs/source/index.rst
This PR improves our documentation on the .ork and .orc file specification. It's not complete, but it's a start.
> Improve docs of file specification

- swing/src/main/java/info/openrocket/swing/gui/adaptors/DoubleModel.java
- swing/src/main/java/info/openrocket/swing/gui/configdialog/AppearancePanel.java
> [#2644] Properly handle null events + supply source

- swing/src/main/java/info/openrocket/swing/gui/util/GUIUtil.java
> [#2652] Don't let the OS decide where to locate the windows

- core/src/main/java/info/openrocket/core/models/wind/PinkNoiseWindModel.java
> [#2678] Remove double-call to set standardDeviation

- core/src/main/java/info/openrocket/core/file/GeneralRocketSaver.java
As requested on [TRF](https://www.rocketryforum.com/threads/announcement-openrocket-24-12-beta-1-is-now-available-for-download.190125/post-2696250), this PR updates the date modified metadata on a .ork when you save it.
> Update last modified date on file when saving

- swing/src/main/java/info/openrocket/swing/gui/configdialog/AppearancePanel.java
> [#2671] Don't make color chooser modal

- core/src/main/java/info/openrocket/core/file/openrocket/importt/DocumentConfig.java
- core/src/main/java/info/openrocket/core/file/openrocket/savers/RocketSaver.java
- core/src/main/java/info/openrocket/core/rocketcomponent/DesignType.java
- core/src/main/java/info/openrocket/core/rocketcomponent/Rocket.java
- core/src/main/resources/l10n/messages.properties
- fileformat.txt
- swing/src/main/java/info/openrocket/swing/gui/configdialog/RocketConfig.java
Added additional properties such as "Design Type", as well as optimizations (Flight, Appearance, Construction). Functionality that saves these properties is also added. Fixes #2664
> [#2664] Additional rocket properties

- ReleaseNotes.md
- build.gradle
- core/src/main/resources/build.properties
- install4j/24.12/openrocket-24.12.install4j
- swing/src/main/java/info/openrocket/swing/gui/dialogs/BugReportDialog.java
- swing/src/main/java/module-info.java
This PR fixes #1667, the infamous window ghosting bug for Windows users. The fix involves adding these JVM arguments when running the JAR, as taken from [here](https://github.com/skylot/jadx/issues/2225):
```
"-Dsun.java2d.noddraw=true"
"-Dsun.java2d.d3d=false"
"-Dsun.java2d.ddforcevram=true"
"-Dsun.java2d.ddblit=false"
"-Dswing.useflipBufferStrategy=True" 
```
The fix has been confirmed by users CoreCount and Catalyst on the r/rocketry server, thanks for the help!
Today is a good day :)
> [#1667] Eliminate window ghosting on Windows!!

- core/src/main/java/info/openrocket/core/simulation/extension/example/CSVSave.java
We've had a user who didn't notice the CSV export feature try to use the CSV export extension to do it. This will hopefully point people in the right place.
Fixes #2696
> Cleanup of CSVSave listener example

- ReleaseNotes.md
Here is the first draft of release notes for 24.12 RC.
> Release notes for 24.12 RC

- swing/src/main/java/info/openrocket/swing/gui/scalefigure/ViewRotationControl.java
> [#2779] Disable view rotation widgets when going 3D

- core/src/main/java/info/openrocket/core/simulation/BasicEventSimulationEngine.java
> Hook up SimulationStatus WarningSet to FlightData before performing sanity check on configuration.

- swing/src/main/java/info/openrocket/swing/gui/dialogs/preferences/MaterialEditPanel.java
> [#2859] Fire rocket mass change when material settings have changed
