- core/src/net/sf/openrocket/gui/util/SimpleFileFilter.java
- swing/src/net/sf/openrocket/gui/main/BasicFrame.java
When using the "File > Save As..." dialog,  this patch will update the filename extension directly upon changing the FileFilter type. (Behavior that changes the extension after clicking "Accept" is preserved.)
Due to JFileChooser API limitations, I had to pull the filename-to-correct from the Rocket's document.
> When using 'File > Save As..' dialog, update filename directly. (Minor patch)

- swing/src/net/sf/openrocket/gui/adaptors/EnumModel.java
- swing/src/net/sf/openrocket/gui/configdialog/ParachuteConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/RecoveryDeviceConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/StreamerConfig.java
- swing/src/net/sf/openrocket/gui/dialogs/flightconfiguration/DeploymentSelectionDialog.java
… deploy. This patch prevents the UI from showing those options.
====
Problem:
A RecoveryDevice sometimes fails to deploy if set to “Lower Stage Separation”.  (see attached file:  simply run the simulation, plot results, and note that the booster stage craters because the parachute did not deploy.)  Shout out to joe.b.bowen@gmail.com for reporting the bug.
Cause: 
The "Lower Stage Separation" is interpreted in code as time after the previous stage separates.  Obviously, this doesn't make much sense for the lowermost stage, but OR allows the user to select this-- making it seem like a bug.
Solution A: 
Prevent user selection of error states. These UI modications are in this pull request.
> Bugfix:  If configured wrong, booster stage recovery device would not deploy.

- swing/src/net/sf/openrocket/gui/figure3d/RealisticRenderer.java
Current limitations; depends on color chooser with alpha capability, alpha value does not get saved to .ork file, does not show up as transparent in "3D Unfinished" mode.
> Add transparent render capability to RealisticRenderer.java

- core/test/net/sf/openrocket/unit/FractionalUnitTest.java
- core/test/net/sf/openrocket/unit/UnitToStringTest.java
Changes tests for comma decimal separator locale so they won't give false negative
I'll then change this tests and ignore the rounding conflicts locally
> fixes tests giving false negative for comma decimal locale

- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/FlightConfigurablePanel.java
This fixes a (minor) display bug where a user could add and remove motors without said changes showing up in the main rocket display. 
The redraw could be forced, of course, but a non-technical user would likely to interpret this cosmetic behavior as a bug.  Hence this fix PR.  --DMW
> [fix] Redraw Rocket Figure when motors are added & removed

- core/src/net/sf/openrocket/unit/Unit.java
reformatted comments in Unit.java to be javadoc-parsable
removed dead code ( already commented out, and duplicate of existing function)
> Unit comment fix [single-file][non-functional][mini]

- core/src/net/sf/openrocket/rocketcomponent/ComponentAssembly.java
- core/src/net/sf/openrocket/rocketcomponent/Rocket.java
. . . instead of RocketComponent
Discussion:
Arguably this is a non-trivial change, but this simplifies overrides, specifically when debugging mass-calculation code, and locating components.  My case is:
1. conceptually, a rocket _IS A_ ComponentAssembly
2. rocket still inherits all the RocketComponent methods.
3. This change reduces code duplication:  
\* 7 redundant functions
\* lines: +8 / -47
4. Also:  changed Coordinate.NUL -> Coordinate.ZERO to better reflect our intent.
[edited for format.]
> [Refactor] Rocket now subclasses ComponentAssembly 

- core/test/net/sf/openrocket/masscalc/MassCalculatorTest.java
- swing/src/net/sf/openrocket/gui/components/StageSelector.java
This is an update to the previous fix attempt for Issue #295.
The changes to Test classes has not changed. (commit 3e869e015b36eaef32f4c6186179ebd349c18933)
While the call to voidMassCache()  has been replaced by fixed the event type sent by the stage toggle button. (commit cb6c525d92accb9cfa111705315b71b876f35797)
> [Fix][Issue #295] CG now correctly updates when Stages are toggled

- swing/src/net/sf/openrocket/gui/configdialog/FreeformFinSetConfig.java
This pull request adds a button to the Free-Form Fin Configuration panel to export the fin profile as a CSV file. This is a convenience so one does not have to open the ork file in a text editor and copy the numbers to a spreadsheet.
> Export Free Form Fin Profile to CSV File

- core/src/net/sf/openrocket/file/openrocket/importt/AppearanceHandler.java
- core/src/net/sf/openrocket/file/openrocket/savers/RocketComponentSaver.java
- swing/src/net/sf/openrocket/gui/figure3d/RealisticRenderer.java
Clear payload bays and clear fins(scale models) need alpha values saved to the file. The following allows any changes to a components transparency level to be saved/loaded from .ork files while maintaining backwards compatibility. Older versions will ignore alpha information from the newer file.
Also a small bug fix where the 3D Unfinished renderer wasn't showing internal parts, now body tubes are back to half-cutaway like before.
> Alpha value for semi-transparent components saved/loaded and small bug fix

- swing/src/net/sf/openrocket/gui/main/BasicFrame.java
Both the 'Component Analysis' and 'Optimization' Dialogs threw exceptions when started.
This PR hides them for the next release.
> Hide Buggy UI Dialogs

- core/src/net/sf/openrocket/rocketcomponent/SymmetricComponent.java
Remedies a negative inertia calculation for very flat NoseCones. 
Reported (in passing) on the mailing list.  Filed as issue #406.
@JoePfeiffer, @neilweinstock
> [fixes #406] SymmetricComponent no longer generates negative inertias

- core/src/net/sf/openrocket/motor/MotorConfiguration.java
- core/src/net/sf/openrocket/motor/MotorConfigurationSet.java
- core/src/net/sf/openrocket/rocketcomponent/FlightConfiguration.java
Formerly just used delay value directly, resulting in huge delay for
plugged motors; now uses motor.getDesignation so it translates to "P" as
expected.
Changed name of toMotorDescription method to toMotorDesignation to match
usage of getDesignation() in ThrustCurveMotor.java
Changed toMotorDesignation() to use motor.getDesignation()
> Fix Configuration name in motor configuration panel.

- core/resources/l10n/messages.properties
Non-functional change.  
Just cleaning up the internationalization file.
> [fix] removed duplicate property keys in 'resources/l10n'

- core/resources/l10n/messages.properties
- swing/src/net/sf/openrocket/gui/main/RocketActions.java
- reads the value of `Stage.Stage` from 'core/resources/l10n/messages.properties'
- currently "Stage"
Addresses inconsistent naming issue present on openrocket-dev mailing list.
> [fix][oneline] both Create Stage buttons now create stages with the same name

- core/src/net/sf/openrocket/rocketcomponent/FlightConfiguration.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/FlightConfigurationPanel.java
createSimulationForConfiguration() assumed addConfiguration() and
copyConfiguration() would set the new configuration as selected, but
they didn't resulting in simulation based on old configuration, not new
one.  Fixed.
addConfiguration() and copyConfiguration() had enough common code that
consolidating them and createSimulationForConfiguration() into a new method addOrCopyConfiguration() seemed like a good idea.
Let FlightConfiguration.copy() create new ID for consistency with
constructor.
> Set current configuration before creating simulation

- core/src/net/sf/openrocket/simulation/BasicEventSimulationEngine.java
Changed order of stage simulations to work from top down, resulting in the drop-down menus for plots and data exports to be in stage order.
Closes #459
> Stack stage simulations

- core/resources/build.properties
- last release candidate was alpha-9
- next round of bug fixes will be alpha-10
> [version] bump version string to '19-xx-alpha10'

- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
If a freeform fin was positioned near or past the end (due to rounding errors) of its mounting / parent component, then the parent would return 0 for the radius at that location, which would in turn glitch the display code in the main view.
A special case correction has been inserted into FinSet, to address this corner case.
> Fixes #468: Freeform fins display correctly again.

- swing/src/net/sf/openrocket/gui/scalefigure/FinPointFigure.java
Makes the underlying reference grid visible once again.
(This was purely a graphical issue)
> [fixes #482] Restores grid lines

- core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java
- core/test/net/sf/openrocket/aerodynamics/BarrowmanCalculatorTest.java
Adds a patch to clamp off-axis CP errors.
Manually sets y-coordinate to zero, when multiple instances are present.
Further discussion available on mailing list.
> [fixes #387] Fixes one source of off-axis CP error

- core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java
Closes issue #478 
Clarifies variable names
Removes previous attempt to limit damping moments by using minimum
velocity of 1.0
Clamps damping moments so they cannot exceed actual moments, avoiding
numerical instability
> Clamp pitch and yaw damping moments to avoid numerical instability

- .travis.yml
Details - https://github.com/probonopd/uploadtool
This script is designed to be called from Travis CI after a successful build. By default, this script will _delete_ any pre-existing release tagged with `continuous`, tag the current state with the name `continuous`, create a new release with that name, and upload the specified binaries there. For pull requests, it will upload the binaries to transfer.sh instead and post the resulting download URL to the pull request page on GitHub.
Before merging this pull request you should do next:
- On https://github.com/settings/tokens, click on "Generate new token" and generate a token with at least the `public_repo`, `repo:status`, and `repo_deployment` scopes
- On Travis CI, go to the settings of your project at …
> Deploy continuous builds to GitHub

- swing/src/net/sf/openrocket/gui/configdialog/FreeformFinSetConfig.java
Addresses corner case, where control would (incorrectly) advance to the first point, if the first point was still within the mount's x-bounds.
edit: refines #488
> [fix][minor] May correctly adjust first fin point

- core/src/net/sf/openrocket/rocketcomponent/FreeformFinSet.java
- swing/src/net/sf/openrocket/gui/configdialog/FreeformFinSetConfig.java
- swing/src/net/sf/openrocket/gui/util/CustomFinImporter.java
fix: enforce an implicit type dependency as an explicit type dependency.  Closes a mismatch in expected types that caused an exception after converting a fin from Trapezoidal to freeform, and then adding a point.
> [fixes #499] prevents an exception after converting-to-freeform

- swing/src/net/sf/openrocket/gui/scalefigure/FinPointFigure.java
- swing/src/net/sf/openrocket/gui/scalefigure/RocketFigure.java
Accommodates negative-coordinate components (like fins ;)
note: the changes in FinPointFigure are not functional, merely cleanup.
> [fixes #502] Adjust RocketFigure Bounds

- core/src/net/sf/openrocket/file/openrocket/savers/FinSetSaver.java
oneliner.  Just correcting the expected function call name.
> [fixes #510] Fin tab now saves the correct offset

- core/src/net/sf/openrocket/rocketcomponent/FlightConfiguration.java
- core/src/net/sf/openrocket/rocketcomponent/InstanceContext.java
- core/src/net/sf/openrocket/rocketcomponent/InstanceMap.java
- core/src/net/sf/openrocket/util/TestRockets.java
- core/test/net/sf/openrocket/rocketcomponent/FlightConfigurationTest.java
- core/test/net/sf/openrocket/rocketcomponent/RocketTest.java
- swing/src/net/sf/openrocket/gui/figure3d/RocketRenderer.java
- swing/src/net/sf/openrocket/gui/print/PrintableNoseCone.java
- swing/src/net/sf/openrocket/gui/rocketfigure/BodyTubeShapes.java
- swing/src/net/sf/openrocket/gui/rocketfigure/FinSetShapes.java
- swing/src/net/sf/openrocket/gui/rocketfigure/LaunchLugShapes.java
- swing/src/net/sf/openrocket/gui/rocketfigure/MassComponentShapes.java
- swing/src/net/sf/openrocket/gui/rocketfigure/MassObjectShapes.java
- swing/src/net/sf/openrocket/gui/rocketfigure/ParachuteShapes.java
- swing/src/net/sf/openrocket/gui/rocketfigure/RailButtonShapes.java
- swing/src/net/sf/openrocket/gui/rocketfigure/RingComponentShapes.java
- swing/src/net/sf/openrocket/gui/rocketfigure/RocketComponentShape.java
- swing/src/net/sf/openrocket/gui/rocketfigure/ShockCordShapes.java
- swing/src/net/sf/openrocket/gui/rocketfigure/StreamerShapes.java
- swing/src/net/sf/openrocket/gui/rocketfigure/SymmetricComponentShapes.java
- swing/src/net/sf/openrocket/gui/rocketfigure/TransitionShapes.java
- swing/src/net/sf/openrocket/gui/rocketfigure/TubeFinSetShapes.java
- swing/src/net/sf/openrocket/gui/rocketfigure/TubeShapes.java
- swing/src/net/sf/openrocket/gui/scalefigure/RocketFigure.java
- swing/src/net/sf/openrocket/gui/scalefigure/RocketPanel.java
Adds support for a new rocket iterator: 
InstanceMap getActiveInstances()
This returns a Map <RocketComponent => Instance info>.  This is intended to eventually supplant (or perhaps just augment) the 'getActiveInstances()' use cases, in situations where information about each component's individual instances is needed.
> Refactor instance map

- swing/src/net/sf/openrocket/gui/scalefigure/FinPointFigure.java
See:
https://github.com/openrocket/openrocket/issues/482
Improved contrast between the fin, fin-body, and the background grid.
Cosmetic only.
> [Fixes #482][graphics] adjusts line color and width in FinPointFigure

- core/src/net/sf/openrocket/rocketcomponent/FlightConfiguration.java
- core/src/net/sf/openrocket/util/TestRockets.java
- core/test/net/sf/openrocket/rocketcomponent/FlightConfigurationTest.java
- swing/src/net/sf/openrocket/gui/scalefigure/RocketPanel.java
The displayed diameter is also restricted to centerline components, now.
Also: corrects rocket length to be the overall max x span of the rocket.
> Fixes #525; Main Figure display rocket diameter again.

- core/src/net/sf/openrocket/aerodynamics/barrowman/FinSetCalc.java
- core/src/net/sf/openrocket/aerodynamics/barrowman/TubeFinSetCalc.java
Original issue arises from fins attached to "phantom" body tubes.
The warning is generated if the fin is thicker than half of it's parents radius; and phantom tubes (often) have a zero radius. (and/or zero length, but the zero radius is what causes the issue) 
Users who implement phantom tubes are expected to be expert / power users -- i.e. they're already assumed to have sufficient experience to know better than the program what they're doing. 
Therefore this PR simply disables warnings for fins on phantom tubes.
> [fix #497] Disables Fin-Thickness-Warnings on Phantom Fins

- core/src/net/sf/openrocket/rocketcomponent/InnerTube.java
Adds offset values to the coordinates returned by InnerTube.getInstanceOffsets() for a single inner tube.
> [Fix #544] InnerTube.getInstanceOffsets() returning Coordinate.ZERO for single inner tube

- core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java
- core/src/net/sf/openrocket/rocketcomponent/AxialStage.java
- core/src/net/sf/openrocket/rocketcomponent/BodyTube.java
- core/src/net/sf/openrocket/rocketcomponent/ComponentAssembly.java
- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
- core/src/net/sf/openrocket/rocketcomponent/FlightConfiguration.java
- core/src/net/sf/openrocket/rocketcomponent/InstanceMap.java
- core/src/net/sf/openrocket/rocketcomponent/InternalComponent.java
- core/src/net/sf/openrocket/rocketcomponent/LaunchLug.java
- core/src/net/sf/openrocket/rocketcomponent/MassObject.java
- core/src/net/sf/openrocket/rocketcomponent/ParallelStage.java
- core/src/net/sf/openrocket/rocketcomponent/PodSet.java
- core/src/net/sf/openrocket/rocketcomponent/RailButton.java
- core/src/net/sf/openrocket/rocketcomponent/RingComponent.java
- core/src/net/sf/openrocket/rocketcomponent/RocketComponent.java
- core/src/net/sf/openrocket/rocketcomponent/RocketUtils.java
- core/src/net/sf/openrocket/rocketcomponent/Sleeve.java
- core/src/net/sf/openrocket/rocketcomponent/SymmetricComponent.java
- core/src/net/sf/openrocket/rocketcomponent/Transition.java
- core/src/net/sf/openrocket/rocketcomponent/TubeFinSet.java
- core/src/net/sf/openrocket/simulation/SimulationStatus.java
- core/src/net/sf/openrocket/util/BoundingBox.java
- openrocket.log
- swing/src/net/sf/openrocket/gui/figure3d/RocketFigure3d.java
- swing/src/net/sf/openrocket/gui/figure3d/RocketRenderer.java
- swing/src/net/sf/openrocket/gui/figure3d/geometry/ComponentRenderer.java
- swing/src/net/sf/openrocket/gui/figure3d/photo/PhotoPanel.java
- swing/src/net/sf/openrocket/gui/figureelements/RocketInfo.java
- swing/src/net/sf/openrocket/gui/scalefigure/RocketFigure.java
- swing/src/net/sf/openrocket/gui/scalefigure/RocketPanel.java
@JoePfeiffer 
Hey, I was taking a look at another bug, and discovered openrocket was exhausting the stack, merely on opening a rocket :/  (Probably due to the auto-simulation done in the background.)
It's pretty much a breaking change, so If we can't find a solution, we'll have to revert the whole thing.  Do you have time to take a look at your PR #543 with the .ork below, and see what happened? 
[Inducing .ork file]( https://github.com/openrocket/openrocket/files/3095876/alcubierre_cranberry.zip )
> Revert "Fix 525" -- PR causes Stack Overflow when simulating other rockets.

- core/.classpath
- lib-test/.classpath
- swing/.classpath
Update the eclipse .classpath files to point to the new and updated
jar files that were merged as part of the recent upgrade to Java 11/
Java 13 commits.
> Update eclipse .classpath files

- swing/src/net/sf/openrocket/gui/figure3d/TextureCache.java
- swing/src/net/sf/openrocket/gui/figure3d/photo/exhaust/FlameRenderer.java
The switch to using JOGL uses the current JPEGs, but these textures
cannot be read using the GL.GL_RGBA format which is eventually
propigated to the user by an error dialog showing a NullPointerException
for the texture which failed to load. Using GL.GL_RGB as the format when
loading the textures will resolve the texture loading issue, but the
images are inverted due to differences between AWT and JOGL
interpretation of where the image starts (top left vs bottom left).
Change instead to use the AWTTextureIO class to create the textures
which solves both problems - the loading of the texture as well as
presenting the image in the appropriate orientation.
Closes #573
> Use AWTTextureIO for creating textures from jpegs

- core/src/net/sf/openrocket/simulation/FlightData.java
- core/test/net/sf/openrocket/simulation/TestFlightData.java
The ground hit velocity is calculated by taking the last recorded
total velocity for the flight data and using that as the ground
hit velocity if the last altitude measurement is less than 10 m.
This method worked until commit f11a3e4 introduced the ability to
track and report all events that happened after a GROUND_HIT event.
That commit introduced a GroundStepper that will step between the
GROUND_HIT event and the SIMULATION_END event and will always
add a measurement to the flight data to record the rocket being on
the ground.
A better way of measuring the ground hit velocity is to interpolate
the velocity at the time the GROUND_HIT event, as that would actually
be the appropriate ground hit velocity.
Closes #576
> Fix ground hit velocity calculation

- swing/src/net/sf/openrocket/gui/adaptors/DoubleModel.java
Previous refactoring of the event listeners lost notifications
to classes which care about changes to the DoubleModel. One
such example is the UnitSelector. Ensure that all the
ChangeEventListeners and StateChangeEventListeners are called
when the setValue method is invoked.
Closes #553
> Notify all event listeners when DoubleModel.setValue called

- .travis.yml
New list: (see `$GT/.travis.yml`)
- OracleJDK and OpenJDK
- Versions 11,13
- move underlying image to Ubuntu 18.04 LTS / Bionic Beaver
> [test] Change which JDKs we plan to support -- by changing which ones we test.

- core/src/net/sf/openrocket/rocketcomponent/InstanceContext.java
Added missing instanceNumber parameter to String.format() call in toString()
Added explicit call to component.toString() so intellij can print component name
> Minor issues in InstanceContext

- swing/.classpath
Commit a7c0cb2 removed the OrangeExtensions-1.2.jar file from the
swing project, but failed to remove it from the eclipse classpath.
This fixes that.
> Remove OrangeExtensions-1.2.jar from eclipse classpath

- core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java
- core/src/net/sf/openrocket/aerodynamics/barrowman/FinSetCalc.java
- core/src/net/sf/openrocket/rocketcomponent/SymmetricComponent.java
- core/src/net/sf/openrocket/util/TestRockets.java
- core/test/net/sf/openrocket/aerodynamics/BarrowmanCalculatorTest.java
Fixes #568 by iterating through all instances of rocket components when calculating drag.
Adds unit test for fins on pods as in bug report.
Jar file is at https://www.dropbox.com/s/rnzs2i0xp9e5l0z/OpenRocket-PR603.jar?dl=0 if anyone would like to take it for a spin.
> [Fixes 568] Consider all instances of components when calculating drag

- core/src/net/sf/openrocket/file/openrocket/savers/RocketComponentSaver.java
(because different components have different default instance counts
> [fixes #608] save all instance counts, even if equal to 1 

- swing/src/net/sf/openrocket/gui/scalefigure/RocketPanel.java
- swing/src/net/sf/openrocket/gui/scalefigure/ScaleScrollPane.java
Analysis from Justin Hanney indicates that the CPU is constantly
processing paint events in the ScaleScrollPane.Ruler. Change the
updateSize method to not revalidate and repaint since the
paintComponent method also invokes the updateSize to ensure it is
drawing components of the right size.
This change also refactors the ChangeListener implementation to
have the RulerClass implement the method instead of using an
anonymous class for event handling when ruler units change.
Additionally, this change adds a revalidate call to the scrollPane
to fix an issue where the ruler is not repainted when switching views
from 3D to 2D.
Fixes #615
> Don't revalidate/repaint component in Ruler.updateSize()

- core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java
- core/src/net/sf/openrocket/aerodynamics/barrowman/FinSetCalc.java
- core/src/net/sf/openrocket/util/TestRockets.java
- core/test/net/sf/openrocket/aerodynamics/BarrowmanCalculatorTest.java
[simple_split_fins.ork.zip](https://github.com/openrocket/openrocket/files/4365711/simple_split_fins.ork.zip)
https://github.com/teyrana/openrocket/blob/2c1daea9d1eea139eb5d55e6ac397e4ec67ef61d/core/test/net/sf/openrocket/aerodynamics/BarrowmanCalculatorTest.java#L114-L226
(prebuilt jar available on request)
Fixes:  #600
May help with: #571, #538
> [Request Review] Corrects the cp calculations for Split-fin rockets.  Fixes #600.

- core/src/net/sf/openrocket/rocketcomponent/Rocket.java
- swing/src/net/sf/openrocket/gui/configdialog/ComponentConfigDialog.java
- swing/src/net/sf/openrocket/gui/configdialog/FreeformFinSetConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/RocketComponentConfig.java
Tracked #536 down to inconsistent removal of ComponentConfigDialogs.
Result:
1. Reworked the closing code to consistently be called for all methods of closing the ConfigDialog.
2. Remove itself from the rocket's listener's list on close.
> [Fixes #536] NullPointerException while editing FreeformFinSet Components

- core/src/net/sf/openrocket/database/motor/ThrustCurveMotorSet.java
- core/src/net/sf/openrocket/motor/ThrustCurveMotor.java
- swing/src/net/sf/openrocket/gui/dialogs/motor/thrustcurve/MotorRowFilter.java
- swing/src/net/sf/openrocket/gui/dialogs/motor/thrustcurve/ThrustCurveMotorColumns.java
- swing/test/net/sf/openrocket/gui/MotorRowFilterTest.java
Ensure motors have sane defaults (notably, no null strings)
Create unit test for motor row filter in motor selection dialog
Fix spelling error getTotalImpuse => getTotalImpulse
> [Fixes 620] avoid prevent null strings in new motors

- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
- core/src/net/sf/openrocket/rocketcomponent/FlightConfiguration.java
- core/test/net/sf/openrocket/rocketcomponent/FlightConfigurationTest.java
- swing/src/net/sf/openrocket/gui/components/StageSelector.java
- swing/src/net/sf/openrocket/gui/scalefigure/RocketFigure.java
- swing/src/net/sf/openrocket/gui/scalefigure/RocketPanel.java
Fix the length of the rocket displayed based on the selected stages. This change switches from calculating the bounds of the rocket to using the length already calculated in the flight configuration, which properly reflects the length of active stages and components.
Additionally, while debugging and testing this - I noticed that the display toggle buttons are always set as selected. The second commit changes the button to reflect the state of the active stage.
> [Fixes 452] Reflect length of selected stages

- .gitignore
- openrocket.log
Remove the openrocket.log file that is errantly in the tree.
Update .gitignore to not include openrocket.log in the future.
> Remove openrocket.log from tree

- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
Minor change to display how fin tabs are display on transition bodies. 
Previously it was possible to display non-physical tabs which looked like the tab cut into the fin body, (outside of the mounted body) where the fin tab should be entirely contained within the mount-body.
Now, zero-height is interpreted as a "no fin tab" and a fin tab height of 0.00001 is interpreted as "give me a fin tab of minimum height"   On a transition, this results in an almost triangular fin tab, which 0 height at one end, and a non-zero height on the other end of the fin tab.  (see image below)
> [address 618] improves display of freeform fin tabs on transition bodies

- core/test/net/sf/openrocket/rocketcomponent/FreeformFinSetTest.java
FreeformFinSetTest.testFreeformCMComputation_triangleOnTransition
was broken with the last merge. This change updates the expected
area for the fin tab to be the area of the triangle under the
curve as well as update the new CG contants in the tests.
Identified in #631
> Fix FreeformFinSetTest unit test

- swing/src/net/sf/openrocket/gui/main/BasicFrame.java
Addresses the duplicate "add stage" buttons. 
It contains the changes: 
1. Removes the 'add stage button
~~2. Reorders the buttons to "move up ", "edit", "move down", .... (space)  "delete"~~
~~3. add some spacing.~~
Edit: no consensus on button ordering or icons was reached, so I just left them as they were.
> [fixes #551] [UI] removed 'add stage' text button; reordered remaining buttons

- swing/src/net/sf/openrocket/gui/configdialog/ComponentConfigDialog.java
I botched this upgrade in the other commit, so here's the tweak that makes it work.
> [fixes #640] Dialogs should now close with the [x] button 

- README.md
Adding a link to the README header. The linked dashboard describes overall repository structure. The goal is to help new developers explore project and understand architecture/dependencies. Direct link: https://sourcespy.com/github/openrocketopenrocket/
> [Documentation] Linking project overview dashboard to README

- core/src/net/sf/openrocket/aerodynamics/AbstractAerodynamicCalculator.java
- swing/src/net/sf/openrocket/gui/scalefigure/RocketPanel.java
This fixes #648 (errrors in CP calculation).  The fins in the first example design in the issue are extremely small, and at some angles of attack can result in a CP weight so small as to be meaningless.  This PR only considers CP's with a non-zero weight in finding the worst case for display in the RocketInfo panel.
Also, in RocketPanel, a comparison was being made between CP weight at worst case and rocket minimum mass.  These have nothing obvious to do with each other, so this PR changes the test to be against MathUtil.EPSILON to avoid confusion in the future (this doesn't change behavior, as MIN_MASS is set to EPSILON in the MassCalculator class).
This doesn't address the off-center rendering of CG in some cases (#641), which is referenced in #648 but appears to be unrelated.
> Avoid considering cp with 0 weight when calculating worst-case CP for display in RocketInfo

- core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java
- core/src/net/sf/openrocket/rocketcomponent/RocketComponent.java
- core/src/net/sf/openrocket/rocketcomponent/SymmetricComponent.java
- core/src/net/sf/openrocket/util/TestRockets.java
- core/test/net/sf/openrocket/rocketcomponent/FlightConfigurationTest.java
- core/test/net/sf/openrocket/rocketcomponent/FreeformFinSetTest.java
- core/test/net/sf/openrocket/rocketcomponent/RocketTest.java
- core/test/net/sf/openrocket/rocketcomponent/TransitionTest.java
- swing/src/net/sf/openrocket/gui/dialogs/preset/ComponentPresetChooserDialog.java
Fixes the "auto" calculation on Symmetric Components (to include transitions and bodies) when pods are present (and previously would interfere)
Addresses: #645 
See that issue for more details, and example file.
> [Fixes #645] fix auto radius calculation on Symmetric Components

- core/src/net/sf/openrocket/masscalc/MassCalculation.java
- core/test/net/sf/openrocket/masscalc/MassCalculatorTest.java
This should fix C.G. calculations for Fins-on-pods.
~Would also like to refactor this to be cleaner.~
Refactor is too big a change to be appropriate, here.
> [fixes #641] MassCalculator now accounts for rotations in the tree

- core/src/net/sf/openrocket/aerodynamics/AerodynamicForces.java
- core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java
- core/test/net/sf/openrocket/aerodynamics/BarrowmanCalculatorTest.java
My test for three or more fins in BarrowmanCalculator.calculatedNonAxialForces() turns out to be the only place in the code where it's possible to set the CP off-axis.  Everywhere else, CP is pinned to the axis; the code would be clearer if CP were just a Double instead of a Coordinate (but that's a bigger change than I want to make right now).
So anyway, this pins CP to the axis in this one case as well by removing the "if" statement.  In essence, the code now assumes radial symmetry; even if we're only looking at a single fin we assume there is a matching fin somewhere.
We may want to investigate whether the CP should be allowed to be off-center (say, modeling a glider) in the future, but not right now.
> Pin CP to axis (Fix 654)

- swing/src/net/sf/openrocket/gui/scalefigure/RocketPanel.java
This does _NOT_ affect any calculations -- it just more accurately displays those same values on the 2D view.
This also means that 2d views and 3d views display these values more similarly.
> [fix] 2D Rocket Figure will now display off-axis CoM and CoP

- swing/src/net/sf/openrocket/gui/main/ComponentAddButtons.java
This PR addresses, but does not completely fix #643.
> [ui] Moves new assembly buttons to their own row in the New Component panel.

- swing/src/net/sf/openrocket/gui/util/EditDecalHelper.java
On the OSX platform, the command editor needs to open the program
with using the 'open' command.
> Use the open -a prefix to commands on OSX

- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
- core/src/net/sf/openrocket/rocketcomponent/SymmetricComponent.java
The culprit was treating PodSets like stages in the `SymmetricComponent.getPreviousSymmetricComponent` and ``SymmetricComponent.getNextSymmetricComponent` methods.
[Testable Jar file: Openrocket-fix666.jar](https://drive.google.com/open?id=1YDi1j6dKpxm5zCRofQRmLnqPFpyntrKL)
> Resolves #666 -- fix the "Exception loading stream" error while loading certain rockets.

- core/resources/l10n/messages.properties
- swing/src/net/sf/openrocket/gui/dialogs/PrintDialog.java
- swing/src/net/sf/openrocket/gui/print/DesignReport.java
- swing/src/net/sf/openrocket/gui/print/PrintController.java
Updates the print dialog to allow for simulations to be re-run
or not. Selecting the "Update simulation data" checkbox will
re-run any out of date simulations prior to generating the
design report.
Fixes #637
> [Fixes 637] Update print dialog to allow simulation control

- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/FlightConfigurableTableModel.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/RecoveryConfigurationPanel.java
See #524 for discussion.   
This fix is  just prompting the proper UI element to _actually_ update.
> [fixes #524][ui] Recovery Devices update their name in the 'Recovery' tab

- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/FlightConfigurableTableModel.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/RecoveryConfigurationPanel.java
Check to see if column index returned from the FlightConfigurationTable
model is referencing a valid column before getting the column data.
Additionally, the FlightConfigurationTableModel was not adequately
accounting for the FCID table column when returning the column.
Fixes #677
> Check to see if column index is valid

- core/src/net/sf/openrocket/rocketcomponent/InnerTube.java
basically, if an innertube is enabled or disabled, fire an event, so UI components can update.
> [fixes #681] Fires an change event from InnerTube `setMotorMount(...)`

- swing/src/net/sf/openrocket/gui/scalefigure/AbstractScaleFigure.java
1. removed line:
```
log.warn(String.format("scaling Request from %g => %g  @%s\n", this.userScale, newScaleRequest, this.getClass().getSimpleName()), new Throwable());
```
2. (also harmonized indentation from a mixed spaces + tabs => tabs only -- for this function, only, while I was in the area.)
> [cleanup][debug] removed excess debug statement in `AbstractScaleFigure.scaleTo`

- .idea/runConfigurations/Openrocket_UI_Jar.xml
- core/src/net/sf/openrocket/rocketcomponent/AxialStage.java
- core/src/net/sf/openrocket/rocketcomponent/BodyTube.java
- core/src/net/sf/openrocket/rocketcomponent/BoxBounded.java
- core/src/net/sf/openrocket/rocketcomponent/ComponentAssembly.java
- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
- core/src/net/sf/openrocket/rocketcomponent/FlightConfiguration.java
- core/src/net/sf/openrocket/rocketcomponent/FreeformFinSet.java
- core/src/net/sf/openrocket/rocketcomponent/PodSet.java
- core/src/net/sf/openrocket/rocketcomponent/Rocket.java
- core/src/net/sf/openrocket/rocketcomponent/SymmetricComponent.java
- core/src/net/sf/openrocket/util/BoundingBox.java
- core/src/net/sf/openrocket/util/Coordinate.java
- core/src/net/sf/openrocket/util/TestRockets.java
- core/test/net/sf/openrocket/aerodynamics/BarrowmanCalculatorTest.java
- core/test/net/sf/openrocket/masscalc/MassCalculatorTest.java
- core/test/net/sf/openrocket/rocketcomponent/FlightConfigurationTest.java
- core/test/net/sf/openrocket/rocketcomponent/RocketTest.java
- swing/src/net/sf/openrocket/gui/figure3d/geometry/FinRenderer.java
- swing/src/net/sf/openrocket/gui/print/PrintFigure.java
- swing/src/net/sf/openrocket/gui/scalefigure/AbstractScaleFigure.java
- swing/src/net/sf/openrocket/gui/scalefigure/FinPointFigure.java
- swing/src/net/sf/openrocket/gui/scalefigure/RocketFigure.java
- swing/src/net/sf/openrocket/gui/scalefigure/ScaleScrollPane.java
1. Simplifies code in FlightConfiguration
2. Adds Interface to indicate implementation of getInstanceBoundingBox function
3. Adjusts test to ensure that refactoring still behaves as desired
4. Adds a fix to the Intersection testing code in FreeformFinSet.setPoint
@neilweinstock
This fixes issue #476, as reported.
Here's the new zoom results:
https://drive.google.com/file/d/1rrOCsJG-2JZ9C_G5fI8uY3GvHrVkDW7R/view?usp=sharing
> [fixes #502][Fixes #476] Fixes auto-scrolling of FinPointFigure bounds.

- core/src/net/sf/openrocket/file/openrocket/importt/DocumentConfig.java
- core/src/net/sf/openrocket/rocketcomponent/TubeFinSet.java
- swing/src/net/sf/openrocket/gui/figure3d/geometry/ComponentRenderer.java
- swing/src/net/sf/openrocket/gui/rocketfigure/TubeFinSetShapes.java
The TubeFinSetShapes were applying the supplied transform too many
times, resulting in the the shapes being offset off the viewing area.
The offset transform is already applied to the component instance
that is provided to the TubeFinSetShapes methods, so applying the
transform resulted in the offset being moved to the right.
This change removes the transform being applied to the component
locations when retrieved and only applies a linear transformation
to the component locations when applying the base rotational
transform. Using the linear transform avoids applying the offset
in addition to the rest of the transform.
The problem existed in both the side view and the back view, however
the back view was not as obvious due to the nature of the view. The
common code between both functions …
> Fix TubeFinSet 2D rendering

- snap/local/launcher
- snap/snapcraft.yaml
Drop gcc as a build-dependency as LP#1883392 was fixed and delivered.
Additionally, change personal-files interfaces to be more explicit which
should allow for the snap store assertions which will possibly allow the
auto-connecting of the interfaces upon install for the OpenRocket app.
> Adjustments to snap stuff

- swing/src/net/sf/openrocket/gui/configdialog/ComponentAssemblyConfig.java
Increase the min count for IntegerModel for Pods/Booster config dialog.
The value can be overridden manually by hand, so this just allows the
user to scroll to it with the buttons.
Fixes #702
> [Fix #702] Increase min count for IntegerModel for Pods/Boosters

- core/src/net/sf/openrocket/simulation/BasicEventSimulationEngine.java
Fixes #718
Reset rocket's relative position when its absolute position is reset.
Make sure rocket has lifted off before setting launch rod as cleared.
> Assure rocket has left the ground before it is considered as having cleared launch rod

- core/src/net/sf/openrocket/rocketcomponent/FlightConfiguration.java
When no components are added, a rocket is showing -INFINITY for the
length. This is because the special case for length 0 is checking for
active stages, instead check the rocketBounds.isEmpty() to see if any
bounds have been added.
Fixes #714
> [Fix #714] Check rocketBounds.isEmpty() rather than activeStages for length

- swing/src/net/sf/openrocket/gui/scalefigure/RocketFigure.java
- swing/src/net/sf/openrocket/gui/scalefigure/ScaleScrollPane.java
Center the rocket within the side-view 2d renderings. This is similar to
how the side-view is rendered in 15.03 version.
> Center rocket in side-view 2d renderings

- swing/src/net/sf/openrocket/gui/configdialog/RocketComponentConfig.java
The new layout is should improve legibility and reduce dead space.
This is a purely cosmetic change.
> [fixes #727][gui][cosmetic] Adjusted layout in RocketComponentConfig layout

- core/src/net/sf/openrocket/rocketcomponent/RingComponent.java
- core/src/net/sf/openrocket/rocketcomponent/RocketComponent.java
- swing/src/net/sf/openrocket/gui/dialogs/ScaleDialog.java
- swing/src/net/sf/openrocket/gui/scalefigure/AbstractScaleFigure.java
The root cause was that scaling progresses through Component properties 1-by-1, and this may cause an inconsistent, physically impossible state.   (in this case, an inner diameter > outer diameter).
Fixes:
1. `RocketComponent.ringMass` : clamp the thickness (== outer diameter - inner diameter)  to be >= 0.
2. Disable events during rocket scaling.   This has a side effect of greatly speeding the scaling process ^^
@hcraigmiller
> [Fixes #723] Fix scaling crashes in some circumstances

- core/src/net/sf/openrocket/simulation/GroundStepper.java
Makes consistent with BasicLandingStepper; more generally, if you don't need a more specialized status derived from SimulationStatus (as is the case with RK4SimulationStepper), you don't need to create a new SimulationStatus when entering a new flight phase.
Fixes #725 (creating a new SimulationStatus doesn't automatically copy warnings, so existing warnings were being forgotten on landing)
> Don't create new SimulationStatus on landing.

- core/src/net/sf/openrocket/rocketcomponent/FreeformFinSet.java
- swing/src/net/sf/openrocket/gui/configdialog/FreeformFinSetConfig.java
- swing/src/net/sf/openrocket/gui/scalefigure/AbstractScaleFigure.java
- swing/src/net/sf/openrocket/gui/scalefigure/FinPointFigure.java
- swing/src/net/sf/openrocket/gui/scalefigure/ScaleScrollPane.java
- swing/src/net/sf/openrocket/gui/scalefigure/ScaleSelector.java
Contains the fixes: 
1. fixes the auto-zoom for fin points
2. if a user drags a fin point out-of-bounds, it will now scroll with the (new) point.
> Fix/FreeformFinConfig - editing fin points

- core/src/net/sf/openrocket/rocketcomponent/SymmetricComponent.java
- core/test/net/sf/openrocket/rocketcomponent/RocketTest.java
I tracked this down to a logic error in `SymmetricComponent.getPreviousSymmetricComponent`.
And fixed the error, obviously.  (+ some minor cleanup).
> Resolves #742 - Crash on rocket-load

- core/src/net/sf/openrocket/rocketcomponent/RailButton.java
Actual fix: removed debug hard-codes.
> [fixes #740] Railbuttons now correctly load instance-separation

- core/src/net/sf/openrocket/aerodynamics/barrowman/FinSetCalc.java
In FinSetCalc.calculateFinGeometry(), make sure x coordinates of intersections between lines defining fins and strips being used to estimate geometry aren't beyond bounds of fin.
Fixes #746
> clamp x coordinate of intersections

- core/src/net/sf/openrocket/simulation/BasicEventSimulationEngine.java
- core/src/net/sf/openrocket/simulation/MotorClusterState.java
- core/src/net/sf/openrocket/simulation/SimulationStatus.java
Fixes #762 
Background:  a motor that has burned out can be in one of two states:  DELAYING (the delay charge has not yet fired) or SPENT (either the delay charge, if any, has fired or there was no delay charge).
The existing SimulationStatus:getActiveMotors() method returned a list of motors that were active for the stage, and which were not SPENT.  The test for the warning redundantly tested for a SPENT motor, still didn't test for a DELAYING motor, and consequently set the warning.
This PR
(1) adds a boolean MotorClusterStatus:isDelaying() method, analogous to the existing state test methods
(2) modifies SimulationStatus.java:getActiveMotors() to return all the motors, not just the ones that aren't SPENT.  This is to improve consistency with FlightConfiguration:getActiveMotors(), and …
> Don't set a warning if recovery device is deployed while motor is coasting

- core/src/net/sf/openrocket/rocketcomponent/FlightConfiguration.java
- core/src/net/sf/openrocket/rocketcomponent/InnerTube.java
- core/src/net/sf/openrocket/rocketcomponent/LaunchLug.java
- core/src/net/sf/openrocket/rocketcomponent/RailButton.java
- core/src/net/sf/openrocket/rocketcomponent/RingComponent.java
- core/src/net/sf/openrocket/util/TestRockets.java
- core/test/net/sf/openrocket/rocketcomponent/BoundingBoxTest.java
- swing/src/net/sf/openrocket/gui/scalefigure/RocketFigure.java
This primarily addresses erroneous dimension calculations on stages with LaunchLugs.  
Similar bugs are fixed on `RailButtons`, `RingComponents` and `InnerTube` components, by implementing the `BoxBounded` interface on each.
> Fixes #756 -- Launch Lug & Stage Dimensions

- core/src/net/sf/openrocket/masscalc/MassCalculation.java
- core/src/net/sf/openrocket/util/TestRockets.java
- core/test/net/sf/openrocket/masscalc/MassCalculatorTest.java
Apply CG override distance to be the distance from the beginning of the component.
> [fixes #755] Correctly calculate cg.x override

- swing/src/net/sf/openrocket/gui/rocketfigure/RailButtonShapes.java
Also includes some refactoring in `RailButtonShapes` so that `getShapesSide` and `getShapesBack` have a more similar structure -- the easier to see their differences.
> [fix #777] Railbuttons now correctly render in rear-view, when rotated

- snap/local/launcher
- snap/snapcraft.yaml
Initial feedback from the Snapcraft store suggests to further refine
the dot-java-user-prefs interface name to include OpenRocket so its
clear to a user which files are being accessed. This changes the
interface name to accommodate that feedback.
> Rename user preference interface to include openrocket

- core/src/net/sf/openrocket/simulation/SimulationOptions.java
- swing/src/net/sf/openrocket/gui/scalefigure/RocketPanel.java
This PR addresses #671 (data in RocketPanel doesn't match simulation results) by searching for a Simulation associated with the current FlightConfiguration.  Two things I'd like input on before proceeding:
(1) Yes, I said "a" simulation, not "the" simulation.  It is possible to have multiple Simulations associated with a single FlightConfiguration; this PR simply chooses one of them so there is no guarantee it'll pick the one the user prefers.  A change that would get around this would be to directly choose a current Simulation in the current "Flight configuration:" dropdown; we could either just put the Simulation names in the dropdown, or we have plenty of room to use something like
Simulation 1 [J381-8;J150-0]
concatenating the Simulation name with the FlightConfiguration name
(2) When …
> Use simulation options (addresses 

- core/src/net/sf/openrocket/file/openrocket/importt/FinTabPositionSetter.java
- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
- core/src/net/sf/openrocket/rocketcomponent/FreeformFinSet.java
This is a partial fix for #794 (Freeform fin set tab length is different when opened than when saved).  This turns out to be a new manifestation of #527 (fin tabs loaded incorrectly), which was fixed for trapezoidal and ellipsoidal finsets in #530.  There was quite a bit of discussion as to why this is the right approach in the comments on that PR.
In the case of freeform fins, changing the fin tab length (which happens as part of loading the file) causes a call to a general update() method, which validates the fin tab.  This PR modifies the call to update() so it only validates the tab when the length of the fin has changed, bringing it into line with the other finset types.
Submitting this PR now, as the symptoms in the reported issue appear to be an unrelated UI bug.
> Only validate freeform fin tab when fin length changes

- swing/src/net/sf/openrocket/gui/scalefigure/RocketPanel.java
Only set the CG and CP for the 3D renderings when the length
is greater than 0. This makes the 3D rendering behavior consistent
with the 2D side view
Fixes #776
> Only draw carets in 3d when length > 0

- swing/src/net/sf/openrocket/gui/rocketfigure/MassComponentShapes.java
- swing/src/net/sf/openrocket/gui/rocketfigure/ParachuteShapes.java
- swing/src/net/sf/openrocket/gui/rocketfigure/StreamerShapes.java
2D side view renderings of mass components within body tubes
were adjusted forward based off the radius of the object. This
change corrects the X position adjustement and makes it consistent
with 15.03 and 3D renderings.
Closes #785
Closes #828
> Fix offset locations of mass components

- core/src/net/sf/openrocket/database/ComponentPresetDatabase.java
ComponentPresetDatabase:listForTypes() tried to cast an array, which  failed at runtime.  Create the array with the right type in the first place.
Fixes #650.
> Avoid trying to cast an array type

- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
- swing/src/net/sf/openrocket/gui/configdialog/FinSetConfig.java
Fixes #833 
Two commits: first restructures the fintab calculation a bit without changing anything, second changes calculation assuming Coaxial to more general calculation with SymmetricComponent.
> Allow automatic calculation of fin tabs on transitions

- core/src/net/sf/openrocket/rocketcomponent/ComponentAssembly.java
- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
- core/src/net/sf/openrocket/rocketcomponent/InternalComponent.java
- core/src/net/sf/openrocket/rocketcomponent/ParallelStage.java
- core/src/net/sf/openrocket/rocketcomponent/PodSet.java
- core/src/net/sf/openrocket/rocketcomponent/RailButton.java
- core/src/net/sf/openrocket/rocketcomponent/TubeFinSet.java
Fixes #834.
Also, while tracking it down, I noticed there are several implementations of setAxialMethod() that call fireComponentChangeEvent() with parameter vales other than ComponentChangeEvent.NONFUNCTIONAL_CHANGE.  Since the method is documented as only changing external views of the component position, it's a NONFUNCTIONAL_CHANGE. Calling it with some other value can cause unnecessary computation.
> Update UI appropriately when FinSet::setTabOffsetMethod() is called

- .gitignore
- snap/local/launcher
- snap/snapcraft.yaml
The snap store review team has approved auto-connecting the plugs
for OpenRocket to allow the application to access the .openrocket
and .java/.userPrefs/OpenRocket directories on Linux without being
prompted by the user.
This patch adjusts the snapcraft.yaml definition per the feedback at
https://forum.snapcraft.io/t/request-for-personal-files-for-openrocket/20579/5
Once this is updated, we can start automatically building and publishing
snap packages for the unstable branch to the snapstore.
> Simplify plugs per snap store review feedback

- core/src/net/sf/openrocket/rocketcomponent/TrapezoidFinSet.java
- core/test/net/sf/openrocket/rocketcomponent/FinSetTest.java
TrapezoidFinSet fin count was reduced to 1 in previous commits in order
to fix a bug. The actual problem was that the instancecount was not
persisted in the ork file. This change restores the default to 3.
Fixes #850
> Restore default fin count to 3 for TrapezoidFinSet

- swing/src/net/sf/openrocket/gui/scalefigure/FinPointFigure.java
Adjust the colors in the freeform fin editor to use a blue hue as
was used in previous releases. Major grid lines are slightly darker
than minor grid lines. Also Adjust selected point color to be red.
Additionally, adjust the minor and major tick size to scale with the
current selection.
Fixes #836
Fixes #837
> Adjust grid in freeform fin editor

- swing/src/net/sf/openrocket/gui/figure3d/RocketFigure3d.java
When setting up the view for 3D figures, the Y span is doubled
incorrectly. This appears to be legacy behavior and the BoundingBox
itself accounts for the full span. Removing the 2x scaling resolves the
rocket scaling appropriately.
Fixes #788
> Fix rocket scaling in 3D views

- core/test/net/sf/openrocket/rocketcomponent/TrapezoidFinSetTest.java
Commit 312e90 updated finset count and tests for FinSets but not
the TrapezoidFinSetTest.testMultiplicity()
> Fix TrapezoidFinSetTest

- swing/src/net/sf/openrocket/gui/scalefigure/FinPointFigure.java
Make the points in the fin point scale figure red (once again) to better
show the location of the points.
Fixes #856
> Make points on fin red for usability

- swing/src/net/sf/openrocket/gui/figure3d/RocketFigure3d.java
Explicitly set the glViewport size on reshape in order to ensure it is
rendered at the full scale of the viewport. Not doing so causes the
display to render very small.
Fixes #790
> Set the glViewport size on reshape

- swing/src/net/sf/openrocket/gui/main/BasicFrame.java
Exporting the rocket to a rocksim format should use the extension .rkt
rather than .ork. However, refactoring the code between save as and
export in commit 4924773 in correctly used the .ork extension in the
exportAsAction.
Fixes #872
> Force a .rkt extension rather than .ork on export

- core/src/net/sf/openrocket/simulation/RK4SimulationStepper.java
This fixes Issue #890.
Note that it trades losing the last simulation data point with losing the first.  However, the data for all points prior to liftoff is pretty much nonsense anyway: until the motor thrust exceeds the force of gravity, the rocket sinks into the ground in the RK4SimulationStepper, and then its location is patched in BasicEventSimulationEngine.  This actually doesn't end up affecting the simulation in any observable way, so it isn't a real problem.
> save RK4SimulationStepper simulation step data after step, not before it

- swing/src/net/sf/openrocket/gui/dialogs/motor/thrustcurve/MotorInformationPanel.java
Calls invalidate() as the last action inside MotorInformationPanel.updateData(), forcing a redraw of the panel.  This makes sure the panel is large enough to display all of its contents
Also, clean up display of the compatible cases a little bit by adding a space between cases, and wrapping in <html></html> tags to allow line breaks.
> Invalidate MotorInformationPanel when updating (fixes #885)

- .gitignore
- core/src/net/sf/openrocket/file/rocksim/importt/FinSetHandler.java
- core/src/net/sf/openrocket/rocketcomponent/position/AxialMethod.java
I apologize for the (again) whitespace changes... I can't seem to figure out how to make VSCode not change them. I've tried several user setting overrides, but it keeps changing correcting the whitespace even when I think I'm telling it not to.
I believe this fixes #881. I thought about (_and tried_) changing the `RocksimCommonConstants.ROCKSIM_TO_OPENROCKET_LENGTH` constant with a negative sign, but I soon realized that only the relative position field was bungled, and changing this constant screwed up other parts of the import. I tested it on my own RockSim model, the [OEM-provided PublicMissiles Spitfire kit file.](https://publicmissiles.com/images/spitfire.zip) The issue wasn't present for me in the official 15.03 `.jar` app, but I did replicate the issue easily with the current …
> Fix #881, #907 issues

- core/test/net/sf/openrocket/rocketcomponent/FinSetTest.java
Commit 936333a2 re-introduced the AxialMethod.ABSOLUTE as an offset
method but did not update the corresponding unit test. Add in the
expected offset value for AxialMethod.ABSOLUTE.
Fixes #931
> Fix FinSetTest.testTabLocation

- swing/src/net/sf/openrocket/gui/figure3d/RocketFigure3d.java
- swing/src/net/sf/openrocket/gui/scalefigure/RocketPanel.java
GLJPanel handles display scaling better than the GLCanvas does natively.
Change to use the GLJPanel always when rendering in 3D mode. FBO
(offscreen rendering) will be set on the GLJPanel via the
GLCapabilities.
Also, ensure when creating a Graphics2D object from a GLOverlay to set
the current transform to the default transform for the component. The
default transform of the swing components will take into account the
scaling of the screen that it is rendered on. By setting the transform
of the overlay, we can be sure that it gets the scaling information as
well.
Fixes #854
> Fix scaling on high dpi monitors

- swing/src/net/sf/openrocket/gui/figure3d/RocketFigure3d.java
Relying primarily on the FBO option for capabilities passed to the
GLJPanel interferes with the part picking algorithm. Revert that
piece of the fix.
Fixes #937
> Don't switch to use GLJPanel always

- core/src/net/sf/openrocket/rocketcomponent/FlightConfigurableParameterSet.java
- core/test/net/sf/openrocket/rocketcomponent/ParameterSetTest.java
Change to use a LinkedHashMap instead of a HashMap in the
FlightConfigurableParameterSet. This ensures that the ordering is
consistent with the way the user added the flight configurations.
This will also be true for when reading the flight configurations from
a file. Additionally, to preserve the ordering, do not sort the
FlightConfigurationIds in getIds().
Fixes #845
> FlightConfigurableParameterSet Predictable Order

- swing/src/net/sf/openrocket/gui/components/ConfigurationComboBox.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/FlightConfigurablePanel.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/FlightConfigurationPanel.java
Restore the behavior from the 15.03 version of the flight configuration
panel. Selected flight configuration is synchronized with the rocket
panel where the design is being done and vice versa.
Fixes #916
> Restore 15.03 selection behavior for flight config

- swing/src/net/sf/openrocket/gui/figure3d/RealisticRenderer.java
- swing/src/net/sf/openrocket/gui/figure3d/UnfinishedRenderer.java
Use the provided alpha from the color when it is available when
rendering the model in the 3d finished view. The 3d unfinished view will
continue to override the alpha to show interior components.
Fixes #878
> Fix transparency display issue

- swing/src/net/sf/openrocket/gui/components/EditableSpinner.java
- swing/src/net/sf/openrocket/gui/figure3d/photo/PhotoSettingsConfig.java
Spinner options in photo frame does not have an editor, so doesn't
allow for keyboard edits. Add an EditableSpinner class which
automatically sets the editor and use that instead of JSpinner.
Note: this EditableSpinner can be used throughout OR, but not including
everywhere as it is a large change at this point and I'd rather wait for
the refactor until after release, so change is small.
Fixes #873
> Make spinner options in photo keyboard editable

- swing/src/net/sf/openrocket/gui/configdialog/LaunchLugConfig.java
Fixed the issue of the lug distance spinner not updating after another reference point was set. Was fixed by trigger a stateChange on the DoubleModel of the AxialOffset of the lug after an item was selected in the reference JComboBox.
Fixes #928 
Here is the [jar](https://www.dropbox.com/s/zdelttkrufxp3nb/OpenRocket-928.jar?dl=0) for testing.
> [fixes #928] Fix launch lug reference

- core/src/net/sf/openrocket/rocketcomponent/LaunchLug.java
- core/src/net/sf/openrocket/rocketcomponent/RailButton.java
- core/test/net/sf/openrocket/rocketcomponent/LaunchLugTest.java
- core/test/net/sf/openrocket/rocketcomponent/RocketTest.java
Changed the default launch lug & rail button rotation to 180°, as per suggestion on #940 .
[Java file](https://www.dropbox.com/s/anonqe9iu7m1ye9/OpenRocket-940.jar?dl=0) for testing.
(also changed the layout of the smokeShader, not needed for this issue, but it ended up in this commit, sorry)
> Lug & rail default rotation 180°

- swing/src/net/sf/openrocket/gui/figure3d/geometry/MassObjectRenderer.java
This fixes issue #859 in which the radial offset of mass components were not getting added in any 3D view. Fixed it by adding the offsets xOffset and yOffset to the vertices in MassObjectRenderer.
Here is [jar file](https://www.dropbox.com/s/nqc91h4s15i73ft/OpenRocket-859.jar?dl=0) for testing.
> [fixes #859] Fix mass component radial offset in 3D view

- core/resources/l10n/messages.properties
- swing/src/net/sf/openrocket/gui/configdialog/ShockCordConfig.java
- swing/src/net/sf/openrocket/gui/rocketfigure/ShockCordShapes.java
This pull fixes #843, where you could not change the radial position of the shock cord component.
The fix was to first add the radial position tab to the shock cord configuration panel into ShockCordConfig. These settings were taken from the MassComponentConfig, which does have radial positioning. I also had to add new translations for the shock cord radial positioning in message.properties.
Next, the changes in radial position settings of the shock cord had to be applied to the 2D figure of the shock cord component. This was done by porting some settings from the MassComponentShapes to the ShockCordShapes.
! Be aware, for the radial positioning of the shock cord to work in the 3D view, #957 first needs to be merged. I already included these changes for the jar file, so that you can still …
> [fixes #843] Added radial positioning for the shock cord component

- swing/src/net/sf/openrocket/gui/figure3d/RealisticRenderer.java
This pull fixes issue #904 where the inside of a tube did not match the color of the outside. The previous implementation was deliberately programmed to have the default appearance (e.g. cardboard appearance) for the inside (unless you set the alpha of the appearance to a value lower than 255). 
As mentioned on the [forum](https://www.rocketryforum.com/threads/painting-the-inside-of-a-body-tube-with-openrocket.165220/#post-2114880), this might have be done to reflect the reality of not painting the inside, but only the outside of e.g. the body tube. Because of this, I will work on #905 which gives the user the control for different inside and outside colors.
Here is the [jar file](https://www.dropbox.com/s/5ty1uvgi266l5yv/OpenRocket-904.jar?dl=0) for testing.
> [fixes #904] Fix inside color tube different color from outside

- swing/src/net/sf/openrocket/gui/configdialog/AppearancePanel.java
This PR fixes #651 where the shine value would have the wrong initial value.
The problem was that the shineModel takes in the value of ab. However, ab's appearance is first set to the default appearance for that component. For example, the body tube's default appearance has a shine value of 30%, thus the spinner will be set to 30. When unchecking the default value, ab now has a new (non-default) appearance, with init value 0. The spinner is still at 30% at this time, but the shineModel value is already at 0. So when you change the slider or use the spinner up/down button, you suddenly jump from the 30%-value to the 0%-value.
So at the initialization of shineModel, I set its value equal to the reset value 0, found in resetToDefaults of AppearanceBuilder.
Here is the [jar …
> [fixes #651] Fix shine wrong init value

- swing/src/net/sf/openrocket/gui/configdialog/AppearancePanel.java
This PR fixes #971 where the 'default appearance' would uncheck itself after first unchecking the checkbox, then checking it again, closing the Appearance Panel and then reopening the panel.
The problem was that when the Appearance Panel opens, it checks the appearance of the component to know whether it should check or uncheck the default appearance. If the component's appearance is null, the default appearance checkbox will be checked and the default appearance is used. Else, the Appearance Panel will use the appearance of the component and thus uncheck the default appearance checkbox, since the component already has a custom appearance.
The problem is however that if you first uncheck the checkbox, then check it again, the component will be assigned the default appearance, but this is …
> [fixes #971] Fix default appearance unchecking

- core/resources/l10n/messages.properties
- core/src/net/sf/openrocket/document/OpenRocketDocument.java
- core/src/net/sf/openrocket/file/GeneralRocketSaver.java
- core/src/net/sf/openrocket/file/openrocket/importt/AppearanceHandler.java
- core/src/net/sf/openrocket/file/openrocket/importt/ComponentParameterHandler.java
- core/src/net/sf/openrocket/file/openrocket/importt/InsideAppearanceHandler.java
- core/src/net/sf/openrocket/file/openrocket/savers/RocketComponentSaver.java
- core/src/net/sf/openrocket/rocketcomponent/BodyTube.java
- core/src/net/sf/openrocket/rocketcomponent/InsideColorComponent.java
- core/src/net/sf/openrocket/rocketcomponent/InsideColorComponentHandler.java
- core/src/net/sf/openrocket/rocketcomponent/LaunchLug.java
- core/src/net/sf/openrocket/rocketcomponent/NoseCone.java
- core/src/net/sf/openrocket/rocketcomponent/Transition.java
- core/src/net/sf/openrocket/rocketcomponent/TubeFinSet.java
- swing/src/net/sf/openrocket/gui/configdialog/AppearancePanel.java
- swing/src/net/sf/openrocket/gui/figure3d/RealisticRenderer.java
- swing/src/net/sf/openrocket/gui/util/EditDecalHelper.java
This PR fixes #905 which was a feature request to be able to select a different outside and inside color of certain components. This is especially useful if, in real life, e.g. you would paint only the outside of the body tube, but leave the inside unpainted (so a cardboard look).
The general idea is: if you have a tube that can have a different outside and inside appearance, then it will have the option in the Appearance editor to change the appearance of both the inside and the outside (see images below). These are just two different tabs. For the inside, you can select whether you want the inside to just be the same as the outside (see checkbutton 'Same as outside') and change all the appearance parameters just like you would do in a normal appearance editor.
You also have the option …
> [fixes #905] Added ability to select a different color for the outside and inside of component

- core/src/net/sf/openrocket/document/OpenRocketDocument.java
- swing/src/net/sf/openrocket/gui/figure3d/photo/PhotoFrame.java
- swing/src/net/sf/openrocket/gui/figure3d/photo/PhotoPanel.java
If Photo Studio window and the main design window are visible at the same time, many changes made to the design don't immediately show up in the photo studio, but will show up when the photo view is dragged or changed.
This PR makes the updates immediate by routing all change events to the top level document change event.
Also fixes a couple of tangentially related problems:
1. every time the Photo Studio is opened a new copy of everything including the OpenGL context, the window data, and the event listeners is created.  These are never destroyed, so the event listener list fills up with old copies of the photo studio, which leaks resources and slows everything down.  Added a listener to the window close event, and made sure the window is disposed on close.
2. If all stages have been …
> More improvements for Bug #954

- swing/src/net/sf/openrocket/gui/figure3d/photo/sky/SkyBoxCross.java
This PR fixes #977 where the sky image for Stormy Days would go blank after selecting it, closing Photo Studio, reopening Photo Studio and trying Stormy Days again.
The problem was that the north, east, west... textures inside SkyBoxCross were being saved/loaded in the Storm singleton class, but the textures get somewhat bound to the gl. So, I added a variable to check what the previous gl was. If it does not equal the current gl, then reload the textures.
Here is a [jar file](https://www.dropbox.com/s/ir2qorsesc31vrq/OpenRocket-977.jar?dl=0) for testing.
> [fixes #977] Fix Storm sky image going blank

- swing/src/net/sf/openrocket/gui/figure3d/photo/PhotoSettingsConfig.java
This PR fixes #950 where in PhotoStudio the sky image option would just have an empty option to use the sky color instead of an image.
In line with how the appearance in a component config is implemented, I made it so that the empty option now displays a "< none >"-message. This is done by adding a dummy sky object with as string value the "< none >"-message.
@hcraigmiller suggested to also leave out the 'Sky'-terms out of 'Sky color' and 'Sky image' because it is already present as the bold 'Sky'-label. I decided not to change this because to be honest I don't really look at those title labels, plus it reduces having to continuously look at different locations to understand what's going on.
Here is a [jar file](https://www.dropbox.com/s/4ckavcgf78h73o2/OpenRocket-950.jar?dl=0) for …
> [fixes #950] Photo Studio sky image empty option

- swing/src/net/sf/openrocket/gui/util/GUIUtil.java
- swing/src/net/sf/openrocket/startup/OSXSetup.java
This PR fixes #948 where the foreground of active tabbed panes was white on OSX machines, making it very much unreadable. All credits for the solution go to @wolsen .
Here is a [jar file](https://www.dropbox.com/s/rtv7vj30nwfgr67/OpenRocket-948.jar?dl=0) for testing.
> [fixes #948] Fix bad appearance of active tabs on Mac

- core/src/net/sf/openrocket/rocketcomponent/BodyTube.java
- core/src/net/sf/openrocket/rocketcomponent/Bulkhead.java
- core/src/net/sf/openrocket/rocketcomponent/CenteringRing.java
- core/src/net/sf/openrocket/rocketcomponent/EngineBlock.java
- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
- core/src/net/sf/openrocket/rocketcomponent/InnerTube.java
- core/src/net/sf/openrocket/rocketcomponent/LaunchLug.java
- core/src/net/sf/openrocket/rocketcomponent/MassComponent.java
- core/src/net/sf/openrocket/rocketcomponent/NoseCone.java
- core/src/net/sf/openrocket/rocketcomponent/Parachute.java
- core/src/net/sf/openrocket/rocketcomponent/RailButton.java
- core/src/net/sf/openrocket/rocketcomponent/RocketComponent.java
- core/src/net/sf/openrocket/rocketcomponent/ShockCord.java
- core/src/net/sf/openrocket/rocketcomponent/Streamer.java
- core/src/net/sf/openrocket/rocketcomponent/Transition.java
- core/src/net/sf/openrocket/rocketcomponent/TubeCoupler.java
- core/src/net/sf/openrocket/rocketcomponent/TubeFinSet.java
- swing/src/net/sf/openrocket/gui/rocketfigure/RocketComponentShape.java
- swing/src/net/sf/openrocket/gui/scalefigure/RocketFigure.java
This PR fixes #976 where you could sometimes not select the launch lug when it was behind the body tube.
The problem was in RocketFigure. How drawing the shapes works is that you have a list of all the RocketComponentShapes, figureShapes, to be drawn. You then parse this list and draw each shape. However, this list was implemented as an ArrayList. ArrayLists don't have a fixed order when parsing, meaning that if you have an ArrayList with elements {A, B, C}, then the first parse, you might get {A, B, C}, but the next time, it might be {B, A, C}.
What finally caused the problem of not being able to select the launch lug when it is behind the body tube shape, is that sometimes the body tube would be drawn first and the launch lug drawn last. This had the effect that the body tube is drawn …
> [fixes #976] Sometimes can't select components when behind body tube

- swing/src/net/sf/openrocket/gui/widgets/SelectColorButton.java
- swing/src/net/sf/openrocket/gui/widgets/SelectColorToggleButton.java
This PR (I do very much hope) fixes #989 and #992 where the editor view went blank when switching to the 3D view + where a very high increase in CPU usage was noticed. Okay, so I did an oopsie in my PR of fixing bad highlight colors. The code written to change the foreground for the SelectColorButton and SelectColorToggleButton should never have been put inside the paint-method. Not only does this cause a very high CPU usage, it also messes up the init-method calling of the editor window (which caused it to go blank).
I added the foreground updating in a changelistener and only let that code execute on OSX-devices (i.e. devices that have a custom Button.selectForeground or ToggleButton.selectForeground defined).
Tested on Mac OSX Big Sur to check the functionality and testen on Windows 10 …
> [fixes #989 & #992] Fix 3D view going blank + high CPU usage

- .gitignore
- .idea/ant.xml
- .idea/misc.xml
When working in the IntelliJ IDE, it creates some files that I very often have to ignore or unstage when making commits. This PR adds some common IntelliJ-files that should be ignored to the gitignore.
Besides that, it also updates the .idea/misc.xml-file to use project language level 10 instead of the previous version 9. This is the minimum level that is necessary to compile some of the OR functions. (Right now I always had to manually change the language level every time I switched to another branch)
I also added .idea/ant.xml for ant building inside IntelliJ.
> Added gitignores for IntelliJ-files

- core/src/net/sf/openrocket/document/OpenRocketDocument.java
- core/src/net/sf/openrocket/models/atmosphere/InterpolatingAtmosphericModel.java
- core/src/net/sf/openrocket/motor/MotorConfiguration.java
- core/src/net/sf/openrocket/rocketcomponent/DeploymentConfiguration.java
- core/src/net/sf/openrocket/rocketcomponent/StageSeparationConfiguration.java
- core/src/net/sf/openrocket/simulation/BasicEventSimulationEngine.java
- core/src/net/sf/openrocket/simulation/FlightData.java
- core/src/net/sf/openrocket/simulation/listeners/system/GroundHitListener.java
- swing/src/net/sf/openrocket/gui/main/BasicFrame.java
- swing/src/net/sf/openrocket/gui/main/SimulationPanel.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/FlightConfigurablePanel.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/FlightConfigurationPanel.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/MotorConfigurationPanel.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/RecoveryConfigurationPanel.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/SeparationConfigurationPanel.java
- swing/src/net/sf/openrocket/gui/scalefigure/RocketPanel.java
Okay, so this was a pretty deep problem to solve.
I noticed that the problem only occurred on velocity at deployment, ground hit velocity and optimum delay. After a bit of searching, I found that the simulation events of recovery device hit and ground hit in BasicSimulationEngine weren't getting triggered. To see what happens, I printed some log info about the simulation events when the problem arose and this was the output. The following shows in chronological order the different simulation events that occur after I have changed a parameter of a rocket component (event of altitude change not included, because there were a lot of them):
Event - Launch
Event - Motor ignition
Event - Lift-off
Event - Launch rod clearance
Event - Motor burnout
Event - Ejection charge
Event - Apogee
Event - …
> [fixes #927 & #771] Fix auto-run simulation NA values

- core/resources/l10n/messages.properties
- swing/src/net/sf/openrocket/database/MotorDatabaseLoader.java
- swing/src/net/sf/openrocket/gui/dialogs/SwingWorkerDialog.java
- swing/src/net/sf/openrocket/startup/providers/BlockingMotorDatabaseProvider.java
This PR fixes #987 where an issue in a user defined thrust curve file would throw an exception, thus crashing OR. This PR shows a warning dialog instead and ignores the faulty thrust curve file.
The warning dialog looks as follows:
Here is a [jar file](https://drive.google.com/file/d/1RGKhM87h_tnvKAoE2h72aREDLXgJyD-u/view?usp=sharing) for testing (note, you need to have [RATT.eng](https://github.com/openrocket/openrocket/files/7150168/RATT.eng.zip) in your user defined thrust curve directory to be able to test this issue, as stated in #987.
> [fixes #987] Use warning dialog for thrust curve import issues

- core/src/net/sf/openrocket/masscalc/MassCalculation.java
- core/test/net/sf/openrocket/masscalc/MassCalculatorTest.java
Fixes #1034. The reference point when overriding the center of gravity is the front of the component.
> Use correct zero point for center of gravity calculation

- core/src/net/sf/openrocket/aerodynamics/barrowman/SymmetricComponentCalc.java
This PR fixes #1044, where in the calculateOgiveNoseInterpolator-method, cdMach1 was implemented as being the cd at Mach = 1.3, instead of the intended cd at Mach = 1.
> [fixes #1044] Correct cdMach1 for ogive nose interpolator

- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
- swing/src/net/sf/openrocket/gui/rocketfigure/FinSetShapes.java
This PR fixes #1003 which was a bug that when a FinSet was to the right of the end of its parent body, the last point of the root of the FinSet would clip to the end of the parent body.
The problem was that the getMountPoints-method in FinSet.java contained some code that deliberately clipped the last point of the root of the FinSet to the end of the parent body, if the position of the last point was beyond the end position of the parent body.
I just removed that code block, since it seems illogical (the FinSet is allowed to go further than the parent body and the clipping only has effect on the root of the FinSet; e.g. in a freeform FinSet, all the points besides the root were allowed to go further than the parent body, so I don't see a reason why the root shouldn't be allowed to) and …
> [fixes #1003] Fix FinSet point clipping when further than parent body

- core/resources/l10n/messages.properties
- swing/src/net/sf/openrocket/gui/dialogs/optimization/GeneralOptimizationDialog.java
- swing/src/net/sf/openrocket/gui/main/BasicFrame.java
This PR fixes #1058. When the OR document does not have simulations present, it is unable to run the optimizer and would previously throw an Exception. This commit shows an info dialog for that and stops the creation of the GeneralOptimizationDialog.
Here is a [jar file](https://drive.google.com/file/d/1SEu2FH5hq8ftiUIFsxjHbyv9gDRDce1U/view?usp=sharing) for testing.
> [fixes #1058] Launch info dialog for no simulations GeneralOptimizer

- core/src/net/sf/openrocket/rocketcomponent/EllipticalFinSet.java
- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
- core/src/net/sf/openrocket/rocketcomponent/FreeformFinSet.java
- core/src/net/sf/openrocket/rocketcomponent/TrapezoidFinSet.java
- core/test/net/sf/openrocket/rocketcomponent/FinSetTest.java
This fix addresses Issue #868, and may help with #865.
Basically, the update function in fin set wasn't checking the fin-tab properties, so I inserted a call to `validateFinTab()`.   It appears to work, now, according to the description / images in #868.    Thanks to @hcraigmiller for the high-quality bug report 👍 
@JoePfeiffer I got you fam.
> [fixes #868] Fin tabs correctly adjust their location when the fin tab _length_ is changed.

- swing/src/net/sf/openrocket/gui/figure3d/photo/PhotoPanel.java
This PR fixes #997. The issue was that the exhaust effects' start point was at the top stage, as can be [seen here](https://github.com/openrocket/openrocket/issues/997#issuecomment-1010332110), instead of on the bottom stage. The fix was very simple, because there was already logic implemented to use the bottom stage motor for the exhaust effects, but the problem was that there was a bottomStage.getStageNumber() method that was never assigned to the bottomStageNumber variable, causing it to always remain 0. This PR just simply assigns bottomStageNumber _et voila_.
Here is a [jar file](https://drive.google.com/file/d/1hB3dAN6-dkGASg09Qa_YFd-YLpUdWWq3/view?usp=sharing) for testing.
> [fixes #997] Fix Photo Studio exhaust effects starting at top stage

- swing/src/net/sf/openrocket/gui/dialogs/BugReportDialog.java
- swing/src/net/sf/openrocket/logging/LogLine.java
This PR does not have an issue tied to it, but it is a quick fix to improving bug reports. This PR puts the lines "_Include detailed steps on how to trigger the bug:_" and "_What does the software do and what in your opinion should it do in the case described above:_" in bold and adds a line "_(You can edit text directly in this window)_" because I was shamefully unaware this was possible until recently.
Old bug report:
New bug report:
I thought this would be useful, because I have seen in the past that people just post their bug report without any indication of how the bug was created, after which we often have to close the issue due to lack of information. My goal with this PR is to guide users to elaborating their bug report.
Oh yeah and I've also edited the LogLine number formatting …
> Improve Bug Report formatting

- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
This PR fixes the root edge of the fin tab not being drawn, as stated in #1092. It's a simple fix: just append the start coordinate point of the fin tab to the coordinate list so that a final line is drawn from the last point to the starting point.
Result:
Here is a [jar file](https://drive.google.com/file/d/1E9MXXx5Beghgu31Zyjt2TjfjZc_IDJgm/view?usp=sharing) for testing.
> [fixes #1092] Draw root edge of fin tab

- core/src/net/sf/openrocket/file/openrocket/importt/FinSetPointHandler.java
- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
- core/src/net/sf/openrocket/rocketcomponent/TrapezoidFinSet.java
This PR fixes #1090 where the FinSet tab position was wrong when you opened a file.
The problem was the following: the tab position (= kinda the same as the tab offset, but just transformed to cope with the offset method, tab length etc.) was calculated using the following method, which uses the `tabOffset` and `tabLength` of the fin tab, and `length`, the length of the fin:
```Java
public void updateTabPosition() {
this.tabPosition = this.tabOffsetMethod.getAsPosition(tabOffset, tabLength, length);
}
```
Now, when loading the .ork-file and parsing the XML-contents of the FinSet, the tabOffset is read in and the `tabPosition` of the FinSet is calculated. But, the value of `tabPosition` was wrong because the `length` that `updateTabPosition()` uses was incorrect. It did not equal the …
> [fixes #1090] Wrong FinSet tab position upon file opening

- swing/src/net/sf/openrocket/gui/configdialog/TransitionConfig.java
This PR fixes an overlap of the transition 'Clipped' checkbox with the comment text area on the right
OId behavior:
New behavior:
> Fix transition 'Clipped' checkbox overlapping with comment

- swing/src/net/sf/openrocket/gui/adaptors/PresetModel.java
- swing/src/net/sf/openrocket/gui/configdialog/RocketComponentConfig.java
- swing/src/net/sf/openrocket/gui/dialogs/preset/ComponentPresetChooserDialog.java
This PR had the following changes over the preset combox/component preset window:
1. **Ok/Cancel button in component preset window replaced by a single Close button**
_(The previous function of the cancel button was just to ignore the preset selection from the preset table; kinda useless in the first place)_
2. **Preset combobox now properly listens to changes in the preset preferences**
The problem was: PresetModel, the CheckboxModel responsible of updating the preset combox, was added as a preset database listener, and removed when the RocketComponentConfig dialog was invalidated. Now, here comes the stupid part of the bug: `setComponent()` of ComponentConfigDialog calls the `pack()` method, which invalidates RocketComponentConfig just to be able to resize its window. This removed …
> [fixes #1076] Fix preset combobox not updating

- swing/build.xml
Something I should have thought of but did not: there is no reasonable way for someone compiling OR to
anticipate that a submodule is now required, and the default error message doesn't give any useful clue as to what's wrong.  This PR modifies swing/build.xml so it tests for the existence of the database, and gives instructions for including it if necessary.  The instructions it gives are:
/home/joseph/openrocket/git-mybranches/swing/build.xml:190: NOTE: 
The component database is now a submodule, and must be included into 
this project to build the .jar file. 
If you retrieved this code by cloning the openrocket repository, you 
must initialize and update the submodule.  From the command line, 
this can be accomplished with 
% git submodule init 
% git submodule update 
If you retrieved …
> Check for database submodule and give instructions for including it if not found

- core/resources/l10n/messages.properties
- core/resources/l10n/messages_nl.properties
- core/resources/l10n/messages_uk_UA.properties
- swing/src/net/sf/openrocket/gui/figure3d/photo/PhotoSettingsConfig.java
This PR fixes layout issues in the PhotoStudio settings panel, as described in #1084.
Value and unit widgets are now close together and in general, the labels on the left and corresponding value-unit widgets are closer together. This should make it visually easier to link a label to the corresponding value.
Here is a [jar file](https://drive.google.com/file/d/11455wR8cO5V4abxvwg6GH6e1EDjEODeR/view?usp=sharing) for testing.
> [fixes #1084] Fix layout PhotoStudio Settings

- swing/src/net/sf/openrocket/gui/components/DescriptionArea.java
- swing/src/net/sf/openrocket/gui/dialogs/BugReportDialog.java
- swing/src/net/sf/openrocket/gui/dialogs/LicenseDialog.java
This PR fixes some layout issues that are present in the new license dialog. It concerns changing the font to match the rest of OR, making the text pane more response when enlarging the dialog, moving the Close-button to the bottom right, centering the title label even when resizing the window and making the dialog a bit bigger by default.
Whilst working on this issue, I also noticed some weirdness in the new bug report layout. I had changed the layout to HTML in a previous PR, but this caused weirdness when one of the bug report lines contained HTML-like text. In the image below you can see e.g. stack trace line '`> at java.desktop/javax.swing.JScrollPane.<init> (JScrollPane.java:306)`' that contains the text '`<init>`'. The HTML formatter interpreted this as an HTML tag, causing this …
> Fix layout issues license dialog

- swing/src/net/sf/openrocket/gui/dialogs/AboutDialog.java
This PR fixes some small layout issues in the about dialog. It just bothered me that you couldn't rescale the window and that the font was not the same as the rest of OR on Mac. Those two issues are now fixed + I made the dialog a bit bigger.
Here is a [jar file](https://drive.google.com/file/d/1ud-aCOvR0lOmKwe424wz0yjZikY0X7HH/view?usp=sharing) for testing.
> Fix about dialog layout issues

- swing/src/net/sf/openrocket/gui/customexpression/CustomExpressionPanel.java
- swing/src/net/sf/openrocket/gui/dialogs/ComponentAnalysisDialog.java
- swing/src/net/sf/openrocket/gui/dialogs/optimization/GeneralOptimizationDialog.java
This PR fixes issue #1024 where the Rocket optimization window was too small at startup, thus clipping of the bottom of the window. While I was at it, I also saw some layout issues in the custom expression window and component analysis window (there still are numerous after this PR, but those are headaches for the future).
Rocket optimization window:
Custom expressions window:
Component analysis window:
Here is a [jar file](https://drive.google.com/file/d/1JDgxOBS2XKYja3hBk--91yNcaShL0Z_G/view?usp=sharing) for testing.
> [fixes #1024] Rocket optimization window too small + others

- swing/src/net/sf/openrocket/gui/dialogs/ComponentAnalysisDialog.java
This PR fixes #1119 by switching back the rocket's orientation after closing the component analysis window.
Here is a [jar file](https://drive.google.com/file/d/15myAqcD7KlMq22n3eX8GXJIHoSp3l0By/view?usp=sharing) for testing.
> [fixes #1119] Fix rocket rotation after component analysis

- swing/src/net/sf/openrocket/gui/main/BasicFrame.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/FlightConfigurablePanel.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/FlightConfigurationPanel.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/MotorConfigurationPanel.java
This PR adds the feature from #1101 where if you select a configuration in the motor configuration table, the corresponding motor mount also gets selected in the rocket preview to visually aid users which part of their design they're editing.
https://user-images.githubusercontent.com/11031519/153752939-38d8f7fe-0aa4-429a-a214-0b01e3a8ecb4.mov
Here is a [jar file](https://drive.google.com/file/d/1TwyoYG4tUbAD_1QJWGyqzOG3tCS2nmea/view?usp=sharing) for testing.
> [fixes #1101] Select motor mount when selecting motor configuration

- .github/workflows/build.yml
This PR modifies the github workflow to upload the compiled jar file(s) as artifacts in actions. This makes the process of testing new builds a lot easier; just link the completed action in your pull request instead of having to upload your own build somewhere. Additionally, it comes with the plus that you are not blindly trusting someone to not include something nasty in their jar file, as the action is directly connected with a publicly available commit.
> Upload built Jarfiles as Artifacts with run Actions

- swing/src/net/sf/openrocket/gui/main/BasicFrame.java
- swing/src/net/sf/openrocket/gui/main/DocumentSelectionModel.java
- swing/src/net/sf/openrocket/gui/main/componenttree/ComponentTreeModel.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/FlightConfigurablePanel.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/FlightConfigurationPanel.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/MotorConfigurationPanel.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/RecoveryConfigurationPanel.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/SeparationConfigurationPanel.java
This PR fixes #244 and adds the ability to have multi-selections in the motors, recovery and stage panels. You can perform almost every action on multiple cells: selecting a motor (selects the same motor for all selected cells), remove motor, select/reset ignition (again uniform ignition selection for all selected cells), rename configuration, remove configuration, copy configuration, select/reset deployment, and select/reset separation.
(You can do multi-selection with holding the shift-key and clicking or ctrl/command + click)
Demo:
https://user-images.githubusercontent.com/11031519/153920756-fb7369cb-98e8-4221-8d93-d44fd5d9b82a.mp4
Here is a [jar file](https://drive.google.com/file/d/14iyFTu54tBjeri9CA8ULhI3O62T__Qro/view?usp=sharing) for testing.
> [fixes #244] Multi-selection in Motors, Recovery & Stages panels

- swing/src/net/sf/openrocket/gui/dialogs/DebugLogDialog.java
This PR fixes #1130 by centering the DebugLogDialog in the center of the screen.
Here is a [jar file](https://drive.google.com/file/d/1dfHzrCmKFqP6-PgZuX3uHbislJiNOvJb/view?usp=sharing) for testing.
> [fixes #1130] Fix DebugLogDialog location

- swing/src/net/sf/openrocket/gui/configdialog/TubeFinSetConfig.java
This PR fixes #1134 where the axial offset of a tube fin set did not work and had an effect on the fin rotation instead.
Here is a [jar file](https://drive.google.com/file/d/1kBh2XPi0OjkGSA8HM78nsVOdaVdVSQhs/view?usp=sharing) for testing.
> [fixes #1134] Fix AxialOffset TubeFinSet

- core/src/net/sf/openrocket/file/openrocket/savers/RocketComponentSaver.java
> Don't need to save <radialdirection> for pod sets, since there's no backward compatibility issue with them

- swing/resources-src/datafiles/legacy_components/bms-legacy.orc
- swing/resources-src/datafiles/legacy_components/fliskits-legacy.orc
- swing/resources-src/datafiles/legacy_components/giantleaprocketry-legacy.orc
- swing/resources-src/datafiles/legacy_components/publicmissiles-legacy.orc
It turns out four manufacturers with entries in our legacy database do not appear in Daves database, namely
Balsa Machining Services
Public Missiles Ltd
Fliskits
Giant Leap Rocketry
This removes the <legacy/> tag from those four manufacturer's .orc files, so the user will see these parts whether "show legacy database" is clicked or not.  The remainder of our legacy database files are still marked as "legacy".
Long term, I'd really like to see these files compared against the current catalogs from those manufacturers and proofed versions submitted to Dave as PRs. Short term, I don't see that we need to delay the beta for it.
> Remove <legacy/> tag from four manufacturers that do not appear in Dave's database

- .gitmodules
- snap/snapcraft.yaml
The update to use dbcook's component database adds a git submodule. The
submodule configuration needs to use an https transport rather than an
ssh transport for users not logged in through git (snapcraft builds
aren't; they're in a clean room).
Additionally, the snapcraft.yaml file needs to be told the source type
is git in order to automatically udpate an pull in submodules.
> Update snapcraft builds for dbcook's db

- swing/src/net/sf/openrocket/communication/AssetHandler.java
Since the new release will use a .sh file for the Linux packager, the software updater needed to be updated for this.
> Update SoftwareUpdater to use .sh for Linux update

- core/src/net/sf/openrocket/communication/UpdateInfoRetriever.java
I realize that I should've done this before the beta release, oh well... The software updater was set up to only check of official releases (i.e. ignore github releases with the tags 'alpha' or 'beta' in it). So if you now run the update checker, it will notify that the latest official release is still 15.03. So not useful for people running the beta and will not get an automatic notification when a new beta release is available...
> Change SoftwareUpdater to by default check unofficial releases

- core/src/net/sf/openrocket/file/rocksim/importt/FinSetHandler.java
This PR fixes #1164 where the location of FinSets from a Rocksim import would be inverted for locations that were referenced from the tip of the nose cone and the top of the parent component.
Here is a [jar file](https://github.com/openrocket/openrocket/suites/5467350835/artifacts/174098659) for testing.
> [fixes #1164] Account for different RockSim FinSet location directions

- swing/src/net/sf/openrocket/gui/configdialog/RocketComponentConfig.java
This PR fixes #1190 where the Close-button in a component config dialog got cut off on some OS'es.
As stated by [Joe's comment](https://github.com/openrocket/openrocket/issues/1190#issuecomment-1054414042), the fix works + I tested it on macOS, Ubuntu and Windows 11 and they are not (negatively) affected by this PR.
> [fixes #1190] Fix ConfigDialog Close-button cut off

- core/src/net/sf/openrocket/file/openrocket/savers/RocketComponentSaver.java
Note that rockets having parallel stages saved before this PR will still show warning; save and reload should make the warning go away.
Fixes #1196
> Don't save backward-compatible radialdirection for ParallelStage

- swing/src/net/sf/openrocket/gui/dialogs/motor/MotorChooserDialog.java
- swing/src/net/sf/openrocket/gui/dialogs/motor/thrustcurve/ThrustCurveMotorSelectionPanel.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/MotorConfigurationPanel.java
- swing/src/net/sf/openrocket/gui/util/GUIUtil.java
This PR fixes #1181 and ensures that an initial table selection in the motor chooser gets translated to an actual motor selection. You should use the instructions from #1181 to recreate the issues and see if it's fixed.
Here is a [jar file](https://github.com/openrocket/openrocket/suites/5465148300/artifacts/173966704) for testing.
> [fixes #1181] Fix initial motor select in MotorChooserDialog

- core/resources/l10n/messages.properties
- core/src/net/sf/openrocket/appearance/AppearanceBuilder.java
- swing/src/net/sf/openrocket/gui/configdialog/AppearancePanel.java
This PR fixes #1078 by adding an opacity slider to the appearance config dialog:
https://user-images.githubusercontent.com/11031519/156026176-9c48d7d9-eb94-4b14-a869-e1e2eb287cae.mov
(I choose to use the term 'Opacity' instead of 'Transparency'. I know that the color picker has 'Transparency', but 'Opacity' is more common in all the programs I've worked with so far).
Here is a [jar file](https://github.com/openrocket/openrocket/suites/5477442873/artifacts/174667095) for testing.
> [fixes #1078] Add opacity slider to appearance config

- core/src/net/sf/openrocket/appearance/AppearanceBuilder.java
This PR fixes #1192 by setting the default 3D component color to a mid-grey #7F7F7F + default 30% shine.
Preview:
> [fixes #1192] Use default 3D component color mid-grey + 30% shine

- swing/src/net/sf/openrocket/gui/configdialog/AppearancePanel.java
This PR fixes #1189 where the shine slider was too small because it used a JSlider instead of BasicSlider.
Additionally, this PR also adds clamping for both the opacity and shine slider so that it is limited to 0 - 100 %.
(Extra: apparently the changes from PR #970 were not present in unstable, no clue why because normally it got merged but anyway, now it's back)
(Already tested in the #1189 thread).
> [fixes #1189] Fix Shine slider too small

- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/FlightConfigurationPanel.java
*sigh* this was a really stupid bug from PR #1132 where I forgot one line of code that selects the newly created configuration (with `rocket.setSelectedConfiguration`).
Issues #1163 and #1175 should be fixed with this.
Here is a [jar file](https://github.com/openrocket/openrocket/suites/5480818622/artifacts/174857559) for testing.
> [fixes #1163 & #1175] Fix unreliable simulation creation from new flight config

- core/src/net/sf/openrocket/database/motor/ThrustCurveMotorSetDatabase.java
- core/src/net/sf/openrocket/file/openrocket/importt/MotorHandler.java
Instead of requiring motor "designation" to match either the actual designation or the common name, require it to be a substring of the actual designation or that the common name be a substring of the actual designation.  Many motors in stored rocket files have "designations" that resemble, but do not match, actual designations and common names.
Don't match on diameter or length when loading files.  Motors with errors in the old database (eg M1850) would fail to be recognized.
Fixes #1174
> Make motor database search more robust, especially when loading files

- core/src/net/sf/openrocket/file/rocksim/importt/FinSetHandler.java
This PR fixes #1220, which was a RockSim fin import issue where the fins would get shrunk down. Thanks to @hcraigmiller for the [analysis of the problem](https://github.com/openrocket/openrocket/issues/1220#issuecomment-1059686384).
New import result:
Here is a [jar file](https://github.com/openrocket/openrocket/suites/5546831963/artifacts/178701675) for testing.
> [fixes #1220] Fix RockSim fin import issue

- swing/src/net/sf/openrocket/gui/plot/SimulationPlot.java
This PR fixes an issue with the plot tooltip text generator which previously threw an exception when there was only one data plot and it was on the right axis.
> Fix tooltip exception when 1 plot on right axis

- core/src/net/sf/openrocket/startup/Application.java
- swing/src/net/sf/openrocket/startup/SwingStartup.java
This PR fixes #1176 by adding JRE version checking at startup. If an unsupported Java version is detected, the following popup will show and the application is closed afterwards:
Currently the following Java versions are included as being supported: 11, 12 & 13 (I think these are the supported versions?)
Note: the packaged installers already have a fixed (and correct) JRE versions, e.g. 22.02.beta.01 will show JRE version 11 if you check in the Debug Report.
Here is a [jar file](https://github.com/openrocket/openrocket/suites/5482436783/artifacts/174946436) for testing. (Note: if you wanna test different JRE versions and are running on Linux or macOS, I recommend [jEnv](https://www.jenv.be/))
> [fixes #1176] Add JRE version checking at startup

- core/src/net/sf/openrocket/database/Databases.java
This PR adds a bunch of new shock cord materials. All credits go to @hcraigmiller who gathered the data.
Added materials, format: '"{ Material name }", { density (in kg/m) }':
- "Kevlar thread 138  (0.4 mm, 1/64 in)", 0.00014808
- "Kevlar thread 207  (0.5 mm, 1/64 in)", 0.00023622
- "Kevlar thread 346  (0.7 mm, 1/32 in)", 0.00047243
- "Kevlar thread 415  (0.8 mm, 1/32 in)", 0.00055117
- "Kevlar thread 800 (1.1 mm, 3/64 in)", 0.00099211
- "Kevlar 12-strand (3.2 mm, 1/8 in)", 0.00967306
- "Kevlar 12-strand (4.8 mm, 3/16 in)", 0.01785797
- "Kevlar 12-strand (6.4 mm, 1/4 in)", 0.02976328
- "Kevlar 12-strand (7.9 mm, 5/16 in)", 0.04464491
- "Kevlar 12-strand (10 mm, 3/8 in)", 0.05952655
- "Kevlar 12-strand (11 mm, 7/16 in)", 0.07440819
- "Kevlar 12-strand (13 mm, 1/2 in)", 0.11607678
- "Kevlar …
> [#1172] Add new shockcord materials

- core/src/net/sf/openrocket/aerodynamics/barrowman/SymmetricComponentCalc.java
This was some debug I put in while fixing the error in subsonic nose cone drag (#1063).  It isn't needed any more, and dumps a wad of unnecessary output in our already voluminous debug logs.
> Remove unnecessary debug from SymmetricComponentCalc

- swing/src/net/sf/openrocket/gui/configdialog/RocketComponentConfig.java
This PR fixes some layout issues in the override panel:
- Change Cd override slider to linear slider with coefficient units (so 0.01 increments)
- Move the override mass/CG for subcomponents checkbox to before the override Cd checkbox
> Fix Override Panel layout issues

- core/src/net/sf/openrocket/simulation/FlightData.java
- swing/src/net/sf/openrocket/gui/plot/PlotConfiguration.java
- swing/src/net/sf/openrocket/gui/plot/SimulationPlot.java
This PR fixes #1128, the simulation plot behavior under boosters (and multi-stage rockets)
> [fixes #1128] Fix SimulationPlot range with boosters dataset

- core/src/net/sf/openrocket/simulation/BasicEventSimulationEngine.java
If there are multiple independent motor clusters in a stage, each of them can attempt a separation event. When the second event happens, there is no longer an active upper stage, so the separation results in a simulation branch with no active stages.  This causes a NaN exception as the mass is 0.
fixes #1226
> Check for active upper stage before dropping booster

- core/src/net/sf/openrocket/rocketcomponent/StageSeparationConfiguration.java
For parallel stages, this is much more likely to be the user's intent.  The previous behavior caused stage separation the moment of ignition, so the booster set essentially flew as a second, independent rocket. With this change, the parallel stage stays with the center stack until the ejection charge fires (note that OR treats a rocket with a -0 ejection delay as having an ejection charge at motor burnout).
Note that this change to the default behavior is also applied to axial stages, but is also appropriate in that case.  For the vast majority  of low power rockets, the booster burnout ignites the next stage, so "next stage ignition" and "current stage ejection charge" are simultaneous.  For high power rockets, the next stage ignition has to be customized anyway.
Fixes #1215
> Change default stage separation from next stage ignition to current stage motor burnout.

- core/src/net/sf/openrocket/rocketcomponent/FreeformFinSet.java
Note that the lowest point on the fin is guaranteed to be either the first point which is at (0, 0) or the last point, which will have a y coordinate of 0 if on a body tube, greater than 0 if on an increasing transition, or less than 0 on a decreasing transition (boattail).
Fixes #1173 and #1243
I'm leery of using either RockSim or a nasty hack as ground truth, but the CP is in a much more reasonable place using the .ork file from the report of #1173
[V2_BT101_RS-22.zip](https://github.com/openrocket/openrocket/files/8263177/V2_BT101_RS-22.zip)
> Get correct fin span when last point in shape is lower than first point.

- core/src/net/sf/openrocket/rocketcomponent/FlightConfiguration.java
- core/src/net/sf/openrocket/rocketcomponent/InstanceContext.java
- core/src/net/sf/openrocket/rocketcomponent/InstanceMap.java
- core/src/net/sf/openrocket/util/TestRockets.java
- swing/src/net/sf/openrocket/gui/figure3d/RocketRenderer.java
- swing/src/net/sf/openrocket/gui/figure3d/geometry/Geometry.java
- swing/src/net/sf/openrocket/gui/scalefigure/RocketFigure.java
When processing the component tree to find active instances of components, it wasn't processing subtrees of inactive components.  The result was that in finding the drag for detached boosters, the drag was calculated as 0.
Notice that if you run the .ork that resulted in filing the issue after this applying this fix, you get a truly bizarre simulation result -- that's actually what we'd expect, since the boosters are separating at launch and have no fins so they're unstable. The attached ork is the same as that one, but uses A8-0's in the boosters and separates at motor ejection charge.
[Pod-Boosters-2.ork.txt](https://github.com/openrocket/openrocket/files/8234582/Pod-Boosters-2.ork.txt)
> Process entire part tree when finding active contexts

- core/resources/l10n/messages.properties
- swing/src/net/sf/openrocket/gui/plot/SimulationPlotDialog.java
- swing/src/net/sf/openrocket/gui/util/FileHelper.java
The button for this is placed next to the zoom button at the bottom of the Simulation Graph/Chart Page.
_How I Did It:_ I simply reused some of the zoom button code to make a button, created a basic method employing JFileChooser so the user can pick where they want the image saved, and lastly used the JFreeChart -> ChartUtilities -> saveChartAsPNG method to export the chart as a PNG.
_Background:_ I was using this software for a project and was curious if this feature existed. I went to website and found that it was still on the Planned feature list but never seemed to be implemented, even in the 22.02 beta. I had a bit of spare time and decided that I would add the feature myself.
[**Link To Jar File For Testing (Hosted On OneDrive)**](https://1drv.ms/u/s!AmD6PPALFydSl3FVxPjJZaDnhNue) …
> Adds Ability To Export Simulation Graph/Chart As PNG

- swing/src/net/sf/openrocket/gui/plot/SimulationPlotDialog.java
This PR fixes #1254: stretching of simulation plot elements when resizing the window (or when the window was too large to begin with). The elements stretched because the panel dimensions were greater than the chartPanel maximum draw dimensions.
New behavior:
Here is a [jar file](https://github.com/openrocket/openrocket/suites/5747525932/artifacts/190744045) for testing.
> [fixes #1254] Fix simulation plot element stretching

- core/src/net/sf/openrocket/startup/Application.java
Let's allow OR to run with either 11 or 17, so we can see whether we can migrate it.
> Allow execution with Java 17

- core/src/net/sf/openrocket/aerodynamics/AerodynamicForces.java
- core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java
- core/src/net/sf/openrocket/aerodynamics/barrowman/FinSetCalc.java
- core/src/net/sf/openrocket/aerodynamics/barrowman/LaunchLugCalc.java
- core/src/net/sf/openrocket/aerodynamics/barrowman/RocketComponentCalc.java
- core/src/net/sf/openrocket/aerodynamics/barrowman/SymmetricComponentCalc.java
- core/src/net/sf/openrocket/aerodynamics/barrowman/TubeFinSetCalc.java
- core/src/net/sf/openrocket/simulation/RK4SimulationStepper.java
- core/test/net/sf/openrocket/aerodynamics/SymmetricComponentCalcTest.java
This PR makes no semantic changes.
The aerodynamics code is currently inconsistent, referring to the coefficient of drag as CD in some places, C when in variables referring to the CD in the axial direction, Drag in others, and even DragForce in at least one.  This changes the code to consistently refer to drag coefficient as CD, clarifying the code.
The two unit test failures are from the script engine issue (#1108 and others)
> Refer to drag coefficient consistently as CD

- core/src/net/sf/openrocket/aerodynamics/AerodynamicForces.java
- core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java
- core/src/net/sf/openrocket/aerodynamics/barrowman/FinSetCalc.java
- core/src/net/sf/openrocket/aerodynamics/barrowman/LaunchLugCalc.java
- core/src/net/sf/openrocket/aerodynamics/barrowman/RocketComponentCalc.java
- core/src/net/sf/openrocket/aerodynamics/barrowman/SymmetricComponentCalc.java
- core/src/net/sf/openrocket/aerodynamics/barrowman/TubeFinSetCalc.java
- core/src/net/sf/openrocket/simulation/RK4SimulationStepper.java
- core/test/net/sf/openrocket/aerodynamics/SymmetricComponentCalcTest.java
Reverts openrocket/openrocket#1273
ant unittest may put test reports in two places:  .../swing/tmp/test-reports/index.html or .../core/tmp/test-reports/index.html.  If it puts any under ...core you don't get an indication that there may also be one under .../swing.  It turns out that in addition to the unit test failures from scripting, there was also a unit test failure in simulation.  This reverts this PR so I can look into it some more and resubmit.
> Revert "Refer to drag coefficient consistently as CD"

- swing/src/net/sf/openrocket/gui/print/FinMarkingGuide.java
Creates a guide if and only if a fin set or tube fin set exists. Allows for multiple fin and/or tube fin sets and multiple launch lugs and/or rail buttons. But, not without overlaping labels when dissimilar components and/or similar components with dissimilar names have the same rotation.
> Adds tube fin sets to fin marking guide.

- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
- swing/src/net/sf/openrocket/gui/configdialog/FinSetConfig.java
If a set of fins has an overridden mass, then, if the set is split into individual fins, the overridden mass is divided by the number of fins in the set and the quotient is set as the mass override for each individual fin.
> [Fixes Issue #1292]  Calculates per fin mass when splitting a set of fins with a mass override

- README.md
Under the contributing section of the README, the link at "read the practicalities of contributing here" links to .github/CONTRIBUTING.md, however a recent commit moved that file out of the github folder so now that link is invalid.
This PR fixes that link.
> Fix the invalid link to CONTRIBUTING.MD in the README

- core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java
- core/src/net/sf/openrocket/aerodynamics/barrowman/FinSetCalc.java
- core/src/net/sf/openrocket/aerodynamics/barrowman/LaunchLugCalc.java
- core/src/net/sf/openrocket/aerodynamics/barrowman/RocketComponentCalc.java
- core/src/net/sf/openrocket/aerodynamics/barrowman/SymmetricComponentCalc.java
- core/src/net/sf/openrocket/aerodynamics/barrowman/TubeFinSetCalc.java
Clean up code for BarrowmanCalculator::calculateFrictionCD() and move code for computing friction CD to the appropriate subclasses of RocketComponentCalc.
Two unit test failures are from scripting issues
Simulation results for a tube fin rocket match the (wildly inaccurate) results from before this PR:
|Motor|Old|New|Flight Data|
|--------|----|------|--------------|
|C6|2549|2549|695.5|
|B6|734|734|352|
|A8|211|211|N/A|
> Refactor friction drag

- swing/src/net/sf/openrocket/database/MotorDatabaseLoader.java
This PR fixes #1304 where the thrust curve error dialog was not accessible due to the loading motor dialog's modality. Additionally the full file path of the erroneous thrustcurve is now shown instead of only the thrustcurve name
> fixes #1304 Improve thrust curve import dialog

- core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java
- core/src/net/sf/openrocket/aerodynamics/barrowman/TubeCalc.java
Left a really annoying extra line of debug in BarromanCalcualtor.
Somehow managed to have two offseting (in the case of this rocket, anyway) typos in pressure drop calculation.
> Two little cleanups in tube fin stuff.

- swing/src/net/sf/openrocket/gui/dialogs/ComponentAnalysisDialog.java
Fixes #1302 (Splitting FinSet causes null pointer exception closing component analysis dialog)
The problem was more general than that: the component analysis dialog simply wasn't listening to changes in the rocket. Adding the listener fixes the null pointer exception, and also makes the analysis "keep up" with changes in configuration dialogs.
> Add listener for changes to rocket to component analysis dialog

- core/src/net/sf/openrocket/material/Material.java
- swing/src/net/sf/openrocket/gui/dialogs/CustomMaterialDialog.java
In the preference's material tab, when adding a new material there was an option to select 'Custom' as material type, which just makes no sense from a user's standpoint. It is used internally in the codebase for a bunch of stuff, but should not be included in the dropdown box. This PR removes the Custom material type from the dropdown box and thus fixes #1320.
Unit test failures due to the scripting bug.
> [fixes #1320] Remove 'Custom' material option from preference's add new material

- core/src/net/sf/openrocket/rocketcomponent/RocketComponent.java
Fixes #1291 (I think)
The more I think about it, the more I think the resolution of the actual bug report is "works as intended".  If you're looking at one fin, you should get one fin's mass in the tooltip.
On the other hand, the report alerted me to the fact that when hovering over the podset that is the finset's parent, it doesn't reflect the number of pods.  Just as a finset's mass should reflect the number of fins, a podset's mass should reflect the number of pods.
So this PR ends up not changing the mass reported for a finset or other component that is a child of a podset (still only one fin, in this case), but does change the reported mass of the parent podset.
So whether this fully or only partially fixes the issue depends on whether people agree with me on the correct behavior.
> consider instance count in component mass

- swing/src/net/sf/openrocket/gui/configdialog/AppearancePanel.java
This PR fixes #1326 and updates the opacity slider whenever an alpha change is made in the appearance color button panel.
> [fixes #1326] Update opacity slider with color button alpha change

- swing/resources-src/datafiles/legacy_components/Fruity_Chutes_Enhanced.orc
- swing/resources-src/datafiles/legacy_components/Rocketman.orc
Corrects FruityChutes packed length and diameter units omission in entire parachute line; as well as Rocketman single decimal point placement error.
> CRITICAL pre-beta ORC corrections

- core/resources/l10n/messages.properties
- core/src/net/sf/openrocket/preset/ComponentPreset.java
- swing/src/net/sf/openrocket/gui/preset/PresetEditorDialog.java
Adds packed length and diameter to preset editor; also adds labels and additional presets for .orc files so that spill hole data can be added to the .orc files without throwing warnings (does not change editor for spill holes).
> Adds additional presets for use in .orc files without throwing errors

- swing/src/net/sf/openrocket/gui/configdialog/RocketComponentConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/ShockCordConfig.java
This PR fixes #1141 where there was an overlap issue of the packed length of the shock cord config on macOS.
@hcraigmiller @JoePfeiffer could you verify that nothing got messed up on the Windows and Linux layout?
Here is a [jar file](https://github.com/openrocket/openrocket/suites/6611911386/artifacts/248779396) for testing.
> [Fixes #1141] Fix packed length overlap

- swing/src/net/sf/openrocket/gui/dialogs/flightconfiguration/MotorMountConfigurationPanel.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/FlightConfigurationPanel.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/MotorConfigurationPanel.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/RecoveryConfigurationPanel.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/SeparationConfigurationPanel.java
This PR fixes #1285 by improving the scalability of the Motors & Configurations tab UI.
Demo:
https://user-images.githubusercontent.com/11031519/169719394-1603079e-019c-4b32-8b98-bcd15c8e4fd4.mov
Again, @hcraigmiller and @JoePfeiffer  could you verify a correct working on Windows/Linux?
Here is a [jar file](https://github.com/openrocket/openrocket/suites/6612001183/artifacts/248785892) for testing.
> [#1285] Improve Motors & Configurations UI scalability

- core/src/net/sf/openrocket/rocketcomponent/Streamer.java
Changing a streamer characteristic exits preset status; except for streamer length. Selection of a preset streamer when not in preset status (such as re-selecting the same preset streamer after changing one of its characteristics), sets all characteristics (including Cd and automatic checkbox); previously, the Cd and automatic checkbox were not set/reset after a manual Cd change.
Here's a [jar file](https://www.dropbox.com/s/4du4zi5nzyz6qlw/OpenRocket_PR1376.jar?dl=0) for testing.
I believe that this PR and PR #1371 will complete Issue #1344 except for centering ring and bulkhead length.
> Streamer changes exit preset status

- core/src/net/sf/openrocket/rocketcomponent/Parachute.java
- core/src/net/sf/openrocket/rocketcomponent/RecoveryDevice.java
Corrected drag coefficient return from “DEFAULT_CD” to cd.” Condensed code related to setting parachute preset values. Added code to set parachute characteristics to default values when a particular characteristic data field either does not exist, is empty, or (when numerical) has a value that is not greater than zero.
Here's a [jar file](https://www.dropbox.com/s/ajxks4e430eh44j/OpenRocket.1371.jar?dl=0) for testing 
Added removal of preset status upon changes to parachute Cd, line length, and line material (jar file updated).
> Improve parachute preset code/gui

- swing/src/net/sf/openrocket/gui/dialogs/preferences/SimulationPreferencesPanel.java
This PR fixes #1278 by updating the simulation preferences UI after resetting the simulation options back to default. The simulation options did reset before this PR, but the UI simply didn't change with it.
> [#1278] Update simulation preferences UI after reset to default

- core/src/net/sf/openrocket/preset/xml/ParachuteDTO.java
Corrected error in preset which used packed length instead of the drag coefficient, and renamed/refactored variable "DragCoefficient" to "dragCoefficient".
> Corrected Parachute CD preset error

- core/src/net/sf/openrocket/rocketcomponent/RingComponent.java
This PR fixes #1344 by clearing the preset of the centering ring and bulkhead when the length (thickness) changes.
> [#1344] Clear preset when centering ring/bulkhead length is changed

- swing/src/net/sf/openrocket/gui/main/SimulationPanel.java
This PR solves #1286 where the sim buttons frequently did not update (i.e. remain disabled) when you quickly opened the simulation tab. Steps to reproduce: open 'A simple model rocket', quickly click on the 'Flight simulations' tab and quickly select any one of the simulations. The 'Edit simulation', 'Run simulations', 'Delete simulations' and 'Plot / Export' would frequently remain disabled.
This PR just implements a row selection listener in the sim table instead of the mouse click listener, which seems to solve the issue.
> [#1286] Use table row selection listener to update sim button state

- core/resources/l10n/messages.properties
- swing/src/net/sf/openrocket/gui/components/StageSelector.java
- swing/src/net/sf/openrocket/gui/configdialog/FreeformFinSetConfig.java
- swing/src/net/sf/openrocket/gui/figure3d/RocketFigure3d.java
- swing/src/net/sf/openrocket/gui/scalefigure/RocketFigure.java
- swing/src/net/sf/openrocket/gui/scalefigure/RocketPanel.java
- swing/src/net/sf/openrocket/gui/scalefigure/ScaleSelector.java
This PR fixes #898 and #1168 by rearranging the rocket view ribbon to be better suited for smaller windows + it adds a checkbox to hide the CG/CP markings in the rocket view. I also added a tooltip text for the rotation slider on the left, since I found it very confusing when I first opened OR what that slider actually did.
Demo:
https://user-images.githubusercontent.com/11031519/170521933-8dddacc5-478f-4f63-b725-0e797a8dabd9.mov
Here is a [jar file](https://github.com/openrocket/openrocket/suites/6673568362/artifacts/252777629) for testing.
> [fixes #898 & #1168] Improve rocket view ribbon for smaller windows + add CG/CP show/hide checkbox

- core/src/net/sf/openrocket/rocketcomponent/Streamer.java
Don't ask me why, but in the streamer the setLength method (which changes the packed length) was overridden to change the strip width. This PR fixes #1397.
> [#1397] Fix streamer packed length updating strip width

- swing/src/net/sf/openrocket/gui/plot/SimulationPlotDialog.java
This PR moves the series selection in the sim pot more to the beginning. Because of the export image button, it looked like the combobox was tied to exporting the image instead of the plot.
> Move series selection in sim plot to the beginning

- swing/src/net/sf/openrocket/gui/widgets/SelectColorButton.java
- swing/src/net/sf/openrocket/gui/widgets/SelectColorToggleButton.java
This PR fixes #1099, where the ToggleButtons on macOS had a grey background instead of blue. (note when pressing down on a JButton, the background is still grey, don't know how to solve that issue, but at least let us enjoy for a moment that the fix works for JToggleButtons)
> [#1099] Fix button grey out on macOS

- swing/src/net/sf/openrocket/gui/simulation/SimulationEditDialog.java
This PR solves an issue where simulations with loaded simulation data from the design file (e.g. the 'A simple model rocket' example) would re-run the simulations when you tried to plot them.
> Fix loaded simulations re-running when plotting

- core/src/net/sf/openrocket/rocketcomponent/RocketComponent.java
- swing/src/net/sf/openrocket/gui/simulation/SimulationEditDialog.java
This PR fixes #1409 by removing the instancecount multiplication in getSectionMass. The getComponentMass already takes instancecounts into account.
> [fixes #1409] Remove instancecount multiplication in getSectionMass

- core/src/net/sf/openrocket/rocketcomponent/RocketComponent.java
- swing/src/net/sf/openrocket/gui/main/RocketActions.java
- swing/src/net/sf/openrocket/gui/main/componenttree/ComponentTreeRenderer.java
- swing/src/net/sf/openrocket/gui/main/componenttree/ComponentTreeTransferHandler.java
Fixes #1411. I’ve made it so that the name just displays ‘Components <mass>’, with all the names of the selected components as a description (second line) in the hover box. If the component selection contains a component with children, it will also give the total mass of that parent component, just as is now the case if you hover over the body tube in ‘A simple model rocket’. For instance if you select the nose cone and body tube in ‘A simple model rocket’, it will display ‘Components (28.5 g of 48.1 g total)’. If no parent components are present, it just shows ‘Components (28.5 g)’. Another special case is if you select a stage or rocket (together with other components). In that case it just shows ‘Components (<total rocket mass>)’, but with the sustainer and all other components …
> [#1411] Show combined mass of multi-selection hover in component

- core/resources/l10n/messages.properties
- core/src/net/sf/openrocket/aerodynamics/Warning.java
- core/src/net/sf/openrocket/aerodynamics/barrowman/TubeFinSetCalc.java
Finally got back to this.
This PR changes the tube fin stability calculations to use calculated stability of tube fins instead of the "three fin hack" previously in use.  It completes the rewrite of tubeFinCalc.java.
The stability calculated with this code is close, but not identical, to that using the code from 15.03.  In the case of the tube fin example rocket, the CP location in centimeters from the nose of the rocket is:
<table>
<tr><th></th><th>15.03</th><th>new</th></tr>
<tr><td>Mach 0.1</td><td>54.1</td><td>53.4</td></tr>
<tr><td>Mach 0.9</td><td>54.5</td><td>52.3</td></tr>
</table>
My expectation is that the new code is more accurate, but we won't really know until we can find a wind tunnel.
A bit of background:  originally, neither RockSim nor OpenRocket was able to simulate tube …
> Update tube fin stabililty calculations

- swing/src/net/sf/openrocket/gui/simulation/SimulationEditDialog.java
This PR fixes #1426 by revalidating the plotExportPanel after the 'OK' button changes in the export window.
Demo:
https://user-images.githubusercontent.com/11031519/173188535-1aeca469-a9b1-4a8d-97d2-791f451d8196.mov
> [Fixes #1426] Revalidate plotExportPanel after button change

- core/resources/l10n/messages.properties
- core/src/net/sf/openrocket/rocketcomponent/FlightConfiguration.java
- core/src/net/sf/openrocket/rocketcomponent/ParallelStage.java
- core/src/net/sf/openrocket/rocketcomponent/PodSet.java
- core/src/net/sf/openrocket/rocketcomponent/position/RadiusMethod.java
- core/test/net/sf/openrocket/rocketcomponent/ParallelStageTest.java
- swing/src/net/sf/openrocket/gui/adaptors/DoubleModel.java
- swing/src/net/sf/openrocket/gui/configdialog/ComponentAssemblyConfig.java
This PR fixes #1422 by adding sliders to the config dialog:
I also changed the labels to make it more consistent with the rest of the program, as can be seen on the previous screenshots.
While working on this issue, I also notices that the radius offset was unresponsive to changes to the radius method (or well, it just reacted in a faulty way), which this PR also fixes:
Previous behavior:
https://user-images.githubusercontent.com/11031519/173162266-0a223a0b-2076-40b5-82e1-f1988932a820.mov
New behavior:
https://user-images.githubusercontent.com/11031519/173162332-981196d8-9b1d-485d-82fe-baec43e25032.mov
All the mentioned behaviors work both for pod sets and boosters.
Here is a [jar file](https://github.com/openrocket/openrocket/suites/6887416517/artifacts/266800683) for testing.
> [Fixes #1422] Add sliders to pods/booster config + fix radius offset not updating with radius method

- swing/src/net/sf/openrocket/gui/scalefigure/ScaleSelector.java
This PR fixes #1423 by giving the zoom combobox an initial size so that it can fit the text 'Fit (100.0%)' (thus all text in the form of 'Fit (xxx.x%)'.
I tried making the combobox size dynamically based on its content, but was unsuccessful.
> [#1423] Make sure zoom combobox can fit 'Fit (100.0%)'

- swing/src/net/sf/openrocket/gui/scalefigure/RocketPanel.java
This PR fixes #753 where the rocket view did not resize when the rocket became shorter. The ScaleScrollPane componentResized just gets triggered whenever the rocket changes (may be not very efficient when parts of the rocket change that do not affect the rocket compound size, but shouldn't be too bad, there is a check somewhere deep that checks whether the bounds actually changed before updating the rocket view).
New behavior:
https://user-images.githubusercontent.com/11031519/173206868-33f05ccc-1a33-4594-83ea-103529209090.mov
Here is a [jar file](https://github.com/openrocket/openrocket/suites/6893520699/artifacts/267268666) for testing.
> [Fixes #753] Update ScaleScrollPane size when rocket changes

- install4j/22.xx/openrocket-22.xx.install4j
- swing/src/net/sf/openrocket/startup/OSXSetup.java
The major change is it turns out you need to do the file installation before trying to create the integrations.
Installers to test in https://drive.google.com/drive/folders/1xaUZXnl9q6CDG-CbkqIQqpFrBz63Gw2k?usp=sharing
Fixes #1135
> Revised installer configuration to enable desktop icon and file associations

- core/src/net/sf/openrocket/util/TextUtil.java
- core/test/net/sf/openrocket/util/TextUtilTest.java
- swing/src/net/sf/openrocket/gui/components/CsvOptionPanel.java
- swing/src/net/sf/openrocket/gui/util/SaveCSVWorker.java
The previous code was just a bit odd and non-standard + variable (and probably inefficient). Decided to replace it with standard Java functions instead (+ some other custom formatting methods). This may also improve the [inefficiency noted by @Sparrowhawk120](https://github.com/openrocket/openrocket/pull/1427#issuecomment-1153324209).
What changed concretely:
- When no exponential notation is needed, this PR changes nothing, you still get the same results, albeith written more efficiently (hopefully)
- When exponential notation is needed, the outcome will be exponential if the value is < 0.001 or ≥ 10000. The previous code was quite variable in this, sometimes switching between decimal notation and exponential based on the length of the result or some other factors. I prefer going for …
> Improve double to string rounding code

- swing/src/net/sf/openrocket/startup/OSXSetup.java
- swing/src/net/sf/openrocket/startup/SwingStartup.java
This PR fixes a small bug in the maOS file association that when you tried to open a design file when OR was not yet running, that upon startup you got a RuntimeException error because BasicFrame was not yet loaded. Moving the OpenFileHandler inside the invokeAndWait fixes the issue.
> Initialize OSX OpenFileHandler in invokeAndWait

- swing/src/net/sf/openrocket/gui/main/BasicFrame.java
- swing/src/net/sf/openrocket/startup/OSXSetup.java
- swing/src/net/sf/openrocket/startup/SwingStartup.java
One final PR to fix an issue in the macOS file association. This PR ensures that a design file opened by the macOS file association replaces an already open (replaceable) design file.
> Use last BasicFrame as parent in macOS OpenFileHandler

- swing/src/net/sf/openrocket/gui/main/BasicFrame.java
- swing/src/net/sf/openrocket/gui/util/DummyFrameMenuOSX.java
- swing/src/net/sf/openrocket/startup/OSXSetup.java
- swing/src/net/sf/openrocket/startup/SwingStartup.java
This PR fixes #1100 by making OR go into idle mode when all the design windows are closed, instead of quitting the application. In idle mode, an alternative menubar is present (that does not contain the edit tab etc.).
Demo:
https://user-images.githubusercontent.com/11031519/174087249-536fd7f6-b924-4899-b953-7e36d16ac627.mp4
Small sidenote: it seems like even in idle mode OR still uses a significant amount or memory, but that's just due to the horrible memory management of OR in general...
> [fixes #1100] Implement macOS idle application mode after all windows are closed

- core/src/net/sf/openrocket/appearance/AppearanceBuilder.java
- core/src/net/sf/openrocket/rocketcomponent/BodyTube.java
- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
- core/src/net/sf/openrocket/rocketcomponent/InsideColorComponent.java
- core/src/net/sf/openrocket/rocketcomponent/LaunchLug.java
- core/src/net/sf/openrocket/rocketcomponent/NoseCone.java
- core/src/net/sf/openrocket/rocketcomponent/RocketComponent.java
- core/src/net/sf/openrocket/rocketcomponent/Transition.java
- core/src/net/sf/openrocket/rocketcomponent/TubeFinSet.java
- swing/src/net/sf/openrocket/gui/main/BasicFrame.java
- swing/src/net/sf/openrocket/gui/main/RocketActions.java
This PR fixes #1454. The problem was that when cloning a RocketComponent, the InsideColorComponentHandler of the new component wasn't cloned as well, causing the program to go in an endless loop when editing the inside color, because the component's listener also had the same InsideColorComponentHandler. Additionally, the configListeners should not be cloned from the previous component, as that would also lead to a stackoverlow error.
> [#1454] Fix stackoverflow error

- swing/src/net/sf/openrocket/gui/scalefigure/RocketFigure.java
This PR fixes #1465 by including the rocket's xmin position into its sideview origin calculation. For normal rockets, xmin should equal 0, thus nothing should have changed for them. For rockets where some of its child components reach further to the left than their parent component, xmin becomes smaller than zero, which should then also be included in the origin calculation. The design file from #1465 was an example of the child components reaching further to the left. A body tube contained a pod set that was positioned to the left of its parent body tube. Another way of recreating the issue from #1465 is by opening 'A simple model rocket' and moving the launch lug all the way to the left.
> [#1465] Include xmin in sideview canvas origin calculation

- swing/src/net/sf/openrocket/gui/scalefigure/RocketPanel.java
This PR removes some redundant calls to updating the rocket view, thus improving performance very slightly.
It changes 2 instances where both the 2D view and 3D view are updated to only updating the view that is currently active. + it doesn't update the view when the simulation of the current flight configuration has changed (instead of updating the figure for all simulations).
> Remove redundant updatefigure/repaint calls

- swing/src/net/sf/openrocket/gui/dialogs/ComponentAnalysisDialog.java
This PR somewhat fixes PR #1441 by increasing the component analysis drag characteristics precision to 3 decimals instead of the previous 2 decimals.
> [#1441] Increase component analysis drag characteristics precision to 3 decimals

- swing/src/net/sf/openrocket/gui/configdialog/AppearancePanel.java
- swing/src/net/sf/openrocket/gui/configdialog/AxialStageConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/BodyTubeConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/BulkheadConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/CenteringRingConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/ComponentAssemblyConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/ComponentConfigDialog.java
- swing/src/net/sf/openrocket/gui/configdialog/EllipticalFinSetConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/FinSetConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/FreeformFinSetConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/InnerTubeConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/LaunchLugConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/MassComponentConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/NoseConeConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/ParachuteConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/RailButtonConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/RecoveryDeviceConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/RingComponentConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/RocketComponentConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/RocketConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/ShockCordConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/SleeveConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/StreamerConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/ThicknessRingComponentConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/TransitionConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/TrapezoidFinSetConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/TubeFinSetConfig.java
This PR fixes #1458 by resizing the component config dialog after changing the inside/outside appearance checkbox.
Demo:
https://user-images.githubusercontent.com/11031519/175384277-221fe612-ab76-4bdd-92dd-7260650a9b84.mov
> [#1458] Pack component config dialog after inside/outside checkbox change

- swing/src/net/sf/openrocket/gui/main/BasicFrame.java
This PR fixes #1491 by keeping track of whether the quit action was already called. The problem was that the Cmd+Q shortcut on Mac first triggered the quit action from the application menu (File > Quit), but then also triggered the OSX QuitHandler from `OSXSetup.java`.
> [#1491] Fix double 'Design not saved' dialog on macOS Cmd+Q quit

- swing/src/net/sf/openrocket/gui/main/BasicFrame.java
- swing/src/net/sf/openrocket/gui/scalefigure/RocketPanel.java
This PR fixes #1489 by visually selecting all children of a selected rocket, stage/booster or podset. It only visually selects the components, meaning that if you click the edit button, only the stage/rocket/podset will be edited, not the children (because only the stage/rocket/podset is selected in the componenttree). Right-clicking in the design view will also visually deselect all the components and then (single-component) select the component that is right-clicked upon.
Again, a lot of words, here's a demo:
https://user-images.githubusercontent.com/11031519/175839367-3a5a42dd-982f-4b41-afa9-c8c76fb4de94.mp4
Also works in the 3D view: 
https://user-images.githubusercontent.com/11031519/175839502-8664f74d-19dd-4533-9345-315139b759fe.mp4
> [#1489] Visually select child components of selected rocket/stage/podset

- core/resources/l10n/messages.properties
- swing/src/net/sf/openrocket/gui/dialogs/preferences/LaunchPreferencesPanel.java
This PR fixes #1487.
I changed the wording at the end a bit since there are multiple ways to edit a simulation (contextual menu, File > Edit, Ctrl/Cmd + E).
> [#1497] Add warning to launch preferences

- swing/src/net/sf/openrocket/gui/components/ConfigurationComboBox.java
- swing/src/net/sf/openrocket/gui/simulation/SimulationEditDialog.java
This PR fixes #1510 by not updating the rocket's selected flight configuration when changing the flight configuration in a simulation's edit dialog.
> [#1510] Don't update flight configuration from simulation edit

- swing/src/net/sf/openrocket/gui/main/BasicFrame.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/RecoveryConfigurationPanel.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/SeparationConfigurationPanel.java
This PR fixes #1490 and selects the recovery device/stage in the design view corresponding to the selected recovery device/stage in the recovery/stage configuration table.
Demo:
https://user-images.githubusercontent.com/11031519/176032271-54db5047-31dd-43cf-aced-6637013454bd.mov
This PR also fixes o an issue with #1494 where selecting multiple stages had no effect on the design view.
> [#1490] Select recovery device/stage after config panel select

- core/src/net/sf/openrocket/document/Simulation.java
During work on [Issue 1507](https://github.com/openrocket/openrocket/pull/1507), noticed that the simulation construction was using a deprecated newInstance method.  Per the comments on the method, moved it to using the defaultConstructor's newInstance method.
> Refactor to remove deprecation warning for newInstance

- swing/src/net/sf/openrocket/gui/configdialog/ComponentConfigDialog.java
- swing/src/net/sf/openrocket/gui/main/ComponentAddButtons.java
This PR fixes #1513 by combining the 'Add new component' and the 'Modify component' of that newly added component into a single 'Add new component' undo action. So if you now add a new component, and modify that new component in the edit dialog that popped up when the new component was added, you do not have perform two undo actions to undo adding that new component. (I also wanted this PR up because it will ease the development for issue #960).
Demo (includes first the prior behavior in OR 22.02.beta.04 and then the new behavior from this PR):
https://user-images.githubusercontent.com/11031519/177221365-c8e581c7-5195-4176-8118-fc51cdee1923.mp4
> [#1513] Combine 'Add component' and 'Modify new component' undo action

- core/src/net/sf/openrocket/rocketcomponent/Rocket.java
- core/src/net/sf/openrocket/rocketcomponent/RocketComponent.java
- swing/src/net/sf/openrocket/gui/figure3d/photo/PhotoFrame.java
- swing/src/net/sf/openrocket/gui/figure3d/photo/PhotoSettings.java
- swing/src/net/sf/openrocket/gui/figure3d/photo/PhotoSettingsConfig.java
This PR fixes #1524 by adding sliders to PhotoStudio.
I also noticed that the smoke opacity spinner had no effect on the smoke's opacity, which is fixed in this PR.
I also changed the default spark concentration to 20% instead of 0, so that when you enable sparks, you immediately see the sparks (instead of first having to change the concentration value to something non-zero).
In addition to adding sliders, I also added units for some parameters, such as a percentage unit for the smoke opacity.
Demo:
https://user-images.githubusercontent.com/11031519/178478007-c9e542b6-777c-4c0d-90c0-46636ef18436.mp4
> [#1524] Add sliders to PhotoStudio

- core/src/net/sf/openrocket/rocketcomponent/Rocket.java
- swing/src/net/sf/openrocket/gui/figureelements/RocketInfo.java
- swing/test/net/sf/openrocket/IntegrationTest.java
This PR fixes #1487 by updating the selected configuration of a rocket in the loadFrom method (called after an undo action). There was then still an issue that when updating the figures, a NullPointerException was thrown because RocketInfo still used an old configuration, which is solved by updating stabilityUnits in RocketInfo when the configuration is changed.
> [#1487] Fix configuration referencing after loadFrom rocket

- swing/build.xml
The build file still used the old directory name.
> Change generate-orc-files build directory

- core/test/net/sf/openrocket/simulation/DisableStageTest.java
Because simulations are not exact, the sim results can vary, which causes unittests to fail sporadically. So increase the error margin...
> Update unit tests

- core/src/net/sf/openrocket/startup/Preferences.java
- swing/src/net/sf/openrocket/gui/dialogs/preset/ComponentPresetChooserDialog.java
This PR solves #1480 in which it was requested to automatically check the "Match fore diameter" and "Match aft diameter" options in the component preset chooser window. This was done by adding a line for each option which selects the JCheckbox after checking if the option is applicable but before adding the checkbox to the pane.
> [#1480] Pre-check diameter filters in component preset chooser

- snap/snapcraft.yaml
The grade of the snap is marked as devel, which is great while the
app is being developed but means that the snap is not eligible to be
published to candidate or stable release channels. This change marks
the snap grade as stable to allow it to be released.
Additionally, the automatic snap publishing that happens for each
commit pushed to the unstable branch has been failing to release
the snap revisions due to a symlink introduced in the openjdk package
for which leaves a dangling symlink certs. The blacklisted.certs
should be now contained in blocked.certs so we add that to the list
of files to remove when being primed (final preparation for snap
packaging).
Fixes #1384
> Mark the snap grade as stable

- swing/src/net/sf/openrocket/gui/main/BasicFrame.java
- swing/src/net/sf/openrocket/gui/main/RocketActions.java
- swing/src/net/sf/openrocket/gui/main/SimulationPanel.java
- swing/src/net/sf/openrocket/gui/main/componenttree/ComponentTree.java
This PR fixes #1549 and allows all elements of the simulation table to be selected with the ctrl/cmd + A command. The same shortcut also works in the component tree, where all components are selected, except for the rocket.
I also noticed a bug in the simulation table where if you select e.g. row 1, then row 2, the plot button was disabled, as should be, but if you would then deselect row 1, then the button's status did not re-enable. This is fixed now in this PR. I also disabled the 'Edit simulation' when multiple simulations are selected. The 'plot' and 'edit' context menu items are now also disabled when multiple simulations are selected.
While working on the previous bug, I also noticed that the 'Edit', 'Delete' and 'Duplicate' button in the home screen (next to the component tree) …
> [#1549] Ctrl/Cmd + A select all shortcut in simulation table and component tree

- core/resources/l10n/messages.properties
- core/src/net/sf/openrocket/file/openrocket/importt/DocumentConfig.java
- core/src/net/sf/openrocket/file/openrocket/savers/RailButtonSaver.java
- core/src/net/sf/openrocket/rocketcomponent/LaunchLug.java
- core/src/net/sf/openrocket/rocketcomponent/RailButton.java
- swing/src/net/sf/openrocket/gui/configdialog/RailButtonConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/RocketComponentConfig.java
- swing/src/net/sf/openrocket/gui/figure3d/geometry/ComponentRenderer.java
- swing/src/net/sf/openrocket/gui/rocketfigure/RailButtonShapes.java
This PR fixes #1537 by adding the following configuration parameters for a rail button:
- Inner diameter (controls the diameter of the middle part of the rail button)
- Base height (controls the height of the cylinder closest to its parent component)
- Flange height (controls the height of the cylinder furthest away from its parent component)
Demo:
https://user-images.githubusercontent.com/11031519/179631165-a1f6ed63-e0ae-4549-bb4c-79dcbbdc168c.mp4
> [#1537] Add additional configuration parameters for rail buttons

- core/src/net/sf/openrocket/simulation/GroundStepper.java
This addresses the bug @hcraigmiller found while investigating issue #1569 , where simulating a rocket that never cleared the launch rod would go into an infinite loop that would continue until the user killed the simulation.  More generally, it turns out that if there were events in the event queue after ground hit time, the ground stepper would never advance the simulation time to the next event.  This PR modifies the ground stepper to do that.
Design demonstrating the issue and solution:  
[underpowered.zip](https://github.com/openrocket/openrocket/files/9230019/underpowered.zip)
I don't fully understand the bug originally reported in #1569, but it was pretty clearly something else.  So this doesn't fix that issue.
> When sitting on the ground, advance simulation time to next event time

- core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java
This PR fixes #1440 by including all context drags to the component drag (for friction and pressure CD) instead of simply setting the component drag to the last context's drag.
FinSets should now display the correct CD:
> [#1440] Add all context drags to component drag

- core/src/net/sf/openrocket/simulation/BasicEventSimulationEngine.java
> If we don't have any events left in the queue, shouldn't advance time

- swing/src/net/sf/openrocket/gui/dialogs/ScaleDialog.java
This PR fixes #411 by displaying the scale dialog error message in terms of the currently selected unit + the spinner widgets now have a larger width.
> [#411] Improvements to scale dialog

- core/src/net/sf/openrocket/rocketcomponent/FlightConfiguration.java
- swing/src/net/sf/openrocket/gui/dialogs/DebugLogDialog.java
- swing/src/net/sf/openrocket/gui/figure3d/photo/PhotoPanel.java
This PR fixes part of #1574, namely now there will no more flame lighting when the rocket has no motors.
The other part of #1574 that needs to be fixed is while PhotoStudio is active, and you add a new configuration with a motor, that motor is not drawn in PhotoStudio. Only if you close PhotoStudio and reopen it, the motor becomes visible. I will not handle a fix for that in this PR.
> [#1574] Fix motor flame lighting when no motor

- swing/src/net/sf/openrocket/gui/dialogs/EditDecalDialog.java
- swing/src/net/sf/openrocket/gui/dialogs/optimization/OptimizationPlotDialog.java
- swing/src/net/sf/openrocket/gui/dialogs/preset/ComponentPresetChooserDialog.java
- swing/src/net/sf/openrocket/gui/help/tours/SlideShowDialog.java
- swing/src/net/sf/openrocket/gui/main/BasicFrame.java
- swing/src/net/sf/openrocket/gui/plot/SimulationPlotDialog.java
- swing/src/net/sf/openrocket/gui/util/GUIUtil.java
- swing/src/net/sf/openrocket/gui/util/SwingPreferences.java
This PR fixes #1305 by adding the following changes to the preset dialog UI:
- By default larger window size (based on the size of BasicFrame - the main OR window)
- Rememberance of window size and location
- The window size and location is the same for the preset dialogs accross all component types. If you change the dialog size in the body tube preset dialog, then that same window size will be used for the nose cone preset dialog. Seems like the most reasonable approach to me.
- Rememberance of column widths
- This is custom for each different preset dialog. Changing e.g. the width of the second column in the body tube dialog does not alter the second column width in the nose cone preset dialog.
Demo:
https://user-images.githubusercontent.com/11031519/184496917-b7e5f9e1-91c6-465c-a3a9-ad …
> [#1305] Bigger default preset window size + remember column width

- swing/src/net/sf/openrocket/gui/configdialog/ParachuteConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/RecoveryDeviceConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/StreamerConfig.java
This PR fixes #1592 and updates the altitude widgets enable/disable state in the parachute and streamer config dialog, when the 'Deploys at' setting is changed.
> [#1592] Update recovery altitude slider state

- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
- swing/src/net/sf/openrocket/gui/print/PrintableFinSet.java
- swing/src/net/sf/openrocket/gui/scalefigure/FinPointFigure.java
This PR fixes #1227. The root edge of a fin set now correctly outlines a transition's shape both in the 3D view and in the fin template export. Besides the fins, the fin tabs also weren't drawn correctly (neither in the 2D view, nor in the 3D view - the fin tab root edge was always just a straight line). This PR solves that issue as well.
Demo (with a transparent transition):
https://user-images.githubusercontent.com/11031519/185255413-d52b3dcc-c1fa-4c30-9025-a2d433d4c4f4.mp4
Fin template export also works with fin tabs:
> [#1227] Fix fin root edge display in 3D view and fin template

- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
- swing/src/net/sf/openrocket/gui/configdialog/FinSetConfig.java
This PR fixes #1603 by correcting the fin set tab height validation (this also fixes an issue where if the aft diameter was smaller than the fore diameter, the tabs were able to grow over the rocket's centerline and overlap with each other). I also made it so that the slider of the fin tab height now dynamically updates its maximum value (in beta 4 you could still slide the slider even though the height value got clipped e.g. halfway).
> [#1603] Fix fin set tab height validation + dynamic max slider value

- swing/src/net/sf/openrocket/gui/widgets/IconButton.java
This PR fixes an issue in the icon buttons where pressing/holding down a button caused the button icon to jump back to its original size, instead of the intended reduced size. Probably a macOS thing...
Previous behavior:
https://user-images.githubusercontent.com/11031519/186762344-44288224-0127-491b-8107-c05d3669d92a.mov
New behavior:
https://user-images.githubusercontent.com/11031519/186762448-744e053c-9195-4674-b352-74231c480de9.mov
> Fix pressed icon size of IconButton

- core/src/net/sf/openrocket/rocketcomponent/TrapezoidFinSet.java
- swing/src/net/sf/openrocket/gui/configdialog/FinSetConfig.java
This PR fixes #1613. The following bugs are fixed:
- tab auto calc works for non-equal sized centering rings
- only use direct children of the fin's parent for the auto-calculation
- there was an issue where if a transition's aft or fore diameter differed, that the fin's height wasn't calculated properly
I did replicate @hcraigmiller's issue of the root edge not being drawn correctly.
> [#1613] Fix bugs in fin tabs auto calc

- swing/src/net/sf/openrocket/gui/adaptors/DoubleModel.java
- swing/src/net/sf/openrocket/gui/dialogs/preferences/SimulationPreferencesPanel.java
- swing/src/net/sf/openrocket/gui/simulation/SimulationOptionsPanel.java
This PR fixes #236 and limits the simulation time step setting to 0.01 s.
Although this is a simple PR, I did implement something that **needs testing** of whether it doesn't brake other stuff in the program. I added a check to `setValue` in `DoubleModel.java` that clips the set value to the model's maximum and minimum value. I must say I was surprised that this wasn't implemented already. The effect of this operation should be that when you type a numerical value in a spinner box and hit enter, that if that value was larger than the DoubleModel's maxValue, that the set value will be clipped to maxValue. Same goes for minValue in the other direction.
> [#236] Limit simulation time step to 0.01 s

- core/src/net/sf/openrocket/file/openrocket/savers/MassObjectSaver.java
- core/src/net/sf/openrocket/file/rocksim/export/BasePartDTO.java
- core/src/net/sf/openrocket/rocketcomponent/MassObject.java
- core/src/net/sf/openrocket/rocketcomponent/Parachute.java
- core/src/net/sf/openrocket/rocketcomponent/RecoveryDevice.java
This PR fixes #1315. New behavior for all mass objects:
- If the 'Auto' checkbox at (packed) diameter is unchecked:
- No special behavior; you can just edit the diameter and length as you please
- If you then enable the 'Auto' checkbox:
- The diameter will change to fit the parent component
- The length will change in such a way that the (packed) volume after enabling the 'Auto' checkbox is the same as the (packed) volume before enabling the checkbox. E.g. if the diameter is 5 cm before, length 5 cm (volume of 98.17 cm^3), enabling the 'Auto' checkbox changes the diameter to 10 cm, and the length to 1.25 cm (volume still 98.17 cm^3)
- You can still change the length in the auto mode, but this will now change the volume of the (packed) mass object. So let's say the diameter in auto mode …
> [#1315] Update auto length in MassObject

- swing/src/net/sf/openrocket/gui/rocketfigure/FinSetShapes.java
This PR fixes #1639 and translates fin set backview shapes if the minimum fin set points y-value is non-zero.
> [#1639] Take negative y fin points into account for back view

- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
- swing/src/net/sf/openrocket/gui/figure3d/geometry/FinRenderer.java
This PR fixes #1646. Turns out the fin root points resolution of 2.5 mm was too small. Increasing it to 5 mm appears to have solved the issue.
So fin template export will be **slightly** less smooth (see discussion [here](https://github.com/openrocket/openrocket/pull/1598#issuecomment-1218776893)).
> [#1646] Increase fin root resolution

- swing/src/net/sf/openrocket/gui/dialogs/ScaleDialog.java
This PR fixes #1653. The problem was the order of scaling. The previous behavior was that first the outer radius of the ring was scaled, and then the inner ring. This works for scaling up, but if scaled down, the outer radius would first scale down, would then become smaller than the inner radius, so the inner radius got clipped, and then the clipped inner radius got scaled down again. This PR changes the scaling order based on when you're scaling up or down. If scaled up, first the outer radius is scaled and then the inner radius, when scaling down, first the inner radius is scaled, and then the outer radius.
> [#1653] Scale RadiusRingComponent according to scale direction

- swing/resources-src/datafiles/legacy_components/bms-legacy.orc
> Correct thickness of BMS CR5060-W centering ring.

- core/test/net/sf/openrocket/simulation/DisableStageTest.java
I thought the DisableStageTest was stable after #1610, but I'm still getting sporadic unit test failures (although much less than before #1610). So I'm gonna increase the error margin from 2.5% to 5%, which is still reasonable.
> Increase error margin for DisableStageTest

- core/src/net/sf/openrocket/rocketcomponent/PodSet.java
- swing/src/net/sf/openrocket/gui/dialogs/ScaleDialog.java
This PR fixes #1662. The issue was in the scaling order, whereby the parent component of the pod was scaled first, and then the pod (and its offset). This caused the parent reference length for the axial offset to change first, and the scaled axial offset to be calculated incorrectly. This PR first does all the component offset scalings, and only then the component dimension scalings.
I also noticed the same issue as #1653, but for ThicknessRingComponents (e.g. TubeCoupler), which this PR fixes.
> [#1662] Fix scaling of pod axial offset + fix ThicknessRingComponent scaling down

- core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java
- core/src/net/sf/openrocket/aerodynamics/barrowman/SymmetricComponentCalc.java
- core/src/net/sf/openrocket/rocketcomponent/SymmetricComponent.java
- core/src/net/sf/openrocket/rocketcomponent/Transition.java
This PR fixes #1676 by setting the longitudinal and rotational inertia of a SymmetricComponent (transition/nose cone) to zero if the component length is zero. To then have the same behavior as a phantom body tube (the component acts as a disk and can still cause drag), I match the fore and aft radius to the max value of the two when the component length is zero. This is because a zero-length transition is just a disk, and a disk is just a zero-length tube. So matching the fore and aft radius will let the transition behave like a zero-length tube.
> [#1676] Treat zero-length SymmetricComponent as tube/disk

- build.xml
This PR adds targets in the root build file for running no-junit-report unit tests, which means that unit tests errors are shown in an output stream, e.g. your console, instead of the typical `index.html` JUnit report file.
Those no-junit-report already existed in the core and swing module, but not in the root build file.
> Add no-junit-report unit test targets in root

- core/resources/l10n/messages.properties
- core/src/net/sf/openrocket/rocketcomponent/AxialStage.java
- core/src/net/sf/openrocket/rocketcomponent/FlightConfiguration.java
- core/test/net/sf/openrocket/aerodynamics/BarrowmanCalculatorTest.java
- core/test/net/sf/openrocket/masscalc/MassCalculatorTest.java
- swing/src/net/sf/openrocket/gui/components/StageSelector.java
This PR fixes #1617 by marking empty stages as inactive. This is reflected in the stage selector buttons as a disabled button, which also indicates to new users that something is wrong with that stage. To make it even more clear, I added a tooltip text for the stage selector buttons for an empty stage: "This stages does not have any child components and is therefore marked as inactive. Add components to the stage to activate it.", and for a non-empty stage: "Toggle this button to activate or deactivate the corresponding stage in your design.".
Demo:
https://user-images.githubusercontent.com/11031519/191367445-6603c486-307b-4e53-a641-b2e16ab2f04b.mp4
> [#1617] Mark empty stages as inactive

- core/src/net/sf/openrocket/rocketcomponent/AxialStage.java
- core/src/net/sf/openrocket/rocketcomponent/FlightConfiguration.java
- core/src/net/sf/openrocket/rocketcomponent/Rocket.java
- core/test/net/sf/openrocket/rocketcomponent/AxialStageTest.java
- core/test/net/sf/openrocket/rocketcomponent/ParallelStageTest.java
This PR fixes #1680. Stages are now given a unique ID, just like flight configurations are assigned a unique ID (it's the same ID generation code). That unique ID is then used to identify stages when updating the stageMap in the flight configurations.
> [#1680] Update flight config stagemap according to unique stage ID

- core/src/net/sf/openrocket/simulation/listeners/example/DampingMoment.java
When attempting to run a simulation with the DampingMoment simulation listener added an exception is thrown and the variable is not computed.
It seems that AerodynamicCalculator.getForceAnalysis was modified to take in a WarningSet argument, however, for the DampingMoment listener, this was given as null, causing the error.
> Fixed error on using DampingMoment simulation listener

- core/src/net/sf/openrocket/file/openrocket/OpenRocketSaver.java
- core/src/net/sf/openrocket/file/openrocket/savers/PhotoStudioSaver.java
Fixes #1714, this approach felt cleaner than keeping the start and end tags in the list and handling those as special cases.
> Fixed photo studio save indents

- core/src/net/sf/openrocket/file/openrocket/savers/PhotoStudioSaver.java
- swing/src/net/sf/openrocket/file/photo/PhotoStudioGetter.java
- swing/src/net/sf/openrocket/file/photo/PhotoStudioSetter.java
- swing/src/net/sf/openrocket/gui/figure3d/photo/PhotoSettings.java
- swing/src/net/sf/openrocket/gui/figure3d/photo/exhaust/FlameRenderer.java
This PR fixes the bug reported on [TRF](https://www.rocketryforum.com/threads/announcement-openrocket-version-22-02-public-beta-5-is-now-available.171295/post-2328000) where opening PhotoStudio could throw an exception. The issue was that smokeOpacity in the .ork file was saved as 2.0, which was the converted to an alpha value of 510. Don't ask me why that happened, but it was either way redundant for a smokeOpacity field in the .ork file, since the alpha value was already stored in smokeColor. So this PR simply removes the smokeOpacity field in the .ork file.
> Don't explicitly save smokeAlpha in photostudio .ork

- swing/src/net/sf/openrocket/gui/main/DocumentSelectionModel.java
Fixes #1713, NPE was thrown when no components were selected and Edit > Scale was used to scale the rocket. This seems to be because `DocumentSelectionModel.getSelectedComponents` returns null if no components are selected, as opposed to an empty list.
> Fixed NPE when scaling when no components are selected

- swing/src/net/sf/openrocket/gui/plot/SimulationPlot.java
Fixes #1622, though I'm not a fan on the magic number, but I couldn't figure out how to determine the text's height as I can't get the font metrics. Any suggestions?
Before Fix:
After Fix:
> Fixed flight event labels getting cut off

- core/src/net/sf/openrocket/rocketcomponent/MassObject.java
- core/test/net/sf/openrocket/rocketcomponent/MassObjectTest.java
This PR fixes #1725 and adds unit tests for MassObject auto radius.
> Add unit tests for MassObject auto radius

- core/src/net/sf/openrocket/file/openrocket/importt/DocumentConfig.java
- core/src/net/sf/openrocket/rocketcomponent/MassObject.java
This PR fixes #1723. The issue was that the MassObject length was saved with the NoAuto parameter, but that during import the normal length was set, instead of LengthNoAuto.
> [#1723] Import MassObject length with NoAuto

- core/resources/l10n/messages.properties
- core/src/net/sf/openrocket/unit/UnitGroup.java
- swing/src/net/sf/openrocket/gui/dialogs/preferences/GeneralPreferencesPanel.java
- swing/src/net/sf/openrocket/gui/util/SwingPreferences.java
This PR fixes #1715. Now there is a button in the preferences for clearing cached preferences (UI settings, recent files list etc.). This is useful for people who have some messed up cached settings (e.g. the case of the missing windows when using OR with an external monitor - this issue is already solved, but just to give an idea of where this feature could be useful).
https://user-images.githubusercontent.com/11031519/195407557-328bcc72-2b8e-44c7-812f-23da012a7068.mp4
> [#1715] Add button in preferences for clearing cached preferences

- core/src/net/sf/openrocket/simulation/AbstractSimulationStepper.java
- core/src/net/sf/openrocket/simulation/BasicLandingStepper.java
- core/src/net/sf/openrocket/simulation/RK4SimulationStepper.java
If the recovery device deploys before apogee, the change in acceleration is negative so the timestep adjustment for jerk wasn't being applied.  In the event of  a deployment right at motor burnout, this could result in a huge simulated ground hit velocity.
Also, in the event of very large changes in acceleration, the time step could get absurdly small resulting in the simulation quite slowly until the acceleration settled out.
> Use absolute value of jerk in calculating time step in BasicLandingStepper, set minimum time step

- swing/src/net/sf/openrocket/gui/dialogs/optimization/SimulationModifierTree.java
This PR fixes #1742. (text is grey if the parameter is already in the optimization list)
> [#1742] Highlight text white if in selection

- swing/src/net/sf/openrocket/gui/dialogs/optimization/OptimizationPlotDialog.java
This PR fixes #1743. New plots:
> [#1743] Better background color for optimization plot

- .github/workflows/build.yml
This PR fixes #1758 and bumps the GitHub actions versions to v3 instead of v2, which I think support Node.js 16, but will have to check after creating this PR and verifying the GitHub build.
> [#1758] Bump GitHub actions

- core/src/net/sf/openrocket/simulation/BasicLandingStepper.java
- swing/src/net/sf/openrocket/gui/simulation/SimulationRunDialog.java
The progress bar dialog was trying to keep track of simulation apogee in two places; in one of them the "apogee" was actually one simulation status update after apogee.  Combined with the bug fixed in PR #1749, this could lead to a reported apogee of 0, causing the exception reported in #1728.  This PR removes the redundant apogee calculation.
Fixes #1728
The SimulationRunDialog sitll needs significant cleanup, but I'd like to just get this bug fix in now and save that for a later PR.
> Improve progress bar reporting

- swing/src/net/sf/openrocket/gui/simulation/SimulationRunDialog.java
It turned out there were two (more) issues:
1. The simulation ran so fast the rocket was on the ground before the first progress update happened.  Since the SimulationStatus was simply being published, this meant that all of the entries in the publish queue were references to the same status, and all the samples before it were effectively lost. Publishing a copy of the SimulationStatus fixes this.
2. Since vertical velocity is slightly less than 0 when apogee is detected, the max altitude code wasn't picking up on the apogee event. Looking for either positive z velocity or actual increase in altitude fixes this (we still need to also update if z velocity is positive so we reset after "false apogees" caused by things like calculating optimal recovery delay).
It also turned out the …
> Improve sampling for SimulationRunDialog

- core/src/net/sf/openrocket/document/OpenRocketDocumentFactory.java
- core/src/net/sf/openrocket/file/openrocket/importt/MotorConfigurationHandler.java
- core/src/net/sf/openrocket/file/openrocket/importt/OpenRocketLoader.java
- core/src/net/sf/openrocket/file/openrocket/savers/RocketSaver.java
- core/src/net/sf/openrocket/rocketcomponent/FlightConfiguration.java
- core/src/net/sf/openrocket/rocketcomponent/Rocket.java
- core/src/net/sf/openrocket/util/TestRockets.java
- core/test/net/sf/openrocket/file/openrocket/OpenRocketSaverTest.java
- core/test/net/sf/openrocket/rocketcomponent/AxialStageTest.java
- fileformat.txt
- swing/src/net/sf/openrocket/gui/main/BasicFrame.java
This PR fixes #1687 and adds stage activeness saving in the design file.
Example beginning of a saved file:
```XML
<?xml version='1.0' encoding='utf-8'?>
<openrocket version="1.8" creator="OpenRocket 22.02.beta.05">
<rocket>
<name>Three-staged rocket</name>
<axialoffset method="absolute">0.0</axialoffset>
<position type="absolute">0.0</position>
<designer>Sampo Niskanen</designer>
<motorconfiguration configid="da326836-0959-4c94-bcd5-49dee07235a4">
<stage number="0" active="true"/>
<stage number="1" active="true"/>
<stage number="2" active="true"/>
</motorconfiguration>
<motorconfiguration configid="05896b5a-71a7-48ac-b7ae-eadeb267975b">
<name>Hi, I have a name :)</name>
<stage number="0" active="true"/>
<stage number="1" active="false"/>
<stage number="2" active="true"/> …
```
> [#1687] Save stage activeness to design file

- swing/src/net/sf/openrocket/gui/figure3d/photo/PhotoPanel.java
This PR fixes #1574. Now when you add a new configuration while PhotoStudio is open, that configuration is drawn in PhotoStudio.
Steps to reproduce:
1. Open 'A simple model rocket'
2. Delete all the configurations
3. Open PhotoStudio
4. Add a new configuration and select a motor for it (PhotoStudio should still be open)
5. You can see the motor being rendered in PhotoStudio, which was previously not the case
> [#1574] Update PhotoPanel configuration on document change

- swing/src/net/sf/openrocket/gui/dialogs/preferences/PreferencesDialog.java
- swing/src/net/sf/openrocket/gui/scalefigure/RocketPanel.java
- swing/src/net/sf/openrocket/startup/OSXSetup.java
This PR fixes #1694. If you change the units in the preference dialog, and close the dialog, the units in the rocket view should get updated.
Note: the units for the stability info and flight info are not updated in the 3D view, see issue #1771.
> [#1694] Update rocket figure after unit change

- swing/src/net/sf/openrocket/gui/figure3d/RocketFigure3d.java
- swing/src/net/sf/openrocket/gui/scalefigure/RocketPanel.java
This PR fixes #1771, fixes #939, and fixes #1191. No more duplicated CG/CP markings!!!
The issue was that the carets (and extra text, such as stability info - see issue #1771) are drawn on the JOGL Overlay class. The overlay class has a function to mark areas as "dirty", which means they should be repainted. The dirty area apparently wasn't sized properly, which this PR solves.
https://user-images.githubusercontent.com/11031519/198417059-70aaa186-4d41-4315-9d24-3c4438739b72.mp4
> [#1771, #939, #1191] FIX OVERLAY ISSUES IN 3D VIEW!!!!

- swing/src/net/sf/openrocket/gui/figure3d/RocketFigure3d.java
This PR fixes #966, which was a weird 3D behavior (on macOS, but maybe also others?) when clicking on a textured part (e.g. the body tube or fins of 'A simple model rocket').
> [#966] Fix weird behavior when clicking on textured part in 3D view

- core/src/net/sf/openrocket/simulation/FlightEvent.java
-- if only one of the events has a source, the other one goes first.
-- if both have sources, lower (numerically higher) stage goes first.
In cases where two stages could separate simultaneously it was possible for either to land in the event queue first, which was disconcerting when looking at debug logs and unit test results.  This imposes an order based on stage number.  It should make no material difference to simulation results.
> Sort on source stage for simultaneous events

- core/src/net/sf/openrocket/util/TestRockets.java
- core/test/net/sf/openrocket/simulation/FlightEventsTest.java
The problem with the occasional failure of the flight events test results in PR #1798 was that the rocket apogee was exactly at motor burnout.  A tiny variation in time to apogee would change the order of the events in the flight, and even whether some of the events were associated with the sustainer or one of the boosters..
Change peak thrust of G77 simulation motor so Falcon9H test rocket do…esn't tumble until well after stage separations
Put order of expected events to match the new test rocket
> Modify Falcon9H test rocket and FlightEventsTest to get predictable results

- core/src/net/sf/openrocket/file/openrocket/importt/DocumentConfig.java
- core/src/net/sf/openrocket/file/openrocket/importt/DoubleSetter.java
- core/src/net/sf/openrocket/rocketcomponent/SymmetricComponent.java
- core/src/net/sf/openrocket/rocketcomponent/Transition.java
- swing/src/net/sf/openrocket/gui/configdialog/NoseConeConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/TransitionConfig.java
This PR fixes #1792. The issue was that when a transition, nose cone, or body tube got imported, first the thickness of the component was set and then the fore and aft radius. However, the thickness setter method clamped the thickness if it was greater than the aft and fore radius. Since the correct aft and fore radius was not yet set at that point, the thickness setter took the default fore and aft radius, which is 2.5 cm. So: if you saved the thickness with a value greater than 2.5 cm, that value would get clamped when re-opening the design.
This PR ignores the clamping of the thickness during import.
I also took the liberty of fixing the maximum value of the thickness slider, which was fixed at 1 cm. Now it updates dynamically with the fore and aft radius.
> [#1792] Don't clamp SymmetricComponent thickness when importing

- swing/src/net/sf/openrocket/gui/plot/PlotConfiguration.java
- swing/src/net/sf/openrocket/gui/plot/SimulationPlot.java
This PR fixes #1809. Data branches with no actual content are now ignored in the plots.
> [#1809] Ignore stages with no sim data in plots

- core/resources/l10n/messages.properties
- core/resources/l10n/messages_nl.properties
- swing/src/net/sf/openrocket/gui/configdialog/ComponentConfigDialog.java
- swing/src/net/sf/openrocket/gui/configdialog/RocketComponentConfig.java
- swing/src/net/sf/openrocket/gui/dialogs/preset/ComponentPresetChooserDialog.java
- swing/src/net/sf/openrocket/gui/main/ComponentAddButtons.java
This PR fixes #1479. There is now an option in the component preset dialog for opening the dialog when creating a new component. The dialog will not automatically open when you have created a component, close the config dialog, and edit the component again. It only works for newly created components. This feature is enabled by default. If you want it disabled by default, let me know.
Demo:
https://user-images.githubusercontent.com/11031519/201204718-232c73f5-e9f0-4736-a122-58e0dc4e6151.mp4
> [#1479] Add option to automatically open preset dialog when creating a new component

- core/src/net/sf/openrocket/rocketcomponent/Rocket.java
This PR fixes #1780. I have not been able to reproduce the bug so I can't be sure, but changing stageMap to a ConcurrentHashMap should resolve the issue. This comes with a performance hit for updating items in the map, but this isn't done very often, so it should be fine.
> [#1780] Use concurrent hashmap for stagemap

- core/src/net/sf/openrocket/simulation/listeners/example/StopSimulationListener.java
This PR fixes #1817. The issue was that StopSimulationListener had no zero-argument constructor. We should probably at one point support constructor parameter support for custom simulation listeners (tied with the radical UI improvement of #1719.
> [#1817] Create zero-argument constructor for StopSimulationListener

- core/src/net/sf/openrocket/file/openrocket/importt/ComponentPresetSetter.java
> [#1815] Don't let preset loading override component name on file import

- core/resources/l10n/messages.properties
- core/src/net/sf/openrocket/simulation/extension/impl/JavaCode.java
- swing/src/net/sf/openrocket/gui/simulation/SimulationOptionsPanel.java
- swing/src/net/sf/openrocket/simulation/extension/AbstractSwingSimulationExtensionConfigurator.java
- swing/src/net/sf/openrocket/simulation/extension/impl/JavaCodeConfigurator.java
This PR fixes #1819.
I also added a better simulation exception message for errors similar to #1817. It will now include the message "Could not instantiate class <classname>.Does it have a zero-argument, or @Inject constructor?". (should have done this in PR #1823, things got entangled a bit, my apologies)
Finally, I also added a small error text when the class entered in the simulation listener dialog was not valid (a small step towards #1719), and trimmed the TextField output so that typing whitespaces in the beginning or end of the classname does not affect the result. Error text demo:
https://user-images.githubusercontent.com/11031519/201666941-60e1e6c7-9300-4c3a-90a4-0e5cea04782f.mov
> [#1819] Update simulation extensions after new extension creation

- core/resources/l10n/messages.properties
- core/src/net/sf/openrocket/aerodynamics/Warning.java
- core/src/net/sf/openrocket/aerodynamics/WarningSet.java
- core/src/net/sf/openrocket/simulation/BasicEventSimulationEngine.java
Also, add a method to WarningSet making it easy to add a "discriminator" to warnings, informing the user what in a design or simulation is causing the warning.
The attached .ork results in an empty data branch for Stage 1
[empty-booster.ork.txt](https://github.com/openrocket/openrocket/files/9998418/empty-booster.ork.txt)
> Provide user with warning when a simulation branch contains no data

- core/resources/l10n/messages.properties
- core/resources/l10n/messages_cs.properties
- core/resources/l10n/messages_es.properties
- core/resources/l10n/messages_fr.properties
- core/resources/l10n/messages_it.properties
- core/resources/l10n/messages_nl.properties
- core/resources/l10n/messages_pl.properties
- core/resources/l10n/messages_pt.properties
- core/resources/l10n/messages_uk_UA.properties
- core/resources/l10n/messages_zh_CN.properties
- core/src/net/sf/openrocket/aerodynamics/AerodynamicCalculator.java
- core/src/net/sf/openrocket/aerodynamics/BarrowmanCalculator.java
- core/test/net/sf/openrocket/aerodynamics/BarrowmanCalculatorTest.java
Now that warnings have an easy way to add additional information, let's make use of it to tell users *where* discontinuities exist in body tubes.
A simple .ork showing the changed warning is attached.
Fixes 241
[discontinuous.ork.txt](https://github.com/openrocket/openrocket/files/10024071/discontinuous.ork.txt)
> Tell user where discontinuities in body tube diameter are

- swing/src/net/sf/openrocket/gui/simulation/SimulationRunDialog.java
This PR fixes #1824. If an out-of-date simulation is now run within the Edit dialog ("Simulate & Plot" button), the simulation table also updates.
> [#1824] Fire document update when simulation is done

- core/src/net/sf/openrocket/unit/UnitGroup.java
- core/src/net/sf/openrocket/util/StringUtil.java
- core/test/net/sf/openrocket/util/StringUtilTest.java
This PR fixes #1842. You can now type decimals using commas and dots in the fin shape editor table.
> [#1842] More general string conversion to double for fin editor table

- core/resources/l10n/messages.properties
- core/src/net/sf/openrocket/simulation/BasicEventSimulationEngine.java
At present, when a simulation throws an exception it gets caught and turned into a warning.  Really, anything so bad the simulation can't finish ought to bring up the simulation error dialog.  This PR causes the "catch" code to record the abort in the flight event branch and then rethrow the exception.
Fixes #1611.  This is actually a more general solution than what I asked for there.
The attached .ork aborts because there are no motors configured to start at launch time.
[empty-booster.ork.txt](https://github.com/openrocket/openrocket/files/10015053/empty-booster.ork.txt)
> When a simulation fails badly enough to be aborted, don't turn the exception into a warning

- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
- swing/src/net/sf/openrocket/gui/figure3d/geometry/FinRenderer.java
This PR fixes #1829. There was an issue with the tessellation creation of the fin polygon. Not gonna lie, I don't know what the actual issue was (I'm not used to OpenGL). I just searched for a bunch of example code on tessellation creation, tried a bunch of stuff and GitHub Copilot happened to propose the exact right piece of code for the tessellation `combine` method. So yeah, this PR is a happy little accident :) .
Because the fin 3D rendering is now more stable, I also increased the low poly fin resolution. So the root of a fin on curved surfaces is now rendered slightly more smooth than before. I still make it more low-poly than usual, otherwise the rendering can get slow.
https://user-images.githubusercontent.com/11031519/202320048-233ff2db-e662-4e24-bdf1-480d080e48c2.mov
> [#1829] Fix tessellation issue on fins with curved root

- core/src/net/sf/openrocket/rocketcomponent/FlightConfiguration.java
- core/test/net/sf/openrocket/rocketcomponent/BoundingBoxTest.java
> [#1849] Fix bounding box calculations for pods with mass components

- swing/src/net/sf/openrocket/gui/widgets/SelectColorButton.java
This PR fixes #1851. Since this is a macOS-issue, @hcraigmiller can't test it so I'll just assume that my testing was adequate and it functions as expected.
> [#1851] Reset button foreground on focus loss

- core/src/net/sf/openrocket/rocketcomponent/Rocket.java
- core/test/net/sf/openrocket/simulation/DisableStageTest.java
This PR fixes #1848 and allows to run simulations with only a booster stage active. I don't know how accurate the simulations are when you do that, but at least running the sim won't throw an exception.
> [#1848] Allow only booster stage to be active

- swing/src/net/sf/openrocket/gui/scalefigure/AbstractScaleFigure.java
- swing/src/net/sf/openrocket/gui/scalefigure/ScaleSelector.java
Trying to set a zoom smaller than the minimum size was provoking an infinite recursion.  It's not clear to me why we need min and max in the first place (the user can always use "Fit" to get back to something reasonable) so just get rid of them.
Fixes #1857
> Remove bounds on minimum and maximum zoom sizes

- core/src/net/sf/openrocket/util/BoundingBox.java
- swing/src/net/sf/openrocket/gui/scalefigure/AbstractScaleFigure.java
- swing/src/net/sf/openrocket/gui/scalefigure/FinPointFigure.java
This PR fixes #1655, where the fin set editor could sometimes go off-screen for fins on nose cones or transitions.
> [#1655] Use minimum mount bounds for fin set editor origin updating

- core/resources/l10n/messages.properties
- core/resources/l10n/messages_ja.properties
- core/resources/l10n/messages_nl.properties
- core/resources/l10n/messages_uk_UA.properties
- swing/src/net/sf/openrocket/gui/dialogs/BugReportDialog.java
Since we have to ask users a thousand times to send their .ork file and give the steps to reproduce an error:
> Reformat bug report dialog

- swing/src/net/sf/openrocket/gui/figure3d/photo/PhotoFrame.java
This PR ensures that PhotoStudio closes when you close the design file.
> Close PhotoStudio when parent window closes

- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
- swing/src/net/sf/openrocket/gui/figure3d/geometry/FinRenderer.java
This PR fixes #1679 by still rendering the fin set even if it has a zero-length (which happens when the last fin point is overlapping with the first one).
> [#1679] Render fin set even if zero length

- core/src/net/sf/openrocket/rocketcomponent/StageSeparationConfiguration.java
Nobody has been able to think of a situation in which this is necessary or helpful, and it provides a way for new users to get in trouble.
Fixes #1611
> Disallow stage separation at launch

- core/src/net/sf/openrocket/rocketcomponent/FreeformFinSet.java
- core/test/net/sf/openrocket/rocketcomponent/FreeformFinSetTest.java
- swing/src/net/sf/openrocket/gui/configdialog/FreeformFinSetConfig.java
This PR support multi-component fin set shape editing.
The basic principle is:
1. Editing the first fin point of the main fin set will edit the first fin point of the listener fin set
2. Editing the last fin point of the main fin set will edit the last fin point of the listener fin set
3. Editing intermediate fin points of the main fin set will edit the correspondingly indexed fin points of the listener fin set
1. If the main fin set has more points than the listener fin set, then ignore the out-of-bound points for the listener fin set
2. If the main fin set has more points than the listener fin set, e.g. main set has 5 points, listener set 4 points, if you edit point 4 of the main fin set (second-to-last point if the main set, last point of the listener set), then point 4 of the listener …
> Support multi-comp fin set shape editing

- core/src/net/sf/openrocket/simulation/BasicEventSimulationEngine.java
- core/test/net/sf/openrocket/simulation/FlightEventsTest.java
This PR fixes #1868. The issue was that the apogee flight event is added when the program notices that the current simulation step has an altitude lower than that of its stored maximum altitude. The issue is that the apogee event then uses the simulation time of the simulation step AFTER the actual apogee. This PR corrects for that.
Previously:
Now:
> [#1868] Set apogee flight event at the correct simulation time

- core/resources/l10n/messages.properties
- core/resources/l10n/messages_uk_UA.properties
- core/src/net/sf/openrocket/file/CSVExport.java
#1821 made clear that my personal annoyance is unjustified. But it did bring up the fact that the text "Data is out of date" should be replace by "Out of date", analogous to how "Up to date" is displayed.
> Replace "Data is out of date" to "Out of date"

- swing/src/net/sf/openrocket/gui/figure3d/photo/PhotoFrame.java
If you opened PhotoStudio for the first time, the settings window was way too small:
This PR fixes it:
You can now also close the settings dialog using the escape key, and the settings dialog now gains focus when starting up PhotoStudio, instead of the PhotoFrame having focus.
> Increase default PS settings window size

- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
- core/test/net/sf/openrocket/rocketcomponent/FreeformFinSetTest.java
- swing/src/net/sf/openrocket/gui/scalefigure/FinPointFigure.java
This PR fixes #1021. There is now an extra root point added at the front of the parent when the first fin point goes out of the parent's bounds. Same effect for the last point. When both the first and last fin point are outside the bounds (either to the left or right), no extra root point is added.
https://user-images.githubusercontent.com/11031519/206334470-56ddebac-726c-4f22-b6a6-e6a4d8cac56c.mov
> [#1021] Add extra root point(s) if fin is outside parent's bounds

- core/src/net/sf/openrocket/rocketcomponent/FlightConfiguration.java
- core/src/net/sf/openrocket/util/BoundingBox.java
- core/test/net/sf/openrocket/rocketcomponent/FlightConfigurationTest.java
- swing/src/net/sf/openrocket/gui/scalefigure/RocketFigure.java
This PR ensures that the rocket view fit zoom is only affected by active stages.
I also made it so that duplicating a configuration will also duplicate the stage activeness states. Plus I wrote unit tests for flight configuration cloning and copying.
Demo (beginning of the video is about the fit zoom, ending is about duplicating configurations)=
https://user-images.githubusercontent.com/11031519/207470990-31b3397e-01e4-4ba9-a6bd-c71040939232.mp4
> Only zoom to active stages

- core/src/net/sf/openrocket/document/Simulation.java
- core/src/net/sf/openrocket/simulation/BasicEventSimulationEngine.java
- core/src/net/sf/openrocket/simulation/exception/SimulationException.java
So for instance, in the flying motor mount in Issue #1898, the simulation can proceed through many steps before failing with a SimulationException.  This lets a user look at the data generated before the exception.
> Attach flight data to simulation exceptions so it can be preserved to help user track down the problem

- swing/src/net/sf/openrocket/gui/main/componenttree/ComponentTreeRenderer.java
> [#1895] Maintain tree cell font after override icon

- core/src/net/sf/openrocket/database/motor/ThrustCurveMotorSet.java
- core/test/net/sf/openrocket/database/ThrustCurveMotorSetTest.java
Require motor designations to match before motors can be said to match.  I *think* this is really leftover unfinished business from my PR #1032; that PR stopped trying to parse motor designations to create a "simplified designation" instead using common names for most purposes that previously used simplified designations.
The main reason for this is to get rid of the annoyance of MICRO_MAXX and MICRO_MAXX_II motors being confounded with each other in the motor selection dialog.
In general, I can't think of  a reason we'd want to be able to have multiple designations turn up as a single motor.
One possible concern with this is we want to make sure we can still find motors saved in 15.03 designs when loading from the new version.  That was only really a problem with CTI motors; I tried …
> Require designation match

- swing/src/net/sf/openrocket/gui/dialogs/BugReportDialog.java
- swing/src/net/sf/openrocket/gui/dialogs/preferences/GeneralPreferencesPanel.java
- swing/src/net/sf/openrocket/gui/util/SwingPreferences.java
This PR improves the bug report dialog in two ways:
1. Previously, there were was a different formatting of the "---------- Bug report ----------" section between the exception dialog (bug report dialog that pops up after an error occurred), and the normal bug report dialog (bug report dialog that opens when you go to the application ribbon > Help > Bug report). Now they have the same formatting.
2. I adding one line in the system information section to display the user-defined thrust curves location. This can be useful when users have thrust curve import issues.
Previous normal bug report dialog: (did not use the same formatting as the exception dialog)
New one: (uses the same formatting as the exception dialog + added the thrust curves line)
> Uniform bug report info section + add user-defined thrust curves location

- core/src/net/sf/openrocket/file/motor/ZipFileMotorLoader.java
- swing/src/net/sf/openrocket/database/MotorDatabaseLoader.java
In light of PR #1919, I think it is reasonable to generalize the exception-catching for motor file loading. So, instead of only catching IOExceptions during motor file loading, now every exception is caught. The upside is that however messed up the files and directories in the user's thrust curve directory is, it will (hopefully) not crash the entire program - as was the case for the TRF user from PR #1919. The downside is that - assuming that the exception dialogs work (PR #1919 shows that this is not always the case) - users will not have a direct feedback that an import failed due to a file/directory issue. You can still view the import error in the debug log though. 
FYI: with "file/directory issue", I mean an issue caused by the raw format of the file/directory, e.g. when you have a …
> Generalize error-catching of motor file loading

- core/src/net/sf/openrocket/unit/Unit.java
- swing/src/net/sf/openrocket/gui/dialogs/ComponentAnalysisDialog.java
This is related to PR 1924, but separate enough I wanted it to be its own PR.  Either of these two can be merged without the other.
This one makes two small changes: 
Iinstead of displaying Not a Number values as NaN, Unit.toString() now displays them as N/A.  This brings it into agreement with Unit.toStringUnit(), which already did that.  While a developer knows what NaN means, someone without a software background will probably find N/A more understandable.  You can see a place where toStringUnit() was using N/A in the RocketPanel display from Issue #1898, where it is used to identify the CP (which has a negative weight) as N/A
In the ComponentAnalysisDialog, if the rocket CP has a negative weight, this now displays it as N/A.  Previously, it would go ahead and display the calculated …
> Display nan as n/a

- core/resources/l10n/messages.properties
- core/src/net/sf/openrocket/simulation/BasicEventSimulationEngine.java
Exception says "Can't calculate rocket stability."
The basic problem with #1898 is it's impossible to calculate the flying motor mount "rocket"'s center of pressure except when it's flying backwards (at nearly 180 degrees).  This results in ever-faster gyrations until one parameter or another exceeds OR's limits.  I spent a little while seeing if I could adjust the simulation time step in response to the speed of the gyrations; the end of result of these experiments was I could calculate with ever-tinier timesteps which made the simulation speed drop to a crawl before finally throwing the exception.
This PR observes that the CP of the rocket assembly has a 0 or negative weight at launch and throws a more meaningful exception at that point.
Fixes #1898
> Throw exception at simulation startup if CP can't be calculated.

- swing/src/net/sf/openrocket/gui/figureelements/RocketInfo.java
This PR increases the darkness of the geometry warning color.
Before:
After:
> Darker warning color

- core/resources/l10n/messages.properties
No idea when those got deleted, but anyway, now they're back. Fixes the issue reported by @hcraigmiller [here](https://github.com/openrocket/openrocket/pull/1931#issuecomment-1367029948) (the first issue).
> Re-add nose cone config translations

- core/resources/l10n/messages.properties
- core/src/net/sf/openrocket/startup/Preferences.java
- core/src/net/sf/openrocket/util/LinearInterpolator.java
- swing/src/net/sf/openrocket/gui/plot/SimulationPlot.java
- swing/src/net/sf/openrocket/gui/simulation/SimulationPlotPanel.java
I recently noticed that apparently, when you make a sim plot where the x axis type is not time, OpenRocket plots the flight event markers using icons, instead of vertical markers. Since I think the markers can get messy pretty easily, I now added the option for time domain plots to switch between vertical markers and icon markers.
I also made the tooltip text of flight event icons more elaborate, to include the x axis value and sample count.
https://user-images.githubusercontent.com/11031519/210019076-360ffd3f-450b-4cc1-82cc-75e4aa53cd57.mp4
> Add option to switch (time) flight event markers to icons

- core/test/net/sf/openrocket/simulation/FlightEventsTest.java
There was just recently a build failure because the flight event time differed for more than 0.002 seconds (namely 0.003 seconds). So I'm gonna increase the error margin yet again, this time to a more safe yet very reasonable 0.005 seconds range.
> Increase error margin

- core/src/net/sf/openrocket/simulation/BasicEventSimulationEngine.java
The problem in #1938 turned out not to be the recovery devices in the pods, but rather that the sustainer motor was ignited again when each of the motors in the first stage burned out.
If a later stage motor's ignition event is triggered by burnout of earlier stage motors, an ignition event gets queued for every burnout in the earlier stage. This checks to see if a motor is already burning when an ignition event is processed for it, and ignores the event if so.
Fixes #1938
> Inhibit reignition of already ignited motor

- core/src/net/sf/openrocket/simulation/BasicTumbleStepper.java
Gets rid of minor annoyance that a rocket or stage using tumble recovery has a final altitude slightly less than 0
> Solve time step for ground hit in tumble stepper

- core/src/net/sf/openrocket/simulation/BasicLandingStepper.java
Fixes #1910
The .ork file associated with that bug report now shows descents at speeds of roughly 18.7, 13, and 10.8 fps for 1, 2, and 3 boosters in the booster set. 18/13 is approximately sqrt(2), and 18/10.8 is approximately sqrt(3) so this is expected.
> Consider number of parachutes in landing drag calculation

- swing/src/net/sf/openrocket/gui/SpinnerEditor.java
- swing/src/net/sf/openrocket/gui/adaptors/TextComponentSelectionKeyListener.java
- swing/src/net/sf/openrocket/gui/configdialog/RocketComponentConfig.java
This PR fixes #1942:
https://user-images.githubusercontent.com/11031519/211022585-567b42e9-32c4-4134-bdd3-8f1fb1292f15.mp4
Note: this fix is now only applied to spinner editors (practically all number-input fields in OR), and the component name and comment text fields. In the future, I may post a general fix for every text field etc., which would just require writing a new JTextField class and applying the fixed key listener to it. But for now, this PR should be good enough.
> [#1942] Fix text component selection key behavior

- .github/FUNDING.yml
Not that we really need extra funding right now, but for completeness sake, this PR adds a Support button on the GitHub page.
> Add GitHub sponsor button

- core/src/net/sf/openrocket/file/iterator/DirectoryIterator.java
- core/src/net/sf/openrocket/file/iterator/FileIterator.java
- core/src/net/sf/openrocket/file/iterator/ZipDirectoryIterator.java
- core/src/net/sf/openrocket/thrustcurve/SerializeThrustcurveMotors.java
- core/test/net/sf/openrocket/file/iterator/TestFileIterator.java
- swing/src/net/sf/openrocket/database/ComponentPresetDatabaseLoader.java
- swing/src/net/sf/openrocket/database/MotorDatabaseLoader.java
- swing/src/net/sf/openrocket/file/motor/MotorLoaderHelper.java
- swing/src/net/sf/openrocket/utils/SerializePresets.java
This PR fixes #1966. The `FileIterator` now passes a pair of the File and InputStream, instead of simply the file name and InputStream.
> [#1966] Pass File in FileIterator instead of filename

- core/src/net/sf/openrocket/document/Simulation.java
- core/src/net/sf/openrocket/file/openrocket/importt/OpenRocketLoader.java
- core/src/net/sf/openrocket/rocketcomponent/FlightConfiguration.java
- core/src/net/sf/openrocket/rocketcomponent/Rocket.java
- core/src/net/sf/openrocket/simulation/SimulationStatus.java
- swing/src/net/sf/openrocket/gui/components/StageSelector.java
- swing/src/net/sf/openrocket/gui/main/FlightConfigurationPanel.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/FlightConfigurablePanel.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/MotorConfigurationPanel.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/RecoveryConfigurationPanel.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/SeparationConfigurationPanel.java
This PR fixes #1973. Instead of marking simulations out-of-date based on the rocket's modID, I changed it to the modID of the flight configuration of that simulation. This ensures that any changes made to a flight configuration (new stage, remove stage, motor selection, ignition change, recovery/stage change...) will not affect simulations based on another flight configuration. If there are multiple simulations of flight configuration A, and flight configuration A is changed, then all those flight config A simulations will be marked out-of-date.
https://user-images.githubusercontent.com/11031519/212572691-3d9e5fd8-f645-499a-90f7-ef5bd7d6e6a9.mp4
> [#1973] Don't mark all simulations out-of-date on flight config change

- swing/src/net/sf/openrocket/gui/configdialog/AppearancePanel.java
When the default material is used, the edit button should be greyed out.
> Grey out texture edit button if using default material

- swing/src/net/sf/openrocket/gui/configdialog/AppearancePanel.java
- swing/src/net/sf/openrocket/gui/dialogs/EditDecalDialog.java
- swing/src/net/sf/openrocket/gui/dialogs/preferences/GraphicsPreferencesPanel.java
There appear to have been a total of three typos preventing decal editing in Linux
1) The test for snap confinement ended up not allowing any UNIX-like OSes to set the editor in the preferences
2) When the tests for desktop support failed, the text entry field for the command name and the command chooser were not enabled.
> Enable decal editing in Linux

- core/src/net/sf/openrocket/rocketcomponent/MassObject.java
- core/src/net/sf/openrocket/rocketcomponent/RocketComponent.java
- core/src/net/sf/openrocket/rocketcomponent/SymmetricComponent.java
- core/test/net/sf/openrocket/rocketcomponent/MassObjectTest.java
This PR fixes #2036. The issue was that some places use a direct call to `this.length` instead of using the `getLength()` method.
I never noticed it before, but the component CG of the parachute would not update when changing the auto radius (if the parachute suddenly halved in length, its CG should also update - which was previously not the case). This PR fixes that as well.
> [#2036] Fix incorrect position of parachute when auto radius

- core/src/net/sf/openrocket/unit/TemperatureUnit.java
- core/src/net/sf/openrocket/unit/UnitGroup.java
- core/test/net/sf/openrocket/unit/ValueTest.java
- swing/src/net/sf/openrocket/gui/dialogs/preferences/LaunchPreferencesPanel.java
- swing/src/net/sf/openrocket/gui/simulation/SimulationConditionsPanel.java
This PR fixes #2003. The temperature and pressure in the launch site settings now have a 2 decimal resolution. For the pressure, `bar` and `atm` remain the same, since that was already good at 0.001 resolution. The resolution of `Pa` is still at integers, that's accurate enough.
> [#2003] Increase resolution of launch temp and pressure to 2 decimals

- core/src/net/sf/openrocket/file/openrocket/OpenRocketSaver.java
- core/src/net/sf/openrocket/file/openrocket/savers/RocketComponentSaver.java
- core/src/net/sf/openrocket/util/TextUtil.java
This PR fixes #2051 by sanitizing some of the XML content when saving a .ork file.
Note: it is not possible to open files already saved with quotes, it is only possible to avoid this issue from happening in the future by sanitizing the XML content before saving it.
Steps to reproduce:
1. Add a body tube, go to its parts library
2. Search for "38mm Motor Mount tube 11" and apply it to the body tube
3. Save the file and close it
4. Open it again
> [#2051] Sanitize some XML content

- core/src/net/sf/openrocket/rocketcomponent/ExternalComponent.java
- core/src/net/sf/openrocket/rocketcomponent/LaunchLug.java
- core/src/net/sf/openrocket/rocketcomponent/RailButton.java
- core/test/net/sf/openrocket/masscalc/MassCalculatorTest.java
- core/test/net/sf/openrocket/rocketcomponent/LaunchLugTest.java
- core/test/net/sf/openrocket/rocketcomponent/RailButtonTest.java
This PR fixes #2040. The CM (mass+CG) of a rail button and launch lug now accounts for multiple instances.
While working on this issue, I also noticed that the CG of the launch lug was incorrectly calculated. Here is a design with a body tube's diameter and length set to 0:
You can see that CG.y is not in the center of the launch lug. The same issue was present for CG.z.
Behavior from this PR:
> [#2040] Fix CM of launch lug & rail button instances

- core/resources/l10n/messages.properties
- core/src/net/sf/openrocket/aerodynamics/Warning.java
- core/src/net/sf/openrocket/aerodynamics/barrowman/FinSetCalc.java
Revert "Don't let fins with zero area cause NaN exceptions."
This reverts commit 1011f2df944dbfe3e82016ea0a3a0f0954c1ca9b.
Revert "Add warning for fin with zero area"
This reverts commit 512ce78b51a2514a5e96f72d9e8946d63b291cd9.
> pushed to the wrong branch, sorry

- core/resources/l10n/messages.properties
- core/src/net/sf/openrocket/formatting/MotorConfigurationSubstitutor.java
- core/src/net/sf/openrocket/motor/Motor.java
- core/src/net/sf/openrocket/motor/MotorConfiguration.java
- core/src/net/sf/openrocket/motor/MotorConfigurationSet.java
- core/src/net/sf/openrocket/startup/Preferences.java
- swing/src/net/sf/openrocket/gui/dialogs/motor/thrustcurve/MotorHolder.java
- swing/src/net/sf/openrocket/gui/dialogs/motor/thrustcurve/MotorInformationPanel.java
- swing/src/net/sf/openrocket/gui/dialogs/motor/thrustcurve/ThrustCurveMotorSelectionPanel.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/MotorConfigurationPanel.java
- swing/src/net/sf/openrocket/gui/util/SwingPreferences.java
This PR fixes #2072. Selecting either "common name" or "manufacturer's designation" in the motor selection table will now also update other parts of OR.
https://user-images.githubusercontent.com/11031519/221307406-3fac9769-776d-48f1-a904-45d7322e0f75.mp4
> [#2072] Apply designation/common name choice to other parts

- swing/src/net/sf/openrocket/gui/figure3d/photo/PhotoSettings.java
- swing/src/net/sf/openrocket/gui/figure3d/photo/PhotoSettingsConfig.java
For some reason, the FOV in PhotoStudio was limited to 1 rad (57.3 °). I don't see immediate issues with decreasing this limit, so this PR decreases the limit to 10°.
https://user-images.githubusercontent.com/11031519/221654214-b8082660-4961-4f8e-857e-ab1bf2e60403.mp4
> Decrease lower-limit of FOV

- swing/src/net/sf/openrocket/gui/print/visitor/PartsDetailVisitorStrategy.java
This PR fixes #2084. Pods and booster components are now included in the parts details.
Export results for "Pods--airframes and winglets" example design:
> [#2084] Include parts details for pods and boosters

- core/resources/l10n/messages.properties
- core/src/net/sf/openrocket/aerodynamics/Warning.java
- core/src/net/sf/openrocket/aerodynamics/barrowman/FinSetCalc.java
Warn that fins with zero area will not affect aerodynamics
Keep fins with zero area from getting NaN errors
Fixes #2032
> Tell user about zero-area fins and keep them from crashing simulation with NaN error

- core/src/net/sf/openrocket/file/openrocket/importt/OpenRocketLoader.java
- core/src/net/sf/openrocket/file/openrocket/importt/SingleSimulationHandler.java
- core/test/net/sf/openrocket/file/openrocket/OpenRocketSaverTest.java
(see discussion of sim loading error at https://discord.com/channels/1073297014814691328/1078123170088878130/1080633494604107796)
The problem with nearly all the sims being marked as "out of date" was that a single loop was being used both to determine whether any of the sims had been saved with data, and to mark them as current.  I exited when a sim with data was identified; all the sims needed to be updated.  Loop isn't exiting early now.
Added a unit test to determine whether a sim was stored in a state in which it couldn't be run (I'm not sure that can happen in practice), runnable but not run, current, or out of date.  
Refined sim loading a bit to identify when loaded data was out of date when it was stored, and mark it out of date.
> Fix error in sim loading, add unit test, refine loading a bit.

- core/src/net/sf/openrocket/aerodynamics/barrowman/RailButtonCalc.java
- core/test/net/sf/openrocket/aerodynamics/BarrowmanCalculatorTest.java
Railbutton pressure drag ended up being multiplied by number of railbuttons because pressure drag was computing total pressure drag for all railbuttons, then it got multiplied by number of railbuttons elsewhere.  Compute average pressure drag instead, so total railbutton drag is correct.
Check for very small velocities and avoid division by 0 by setting pressure drag multiplier to a fixed number in that case.
Add unit tests to both of the above.
Fixes #2115
> Railbutton pressure drag tweaks

- swing/src/net/sf/openrocket/gui/figure3d/RealisticRenderer.java
This PR fixes #2107. Decals are now not rendered on component edges anymore.
> [#2107] Don't render decals on component edges

- core/src/net/sf/openrocket/unit/InchUnit.java
- core/src/net/sf/openrocket/unit/UnitGroup.java
This PR fixes #2098. Lengths in inches now have a 0.1" precision instead of 1".
> [#2098] Use higher precision for inches lengths

- core/src/net/sf/openrocket/simulation/SimulationOptions.java
- swing/src/net/sf/openrocket/gui/main/BasicFrame.java
- swing/src/net/sf/openrocket/gui/main/ExampleDesignFileAction.java
- swing/src/net/sf/openrocket/gui/main/SimulationPanel.java
- swing/src/net/sf/openrocket/gui/simulation/SimulationEditDialog.java
This PR fixes #2148 and fixes #1826. Now, when closing the edit sim dialog in **any way** (clicking the close button, hitting the escape key, x-button in top-left of the window) applies the simulation options to all selected simulation.
The fix for #1826 is that multi-sim editing had some gaps, namely:
- The checkbox for "Always launch directly up-wind"
- The checkbox for "Use ISA"
- Geodetic calculations
These are now fixed.
> [#2148] Apply sim changes when window closes & [#1826] Fill in gaps in multi-sim editing

- swing/src/net/sf/openrocket/gui/figure3d/photo/PhotoPanel.java
There was still an issue with #2157, where saving a PhotoStudio image with off-screen rendering disabled would result in an opaque background instead of transparent. This is now fixed in this PR.
> Fix issue with exporting of transparent image when off-screen rendering is disabled

- swing/src/net/sf/openrocket/gui/dialogs/flightconfiguration/MotorMountConfigurationPanel.java
> [#2179] Fix mount name column text being cut off too early

- core/src/net/sf/openrocket/file/openrocket/importt/DocumentConfig.java
- core/src/net/sf/openrocket/file/openrocket/savers/BodyTubeSaver.java
- core/src/net/sf/openrocket/file/openrocket/savers/MassObjectSaver.java
- core/src/net/sf/openrocket/file/openrocket/savers/NoseConeSaver.java
- core/src/net/sf/openrocket/file/openrocket/savers/TransitionSaver.java
- core/src/net/sf/openrocket/rocketcomponent/BodyTube.java
- core/src/net/sf/openrocket/rocketcomponent/MassObject.java
- core/src/net/sf/openrocket/rocketcomponent/NoseCone.java
- core/src/net/sf/openrocket/rocketcomponent/Transition.java
- core/test/net/sf/openrocket/rocketcomponent/MassObjectTest.java
- core/test/net/sf/openrocket/rocketcomponent/NoseConeTest.java
- swing/src/net/sf/openrocket/gui/dialogs/ScaleDialog.java
This PR fixes #2096. After checking the "Automatic" checkbox on any rocket component setting, that setting will remain saved, even after unchecking the 'Automatic" checkbox.
> [#2096] Update values after auto is set

- core/resources/l10n/messages.properties
- core/src/net/sf/openrocket/file/motor/RASPMotorLoader.java
- swing/src/net/sf/openrocket/database/MotorDatabaseLoader.java
This PR fixes #2150 by showing a warning dialog when a thrust curve file has an illegal file format.
There is still a discussion in #2150 about how to handle a motor designation with a dash.
> [#2150] Don't let illegal file format be a silent warning

- swing/src/net/sf/openrocket/gui/util/SwingPreferences.java
This PR fixes #2141.
Steps to reproduce the original bug:
1. Open "A simple model rocket"
2. Go to the simulations tab, and plot simulation 1
3. Move the plot window to a secondary monitor screen
4. Close the plot window
5. Re-plot simulation 1, you will see that the window remains on the secondary monitor screen
6. Unplug the secondary monitor screen
7. Re-plot simulation 1 again
8. Plot window can be gone
Steps to verify the solution = same as the bug steps, but in step 8, the plot window should be centered on the screen again.
Note: this is now implemented as a general solution. For every window that has window location remembrance enabled, OR will first check whether the window is positioned on an existing screen. If not, it will reset the position.
> [#2141] Reset window position if out-of-screen

- core/src/net/sf/openrocket/rocketcomponent/RocketComponent.java
- core/test/net/sf/openrocket/masscalc/MassCalculatorTest.java
- core/test/net/sf/openrocket/simulation/DisableStageTest.java
This PR fixes #2171 by computing a rocket component's position only based on active components.
https://user-images.githubusercontent.com/11031519/230635048-00e8fa69-b921-4058-ae63-897e6dc47153.mov
> [#2171] Compute position based on active components

- core/src/net/sf/openrocket/rocketcomponent/RocketComponent.java
- swing/src/net/sf/openrocket/gui/main/OpenRocketClipboard.java
- swing/src/net/sf/openrocket/gui/main/RocketActions.java
This PR fixes #2183. You can now copy components that have boosters as children. The issue was that the copying code contained some `addChild(component)` and `removeChild(component)` code which would automatically track the stage, if component was an instance of a stage. Now, when copying, the copy components don't have a reference to a rocket (as should be), so the stage tracking failed and threw an exception. This PR bypasses stage tracking when doing a copy-operation.
> [#2183] Don't track stages when copying

- core/resources/l10n/messages.properties
- swing/src/net/sf/openrocket/gui/components/DescriptionArea.java
- swing/src/net/sf/openrocket/gui/plot/SimulationPlotDialog.java
- swing/src/net/sf/openrocket/gui/simulation/SimulationPlotPanel.java
Fixes #2161 
The plot dialog warns that all data is plotted in time order regardless of X axis type, but this warning is easy to miss.
The message was removed by default and on changing to an X axis type other than time, a red warning will appear.
[Here is a jar file for testing](https://drive.google.com/file/d/1YJp7lEhRgSuI3k13kbFqVgx6vLZBWWz-/view?usp=share_link)
> [Enhancement] Add better warning that data will be plotted in time order

- core/src/net/sf/openrocket/rocketcomponent/ExternalComponent.java
- core/src/net/sf/openrocket/rocketcomponent/LaunchLug.java
- core/src/net/sf/openrocket/rocketcomponent/RailButton.java
- core/test/net/sf/openrocket/masscalc/MassCalculatorTest.java
- core/test/net/sf/openrocket/rocketcomponent/LaunchLugTest.java
- core/test/net/sf/openrocket/rocketcomponent/RailButtonTest.java
This PR fixes #2217. The was caused by PR #2053 - I didn't realize that componentVolume was that of all the instances instead of a single instance.
Additionally, I noticed an issues with launch lugs and rial buttons where the y and z location of the CG wasn't right. If you created a new design with just a body tube and rail button/launch lug and overdid the mass of the body tube to 0, the CG should be located solely at the rail button/launch lug, which wasn't the case. This is now fixed.
> [#2217] Fix mass issues for fin sets (+ CM of launch lug and rail buttons)

- ReleaseNotes.md
- core/resources/build.properties
- swing/src/net/sf/openrocket/gui/main/BasicFrame.java
- swing/src/net/sf/openrocket/startup/OSXSetup.java
This PR fixes #2222. Opening a file with the file association should now also cause that file to open in the recent design files.
> [#2222] Fix file association Open Recent

- swing/resources-src/datafiles/components-openrocket/Estes-legacy.orc
- swing/resources-src/datafiles/components-openrocket/LocPrecision-legacy.orc
- swing/resources-src/datafiles/components-openrocket/Quest-legacy.orc
- swing/resources-src/datafiles/components-openrocket/bluetube-legacy.orc
- swing/resources-src/datafiles/components-openrocket/bms-legacy.orc
- swing/resources-src/datafiles/components-openrocket/fliskits-legacy.orc
- swing/resources-src/datafiles/components-openrocket/giantleaprocketry-legacy.orc
- swing/resources-src/datafiles/components-openrocket/publicmissiles-legacy.orc
- swing/resources-src/datafiles/components-openrocket/semroc-legacy.orc
*Only* updates the unit specifiers, not values.  The values appear to have all been in MKS units, while the unit specifiers were in error.
In spite of my own earlier remark that I preferred using "if legacy" flags in the code to maintaining the legacy database, once I started looking at it simply making these corrections was enough cleaner than mucking with the code that it's what I did.
Fixes #2245
> update legacy component preset databases setting all units to SI, instead of the various mixes of g, kg, cm, and m that previously existed.

- core/resources/l10n/messages.properties
- core/src/net/sf/openrocket/rocketcomponent/RocketComponent.java
- swing/src/net/sf/openrocket/gui/dialogs/ComponentAnalysisDialog.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/FlightConfigurablePanel.java
This PR fixes #1629. When the mass, CG or CD of a component is not overridden, the override values will be the calculated values.
Demo:
https://github.com/openrocket/openrocket/assets/11031519/4f1ead16-5b26-4c78-96e0-189f8b773177
Note: when toggling the override CD the simulation results can slightly change. This is because in the overridden state, the individual CD components (pressure, base & friction CD) are set to 0 and only the total CD is decisive, so I think that's the reason for the very small difference.
---
Additionally, I also improved the formatting of the component analysis stability, drag characteristics and roll dynamics tables. The number formatting is now more standardized (better decimal behavior and decimal separator of locale) + when selecting a row, the row now also …
> [#1629] Show calculated mass, CG & CD in override tab if not overridden

- core/src/net/sf/openrocket/rocketcomponent/EllipticalFinSet.java
- core/src/net/sf/openrocket/rocketcomponent/FinSet.java
- core/src/net/sf/openrocket/rocketcomponent/FreeformFinSet.java
- core/src/net/sf/openrocket/rocketcomponent/TrapezoidFinSet.java
- core/test/net/sf/openrocket/rocketcomponent/FreeformFinSetTest.java
- core/test/net/sf/openrocket/rocketcomponent/TrapezoidFinSetTest.java
- swing/src/net/sf/openrocket/gui/figure3d/geometry/FinRenderer.java
This PR fixes #2231 and fixes #2242. Regarding #2242, the 3D view now rotates a canted fin correctly around its root center. Regarding #2231, the root (and fin) points now account for canted fins (you'll see a slight parabola shape for the root now).
Demo:
https://github.com/openrocket/openrocket/assets/11031519/d16ac598-5244-480c-a8a8-10d03eba35fd
> [#2231 & #2242] Account for fin cant in root points

- swing/src/net/sf/openrocket/gui/dialogs/ComponentAnalysisDialog.java
This PR fixes #2256 by fixing the width of the warnings panel in the component analysis dialog.
> [#2256] Use fixed width for warnings panel

- swing/src/net/sf/openrocket/gui/figureelements/RocketInfo.java
This PR fixes an issue with the rendering of the rocket info, where the CG/CP text would be to far to the left (because of the long stability text).
Then:
Now:
> Separate stability info text from rest

- core/src/net/sf/openrocket/rocketcomponent/AxialStage.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/SeparationConfigurationPanel.java
This PR fixes #2244. The issue was that there was a check that verifies whether you're editing the default flight config, and if so OR would create a new flight config. This PR now clones the default config, which retains the separation settings.
Additionally, this PR fixes #2249.
> [#2244 & #2249] Copy default sep config instead of creating new one

- core/resources/l10n/messages.properties
- core/src/net/sf/openrocket/simulation/AbstractEulerStepper.java
- core/src/net/sf/openrocket/simulation/RK4SimulationStepper.java
It would have been more aesthetically pleasing to just check at the start of each simulation branch, but a buggy simulation listener could cause the mass to be zero at a later time in the branch.
Also, removed comment in AbstractEulerStepper claiming mass could be calculated once at the start of the branch, due to possibility of simulation listeners.
Fixes #2196
> Check for 0 mass when running simulation

- core/resources/l10n/messages.properties
- core/src/net/sf/openrocket/startup/Preferences.java
- swing/src/net/sf/openrocket/gui/configdialog/RocketComponentConfig.java
- swing/src/net/sf/openrocket/gui/configdialog/SaveDesignInfoPanel.java
- swing/src/net/sf/openrocket/gui/main/BasicFrame.java
This PR aids users who are not aware that you can edit the design information by editing the rocket in the component tree, as mentioned in #2234.
When a new design is saved, or you save an existing file with the "Save As" functionality, a dialog pops up. The dialog is the same as the rocket config dialog, with some additions (informative label on top + "Don't show again" checkbox at the bottom). The rocket is also selected in the component tree to indicate to users that they can edit the design info by editing the rocket.
Demo:
https://github.com/openrocket/openrocket/assets/11031519/26e4088c-996c-4e00-8b75-332da3efc969
> Open dialog to save design information when saving the file

- core/src/net/sf/openrocket/rocketcomponent/MassObject.java
This PR fixes #2267. The issue was that the auto radius method should've checked the nose cone base radius, not the aft radius.
> [#2267] Check for nose cone base radius for massObject auto radius

- core/src/net/sf/openrocket/rocketcomponent/AxialStage.java
This PR fixes #2270. The issue was that when checking for the upper stage, the stage number was used to find the previous stage index. In the case of #2270, because there are boosters in the sustainer, the previous (upper) stage index was that of one of the boosters instead of the sustainer. So, this PR just checks for the index of the current stage relative to the rocket.
> [#2270] Only check axial stages for upper stage, not boosters

- core/resources/l10n/messages.properties
- core/src/net/sf/openrocket/rocketcomponent/InnerTube.java
- swing/src/net/sf/openrocket/gui/configdialog/InnerTubeConfig.java
This PR fixes #1970 and is a continuation of the work done by @jura0207 in #1974. You can now choose to set the inner tube cluster separation in relative or absolute units.
Demo:
https://github.com/openrocket/openrocket/assets/11031519/7e236462-91ba-4af5-89bb-3c75fe1bb79d
> [#1970] Add absolute inner tube separation option

- core/src/net/sf/openrocket/rocketcomponent/InnerTube.java
- swing/src/net/sf/openrocket/gui/configdialog/InnerTubeConfig.java
This PR fixes #2283.
https://github.com/openrocket/openrocket/assets/11031519/0d627f7e-9576-4fd0-ba9b-39d6c51704a4
> [#2283] Apply radial positioning to non-single cluster

- swing/src/net/sf/openrocket/gui/dialogs/motor/thrustcurve/MotorFilterPanel.java
- swing/src/net/sf/openrocket/gui/dialogs/motor/thrustcurve/MotorInformationPanel.java
- swing/src/net/sf/openrocket/gui/dialogs/motor/thrustcurve/ThrustCurveMotorSelectionPanel.java
- swing/src/net/sf/openrocket/gui/util/CheckListRenderer.java
This PR fixes #2298.
I also fixed an issue where the "Number of motors" text below the motor table was not shown + I added borders around some of the widgets.
> [#2208] Fix manufacturers' list in dark theme

- swing/src/net/sf/openrocket/gui/figure3d/RealisticRenderer.java
This PR fixes #2295.
Drawback is that the opacity of the color has no effect, but I already spent too much time trying to fix it, so I'll leave that as is for now.
> [#2295] Use component color for sticker edge mode

- core/src/net/sf/openrocket/simulation/AbstractEulerStepper.java
- core/src/net/sf/openrocket/simulation/BasicEventSimulationEngine.java
- core/src/net/sf/openrocket/simulation/RK4SimulationStepper.java
- core/src/net/sf/openrocket/simulation/SimulationConditions.java
- core/src/net/sf/openrocket/simulation/SimulationOptions.java
The simulation status identifies some simulation parameters (such as rocket orientation angles) as "extra", and checks whether a simulation option for calculating these extras is set before calculating and saving them.  I can't find any way to set this variable to anything other than "true" (I've got a hunch it went away back when we got rid of the option to only save "primary figures", but haven't checked).  Anyway, it appears to do nothing, so this gets rid of it and always calculates and saves these extras.
> Remove capability to not compute and save "extra" simulation parameters

- core/src/net/sf/openrocket/rocketcomponent/RecoveryDevice.java
- swing/src/net/sf/openrocket/gui/dialogs/flightconfiguration/DeploymentSelectionDialog.java
- swing/src/net/sf/openrocket/gui/dialogs/flightconfiguration/IgnitionSelectionDialog.java
- swing/src/net/sf/openrocket/gui/dialogs/flightconfiguration/SeparationSelectionDialog.java
- swing/src/net/sf/openrocket/gui/main/FlightConfigurationPanel.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/FlightConfigurablePanel.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/MotorConfigurationPanel.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/RecoveryConfigurationPanel.java
- swing/src/net/sf/openrocket/gui/main/flightconfigpanel/SeparationConfigurationPanel.java
- swing/src/net/sf/openrocket/gui/util/GUIUtil.java
This PR fixes #2307. Every config action in the motors & recovery tab now has a dedicated undo action (select motor, delete motor, select ignition, reset ignition, select deployment, reset deployment, select separation and reset separation).
Whilst working on this PR, I also found some pretty serious bugs in multi-comp editing the motors, recovery and stages. An example bug:
1. Open 'Three-stage rocket'
2. Go to recovery tab, select middle and first config, change deployment to 1 s
3. All configs change, instead of only first 2
This PR fixes those bugs for each tab.
> [#2307] Add dedicated undo actions + fix multi-comp editing for motors & recovery settings

- swing/src/net/sf/openrocket/gui/main/componenttree/ComponentTree.java
- swing/src/net/sf/openrocket/gui/main/componenttree/ComponentTreeRenderer.java
This PR fixes #2329. Component tooltips are back :)
> [#2329] Apply component tooltip to panel

- swing/src/net/sf/openrocket/gui/dialogs/WelcomeDialog.java
- swing/src/net/sf/openrocket/gui/dialogs/preset/ComponentPresetTable.java
One of our beta testers found a bug: if you use the dark theme, open the component preset dialog and then click a checkbox without having a row previously selected, OR would throw an exception.
> Don't use selected row, but target row for preset selection

- core/src/net/sf/openrocket/file/wavefrontobj/export/OBJExporterFactory.java
- core/src/net/sf/openrocket/util/FileUtils.java
- swing/src/net/sf/openrocket/gui/widgets/SaveFileChooser.java
This PR fixes #2341 by sanitizing the group names before exportin.
> [#2341] Sanitize OBJ export groupnames

- swing/src/net/sf/openrocket/gui/dialogs/preset/ComponentPresetChooserDialog.java
- swing/src/net/sf/openrocket/gui/dialogs/preset/ComponentPresetTable.java
- swing/src/net/sf/openrocket/gui/util/GUIUtil.java
In the component preset table, you can right-click the header to hide/show columns and change the units. However, the columns displayed were not correct; every column from each different rocket component was displayed:
(notice screw entries etc.)
Additionally, in dark mode, the units used checkboxes, so you could select multiple units (does not make sense):
---
Fix after this PR:
Correct units:
> Fix component preset table column popup menu

- install4j/23.09/openrocket-23.09.install4j
This PR adds the JVM arguments `--add-exports java.base/java.lang=ALL-UNNAMED --add-exports java.desktop/sun.awt=ALL-UNNAMED --add-exports java.desktop/sun.java2d=ALL-UNNAMED` to the install4j configuration which is a Q&D fix for #2336. See also https://github.com/jzy3d/jogl/issues/4.
Created a Windows installer and tested on my Windows machine, which did not throw the exception from #2336 anymore.
> Add JVM arguments to fix 3D issue on Windows

- core/src/net/sf/openrocket/rocketcomponent/SymmetricComponent.java
- core/test/net/sf/openrocket/masscalc/MassCalculatorTest.java
The shoulders are not considered in computing moments of inertia in SymmetricComponent, but were considered in computing CG when applying the parallel axis theorem at the end of the calculation.  This results in an inaccurate longitudinal moment of inertia, which could even become negative (there was code clamping the result to avoid that).
This PR fixes the bug in the sense that the code now does what the original author intended, but the shoulders should really be considered in moment of inertia calculations.
Fixes #2278
> Don't consider shoulders in applying parallel axis theorem to longitudinal moment of inertia

- swing/src/net/sf/openrocket/gui/dialogs/optimization/GeneralOptimizationDialog.java
- swing/src/net/sf/openrocket/gui/dialogs/preset/ComponentPresetChooserDialog.java
- swing/src/net/sf/openrocket/gui/dialogs/preset/ComponentPresetTable.java
- swing/src/net/sf/openrocket/gui/dialogs/preset/XTableColumnModel.java
- swing/src/net/sf/openrocket/gui/main/SimulationPanel.java
- swing/src/net/sf/openrocket/gui/util/GUIUtil.java
- swing/src/net/sf/openrocket/gui/util/PreferencesExporter.java
- swing/src/net/sf/openrocket/gui/util/SwingPreferences.java
- swing/src/net/sf/openrocket/gui/util/TableUIPreferences.java
This PR fixes #2357. The component preset table now remembers the following settings:
- column widths
- column order (when you click and drag columns around)
- column visibility (when you right-click on the table column header and hide a column)
Previously, only the column width was remembered. Additionally, this PR also cleans the column width remembering code.
https://github.com/openrocket/openrocket/assets/11031519/659678ef-c345-461e-997a-a27f9489488c
> [#2357] Remember column width, order, and visibility in preset table

- swing/src/net/sf/openrocket/gui/dialogs/motor/thrustcurve/MotorInformationPanel.java
- swing/src/net/sf/openrocket/gui/dialogs/motor/thrustcurve/ThrustCurveMotorSelectionPanel.java
- swing/src/net/sf/openrocket/gui/plot/SimulationPlot.java
- swing/src/net/sf/openrocket/gui/plot/Util.java
This PR fixes #2385 by using the OpenRocket plot colors for the thrust curves as well.
Additionally, I added an improvement where hovering over an item in the thrust curve combobox now uses the thrust curve color as the selection background color:
https://github.com/openrocket/openrocket/assets/11031519/6d1b5ff6-dc11-491e-98d7-bc3809162fb4
https://github.com/openrocket/openrocket/assets/11031519/ef4ec21e-d345-4560-9518-5d185b6cb98a
> [#2385] Use plot colors for thrust curves

- core/src/net/sf/openrocket/aerodynamics/barrowman/TubeCalc.java
> Avoid divide by 0 in TubeCalc when velocity is 0 by setting CD to 0 in this case.

- core/src/net/sf/openrocket/masscalc/MassCalculation.java
- core/src/net/sf/openrocket/rocketcomponent/RocketComponent.java
- core/test/net/sf/openrocket/masscalc/MassCalculatorTest.java
Corrects some comments involving overrides in RocketComponent (the comments seem to have not been updated when subcomponent overrides for mass and CG were split)
Cleans up and corrects mass and CG override code in MassComputation
Adds a unit test for mass overrides in stages
Fixes #2394
> Clean up and fix mass and CG overrides

- core/test/net/sf/openrocket/simulation/FlightEventsTest.java
If we end up getting spurious failures we can take them back out.
> Add times to some of the events that were currently unspecified.

- core/src/net/sf/openrocket/unit/GeneralUnit.java
- core/src/net/sf/openrocket/unit/UnitGroup.java
This PR fixes #2409. You can now enter values up to 3 decimals, while the spinner's up- and down arrows increment/decrement in 0.1 steps.
https://github.com/openrocket/openrocket/assets/11031519/417ae0dc-2672-40e7-81b9-7a50ce54d20c
> [#2409] Don't use fixed precision for shape parameter

- core/src/net/sf/openrocket/file/rasaero/export/LaunchSiteDTO.java
When exporting an OR file to RASAero, the launch rod length was not properly converted to the right units. RASAero saves the launch rod length in feet instead of inches (all other lengths are saved in inches). This PR fixes this issue.
> Use meters->feet conversion for RASAero rod length

- core/src/net/sf/openrocket/optimization/services/DefaultSimulationModifierService.java
- swing/src/net/sf/openrocket/gui/dialogs/optimization/SimulationModifierTree.java
- swing/src/net/sf/openrocket/gui/util/UITheme.java
This PR fixes #2345. The motor ignition delay is now back for motor mounts.
There was also a rendering issue in the dark theme UI with already added optimization parameters; the contrast compared to normal text wasn't high. This PR fixes that as well.
Demo:
https://github.com/openrocket/openrocket/assets/11031519/762dcf4b-ae47-4b56-8181-505a4faec8e9
> [#2345] Reintroduce motor ignition delay optimization

- core/resources/l10n/messages.properties
- core/resources/l10n/messages_uk_UA.properties
- swing/src/net/sf/openrocket/gui/configdialog/AppearancePanel.java
I made two changes to things that have been bugging me for a long time.
1) Show up to 20 items at once, instead of 8.
2) Change the "From file..." option to "Select file..." in both the default and UK variants.  "From file..." never made sense to me.  I would probably prefer it to be at the top of the list (or perhaps just below "<none>" but was too lazy to make all the necessary changes and try it out.  Just avoiding the scrollbar will make it much better even in its current location at the bottom.
Before:
After:
> Updated texture select combobox

- core/resources/build.properties
- core/src/net/sf/openrocket/communication/UpdateInfoRetriever.java
- core/test/net/sf/openrocket/communication/UpdateInfoTest.java
- core/test/net/sf/openrocket/communication/WelcomeInfoTest.java
Currently, we always leave OpenRocket's build version to the latest released version (e.g. "23.09"). This is not really ideal. This PR adds a new version string for snapshot versions. So, the build version is now changed to "**23.09.SNAPSHOT**".
The idea is to change the build version of the unstable branch to "xx.xx.SNAPSHOT" after each release. That way, we can easily keep track of official releases vs dev versions. Ideally, we would also append the date or git commit ID of the latest commit to the version, but that's not too important right now.
> Add snapshot version to OpenRocket versioning system

- core/src/net/sf/openrocket/file/openrocket/importt/ComponentParameterHandler.java
- core/src/net/sf/openrocket/file/openrocket/importt/ComponentPresetSetter.java
- core/src/net/sf/openrocket/file/openrocket/importt/DocumentConfig.java
- core/src/net/sf/openrocket/file/rocksim/importt/ParachuteHandler.java
- core/src/net/sf/openrocket/rocketcomponent/Parachute.java
- core/src/net/sf/openrocket/rocketcomponent/RocketComponent.java
Some users on [TRF](https://www.rocketryforum.com/threads/openrocket-parachutes-resize-themselves.183828/) noticed a bug where the parachute size would change when loading designs that use preset parachutes.
The issue was that loading a parachute preset could set the packed radius to auto mode, which would in turn calculate a new packed length. This PR fixes that. Hope this is the last parachute length bug 🙂.
Problematic design file:
[lengthening_parachute_example.ork.zip](https://github.com/openrocket/openrocket/files/13781994/lengthening_parachute_example.ork.zip)
Resulted in this bug:
Which is now fixed:
> Fix parachute length resizing when loading preset parachute

- core/src/net/sf/openrocket/rocketcomponent/DeploymentConfiguration.java
- core/src/net/sf/openrocket/simulation/BasicEventSimulationEngine.java
Small bug in #2432: I put the current MotorClusterConfiguration in the general purpose data field of ALTITUDE events. Most (all?) other ALTITUDE events use this to store the previous and current altitude, and altitude-based recovery deployment looks at that to decide whether to fire. So, dual-deploy configurations got an exception there.
This PR puts a null in that field, and has the deployment configuration check for null.
> Fix data field in thrustcurve events

- swing/src/net/sf/openrocket/gui/dialogs/ComponentAnalysisDialog.java
In the component analysis drag table, an extra parameter (the Cd) was being passed to String.format().  This wound up putting the actual Cd of the component in the percentage display instead of the percentage.
I have to admit to some surprise -- this would be expected behavior from C; I would have thought Java would compare the number of parameters against the number of format conversion strings...
> Don't pass extra value (cd) to String.format

- core/src/net/sf/openrocket/simulation/BasicEventSimulationEngine.java
- core/src/net/sf/openrocket/util/TestRockets.java
- core/test/net/sf/openrocket/simulation/FlightEventsTest.java
When the tumble stepper was first added, a stage was only allowed to tumble after apogee was reached (I've got no idea why this limitation was imposed). Later, booster stages were allowed to tumble before apogee but the sustainer was not; if the conditions for tumbling were reached for the sustainer a warning was raised but the sustainer continued to use the RK4 stepper (see #181). At some point (I'm not sure when) the warning was removed.  Nowhere do I get a clear picture of why the sustainer is prohibited from tumbling before apogee.
This PR allows the sustainer to tumble under the same conditions as other stages. If the sustainer is still under thrust when it begins to tumble, the simulation stops with a SIM_ABORT event. There are two main reasons to do this:
1. We get not-infrequent …
> Allow sustainer tumble before apogee

- core/src/net/sf/openrocket/simulation/AbstractEulerStepper.java
- core/src/net/sf/openrocket/simulation/BasicEventSimulationEngine.java
- core/src/net/sf/openrocket/simulation/SimulationStatus.java
- core/src/net/sf/openrocket/util/Coordinate.java
- core/test/net/sf/openrocket/simulation/FlightEventsTest.java
This PR addresses several minor annoyances:
1. Previously, AbstractEulerTimeStep didn't honor the max time step that was passed in from BasicEventSimulationEngine. Here's an example from our "Pods--powered with recovery deployment" example:
The time step runs from about 5.30 seconds to 5.80 seconds, while the parachute opens at 5.35 seconds.  The parachute's effect on the flight isn't apparent until the next step; in addition to being annoying (it's really not significant) it could also mislead a user into thinking we're simulating chute opening times or something.
This PR changes the behavior to this:
The time step that would have included the chute opening is ended a time MIN_TIME_STEP (currently .001) seconds before the chute opening, and then a step from there to the chute opening is …
> Refine time step in AbstractEulerStepper

- swing/src/main/java/info/openrocket/swing/gui/dialogs/preferences/DesignPreferencesPanel.java
While working on the new documentation, I noticed that the "Open last design file on startup" preference is present in both the Design tab and the General tab. This PR removes that option from the Design, so that it is only accessible in the General tab from now on.
> Remove duplicate "Open last design file" preference from design tab

- core/src/main/java/info/openrocket/core/simulation/AbstractSimulationStepper.java
- core/src/main/java/info/openrocket/core/simulation/FlightDataType.java
- core/src/main/resources/l10n/messages.properties
This PR fixes #2462 by providing the air density as a plottable/exportable variable:
> [#2462] Provide air density as plottable variable

- swing/src/main/java/info/openrocket/swing/gui/print/PaperSize.java
This PR fixes #2483 by adding the following paper sizes for printing: A1, A2, ANSI B (tabloid), ANSI C, ANSI D.
> [#2483] Support more (larger) paper sizes

- core/src/main/java/info/openrocket/core/simulation/AbstractEulerStepper.java
- core/src/main/java/info/openrocket/core/simulation/AbstractSimulationStepper.java
- core/src/main/java/info/openrocket/core/simulation/RK4SimulationStepper.java
The DataStore, AccelerationData, and SimulationStatus had redundant storage of identical acceleration data. This made the code more difficult to read and has a potential for errors in the future if the data gets out of sync. This PR removes this redundancy. Issue #2443 was originally filed because some of this data was only in the SimulationStatus when in an Euler stepper, not the RK4 Stepper.  It is now never in SimulationStatus (it is in DataStore.accelerationData at all times).
Fixes #2443
> Reduce redundant acceleration data storage

- swing/src/main/java/info/openrocket/swing/gui/simulation/SimulationConfigDialog.java
This PR fixes #2531. The sim edit dialog will now remain open after plotting/exporting a sim.
> [#2531] Don't close edit sim dialog after plotting or exporting

- core/src/main/java/info/openrocket/core/preferences/ApplicationPreferences.java
- core/src/main/java/info/openrocket/core/rocketcomponent/FlightConfiguration.java
- core/src/main/resources/l10n/messages.properties
- swing/src/main/java/info/openrocket/swing/gui/dialogs/flightconfiguration/RenameConfigDialog.java
This PR fixes #2537.
https://github.com/user-attachments/assets/8baef65a-8dd0-4a63-a1f7-fce7606bb7b4
> [#2537] Allow for reconfiguration of the default flight config name

- core/src/main/java/info/openrocket/core/database/AsynchronousDatabaseLoader.java
- swing/src/main/java/info/openrocket/swing/startup/GuiModule.java
This PR fixes #1579. You can now bypass the component preset and motor database loading respectively with the command line arguments `-Dopenrocket.bypass.presets` and `-Dopenrocket.bypass.motors`. It has been documented on the GitHub Wiki: https://github.com/openrocket/openrocket/wiki/Command-line-arguments.
> [#1579] Add command-line argument to bypass preset and motor loading at startup

- core/src/main/java/info/openrocket/core/aerodynamics/AerodynamicForces.java
- core/src/main/java/info/openrocket/core/componentanalysis/CADataType.java
- core/src/main/java/info/openrocket/core/componentanalysis/CAParameterSweep.java
- core/src/main/resources/l10n/messages.properties
- swing/src/main/java/info/openrocket/swing/gui/dialogs/componentanalysis/CAPlotTypeSelector.java
- swing/src/main/java/info/openrocket/swing/gui/dialogs/componentanalysis/ComponentAnalysisGeneralPanel.java
- swing/src/main/java/info/openrocket/swing/gui/scalefigure/RocketPanel.java
- swing/src/main/java/info/openrocket/swing/gui/widgets/GroupableAndSearchableComboBox.java
This PR fixes #2019. When selecting a row in the component analysis tables, the corresponding component is highlighted in the rocket panel. There is now also a column for per instance CD and total CD. In the per instance CD, the cell of the rocket is left blank and there are no relative contributions (the percentages).
https://github.com/user-attachments/assets/9ec575d8-c3af-4e11-a068-68a06bd0f70f
>  [#2019] Highlight selected component in CA dialog in rocket panel  & Add per-instance CD column to component analysis dialog

- core/src/main/java/info/openrocket/core/aerodynamics/barrowman/TubeCalc.java
I can't find any notes giving any clue what I was thinking when I applied the Prandtl-Glauert transformation to the friction coefficient of the tube, and the papers I went from in developing the code also give me no hints. It's obviously completely invalid here. Mea culpa.
Removing it makes no difference to the accuracy of the sim results for the subsonic (B and C motor) test rocket, only slightly reduces it for the supersonic (K motor) tests, and actually improves it slightly (but still not significantly) for the low transonic peak velocity (J) rocket.
| Motor | Actual | Current Unstable | Error | This PR | Error
|-- | -- | -- | --|--|--|
|B6 | 352 |361| 2.56%|360|2.27%|
|C6 | 693 |729 | 5.19%|729|5.19%|
|J360 | 4065| 3982 | -2.04%|3986|-1.94%|
|K1103 | 5009| 5084 | 1.5%|5149|2.79%| …
> Remove Prandtl-Glauert correction factor

- core/src/main/java/info/openrocket/core/aerodynamics/FlightConditions.java
- core/src/main/java/info/openrocket/core/aerodynamics/barrowman/FinSetCalc.java
- core/src/test/java/info/openrocket/core/aerodynamics/FlightConditionsTest.java
This PR is related to #2543. It clamps the Prandtl-Glauert compressibility correction factor (beta) to 0.6 in the transonic region, between Mach 0.8 and 1.1, as described in "Active Guidance and Dynamic Flight Mechanics for Model Rockets", David Ketchledge (1993). This avoids beta reaching infinity when it nears Mach 1. Additionally, I also applied the compressibility correction in the supersonic region for fins, as described in literature.
> Clamp beta factor (compressibility correction) in transonic region + apply it in supersonic region

- swing/src/main/java/info/openrocket/swing/gui/dialogs/preset/ComponentPresetTable.java
This PR fixes #2576 where the "Sides" and "Line Count" column in the Parachute Component panel sort lexically instead of numerically.
The problem was in ComponentPresetTable. During column initialization, the sorter did not have a special case for Integers as it did for Doubles and Booleans. This caused it to sort Integers like Strings instead of numbers because there was no base case other than the default.
The issue was fixed by adding a simple special case, just like the Booleans or Doubles, that handles Integers separately than all other Objects.
> [#2576] Fix Sorting Problem With Sides and Line Count columns on Parachute Preset Library

- swing/src/main/java/info/openrocket/swing/gui/plot/SimulationPlot.java
currently it uses the default formatting, which means you can get a dozen or so decimal places
> format time in sim abort window to two decimal places

- core/src/main/java/info/openrocket/core/simulation/BasicEventSimulationEngine.java
- core/src/main/java/info/openrocket/core/simulation/SimulationStatus.java
- core/src/test/java/info/openrocket/core/simulation/FlightEventsTest.java
It is possible for a FlightEvent, scheduled by a component of one stage of a rocket, to end up on the event queue for another stage and still be on the queue after the second stage lands. For instance, in FlightEventsTest.testMultiStage(), the center booster doesn't burn out until after the side boosters are on the ground. This results in a spurious EventAfterLanding warning.
In addition, there is a bug in the test causing events from the side booster branch to not be checked, so the bug had not been noticed until now.
This PR fixes the bug in the test, and also filters the events in the queue immediately after stage separation to eliminate the unattached events.
> Filter out events from components that are no longer attached immediately after stage separation

- core/src/test/java/info/openrocket/core/simulation/FlightEventsTest.java
Fixes #2601. Tested on 10,000 iterations of the unit tests. The ground hit and simulation end timing were especially problematic, so I ignore those times.
> [#2601] Loosen constraints on unit test

- core/src/test/java/info/openrocket/core/simulation/DisableStageTest.java
Similar to #2603, the `DisableStageTest` often failed. Tested the new unit test on 10,000 iterations and no failures.
> Improve failure rate of unit tests

- core/src/main/java/info/openrocket/core/file/wavefrontobj/export/components/TransitionExporter.java
This PR fixes #2609. The issue in the original example was that in the nose cone, the fore radius could become negative (`innerFore = component.getForeRadius() - component.getThickness()` where the thickness was larger than the fore radius). This PR clamps the radius to positive numbers. Note that this issue only occurred for conical-shaped nose cones/transitions.
> [#2609] Ensure non-negative inner fore/aft radius

- ReleaseNotes.md
- core/src/main/java/info/openrocket/core/rocketcomponent/SymmetricComponent.java
- core/src/test/java/info/openrocket/core/preset/NoseConePresetTests.java
Well, this is a bit awkward. Transition (and nose cone) presets that had a `<Filled>` parameter in the database, even if it was `<Filled>false</False>`, would always be set to filled, because of `loadFromPreset` in `SymmetricComponent.java`:
```java
@Override
protected void loadFromPreset(ComponentPreset preset) {
if (preset.has(ComponentPreset.THICKNESS)) {
this.thickness = preset.get(ComponentPreset.THICKNESS);
this.filled = false;
}
if (preset.has(ComponentPreset.FILLED)) {
this.filled = true;
}
super.loadFromPreset(preset);
}
```
Which was called in `Transition`:
```java
@Override
protected void loadFromPreset(ComponentPreset preset) {
boolean presetFilled = false;
if (preset.has(ComponentPreset.FILLED)) {
presetFilled = preset.get(ComponentPreset.FILLED);
}
... …
```
> [#2614] Set transition component preset filled value based on actual preset value instead of the presence of the parameter

- core/src/main/java/info/openrocket/core/simulation/AbstractEulerStepper.java
- core/src/main/java/info/openrocket/core/simulation/AbstractSimulationStepper.java
- core/src/main/java/info/openrocket/core/simulation/BasicEventSimulationEngine.java
- core/src/main/java/info/openrocket/core/simulation/GroundStepper.java
- core/src/main/java/info/openrocket/core/simulation/RK4SimulationStepper.java
- core/src/main/java/info/openrocket/core/simulation/SimulationStatus.java
- core/src/main/java/info/openrocket/core/simulation/SimulationStepper.java
- core/src/main/java/info/openrocket/core/util/TestRockets.java
- core/src/test/java/info/openrocket/core/simulation/FlightEventsTest.java
Final time step isn't calculated since there will be no next step.
Updates unit tests to check for flight data variables that are NaN in the last sample, but not previous.
Fixes #2608
> Add a cleanup method to AbstractSimulationStepper to write values from final step to flight data branch

- core/src/main/java/info/openrocket/core/communication/WelcomeInfoRetriever.java
Description: This PR fixes #2625, where the retrieveWelcomeInfo method used outdated file paths after the Gradle migration, preventing the welcome dialogue from displaying correctly.
Solution: Updated the file path for ReleaseNotes.md to the correct location to ensure the release notes are loaded properly.
> [#2625] Update welcome info path

- core/src/main/java/info/openrocket/core/rocketcomponent/SymmetricComponent.java
- core/src/test/java/info/openrocket/core/rocketcomponent/TransitionTest.java
This PR fixes #2626. There was an issue for 0-length transitions that got loaded from the .ork file. The `Transition` was loaded, which initializes the CG to `null`. Then `calculateProperties()` was called on the `Transition`, which first goes to `calculateProperties()` of `SymmetricComponent`, but because the length was 0, the method immediately returned, leaving the CG to `null`, and causing the `NullPointerException`. This PR just initializes the CG in `calculateProperties()` of `SymmetricComponent` so it cannot be `null`.
> [#2626] Initialize CG in SymmetricComponent

- core/src/main/java/info/openrocket/core/database/Databases.java
This PR fixes #2624 by ignoring material groups in the material database search. I don't think this will ever be a problem. The only problem could be that if you have e.g. "MAT A, 1 g/m3" in the Metals group and "MAT A, 1 g/m3" in the Woods group, that there is no distinction between both, since they have the same material name and density. But again, not really an issue since functionality they are the same materials.
> [#2624] Don't check for material group in database search

- CONTRIBUTING.md
This PR is a patch for spellings in the contribution guide. 
* his/her are possessive, so 'they' should be possessive as well
* therefor generally means 'in return for' while therefore generally means 'as a result', with the latter seeming to fit better
From a copy editing perspective, it may be more inclusive and flow more smoothly to shorten 'his/her/their' to 'their', as this would retain the meaning, but this would be a more stylistic choice for the author. 
Hope this helps! Happy to make any edits and look forward to contributing more.
> [Typo] Align spellings for contributing translations

- swing/src/main/java/info/openrocket/swing/gui/adaptors/Column.java
- swing/src/main/java/info/openrocket/swing/gui/adaptors/ColumnTable.java
- swing/src/main/java/info/openrocket/swing/gui/adaptors/ColumnTableModel.java
- swing/src/main/java/info/openrocket/swing/gui/main/SimulationPanel.java
This PR dynamically resizes the Warnings column in the sim table to fit the content of the sim. Before, it was a relatively wide, statically sized column.
Examples:
The column header text is cut off, but the full name is accessible with the tooltip:
> Dynamically resize the sim table Warnings column based on its content

- core/src/main/java/info/openrocket/core/unit/FixedPrecisionUnit.java
- core/src/main/java/info/openrocket/core/unit/UnitGroup.java
- core/src/test/java/info/openrocket/core/unit/FixedPrecisionUnitTest.java
- core/src/test/java/info/openrocket/core/unit/UnitToStringTest.java
- swing/src/main/java/info/openrocket/swing/gui/simulation/SimulationConditionsPanel.java
This PR fixes #2590. The input fields for the longitude and latitude are now wider and support up to 5-decimal precision. The field is made wide enough to support the precision.
>  [#2590] Make input fields for longitude and latitude larger + add more decimal precision

- core/src/main/java/info/openrocket/core/communication/ReleaseInfo.java
- core/src/main/java/info/openrocket/core/communication/UpdateInfoRetriever.java
- core/src/main/resources/l10n/messages.properties
- swing/src/main/java/info/openrocket/swing/communication/AssetHandler.java
- swing/src/main/java/info/openrocket/swing/gui/dialogs/UpdateInfoDialog.java
- swing/src/main/java/info/openrocket/swing/startup/SwingStartup.java
This PR adds some improvements to the software updater:
1. Remove the OS selection combobox from the update dialog, it's not really serving a purpose. Users should just select the right installer on the website.
2. Only when the update is an official release, link to the openrocket.info website when you click "Install Update". For pre-releases, link to the GitHub release page. This is because normally, we do not upload pre-releases to the website.
3. When the update is a pre-release, add a warning text below the title, stating that it is a pre-releases and issues may be present.
> Improvements to the software updater

- core/src/main/java/info/openrocket/core/aerodynamics/barrowman/FinSetCalc.java
- core/src/test/java/info/openrocket/core/aerodynamics/FinSetCalcTest.java
This PR fixes #2474 by adding extra sanity checks in `FinSetCalc` for when the fin area/MAC span is zero or very small. See also [this comment](https://github.com/openrocket/openrocket/issues/2474#issuecomment-2558826495).
>  [#2474] Add extra sanity checks for small or zero-area fins in aerodynamics calculations

- core/src/main/java/info/openrocket/core/aerodynamics/BarrowmanCalculator.java
- core/src/main/java/info/openrocket/core/rocketcomponent/RocketComponent.java
- core/src/test/java/info/openrocket/core/aerodynamics/BarrowmanCalculatorTest.java
This PR fixes #2657 by including enabled stages in the `BarrowmanCalculator` calculations, even if its parent stage is disabled.
> [#2657] Do not ignore active child stages of inactive parent stage in calculations

- core/src/main/java/info/openrocket/core/simulation/BasicEventSimulationEngine.java
- core/src/test/java/info/openrocket/core/simulation/FlightEventsTest.java
Inference was wrong anyway, as it didn't check for a motor that hadn't started burning yet.
> directly test for non-zero thrust when recovery device deploys, instead of inferring from motor state.

- swing/src/main/java/info/openrocket/swing/gui/main/SimulationPanel.java
- swing/src/main/java/info/openrocket/swing/gui/simulation/SimulationWarningsPanel.java
A couple of small tweaks:
1) In the simulation warnings panel, don't show the number of warnings on each header.  You can see the warnings right in front of you, don't need to see the number
2) In the sim results table warnings column, only show the number if its greater than 1.  I am not sure about this change.
I am confident about (1), less so about (2).
> Sim warnings updates

- core/src/main/java/info/openrocket/core/aerodynamics/BarrowmanCalculator.java
- core/src/main/java/info/openrocket/core/logging/Message.java
- core/src/main/java/info/openrocket/core/logging/Warning.java
- core/src/main/java/info/openrocket/core/simulation/BasicEventSimulationEngine.java
- core/src/test/java/info/openrocket/core/simulation/FlightEventsTest.java
This PR makes all warnings look like
Problem: "component", "component"
both for uniformity and for clarity. Also properly sets zero-volume body tube priority.
Fixes #2669
> Make all (most?) warnings take a standard syntax

- core/src/main/java/info/openrocket/core/database/Databases.java
The density (1.05 g/cm^3) corresponds to polystyrene plastics instead of foams (typically 0.01 to 0.05 g/cm³).
> Reclassify polystyrene to plastics instead of foams

- core/src/main/java/info/openrocket/core/file/wavefrontobj/export/components/TransitionExporter.java
- core/src/test/java/info/openrocket/core/file/wavefrontobj/export/OBJExporterFactoryTest.java
This PR fixes #2673. Zero-thickness shoulder should now export correctly:
> [#2673] Fix export of 0-thickness transition shoulder

- core/src/main/java/info/openrocket/core/rocketcomponent/Rocket.java
This PR fixes #2679. The issue was in the `Rocket` `notifyAllListeners` code:
```java
private void notifyAllListeners(final ComponentChangeEvent cce) {
// Copy the list before iterating to prevent concurrent modification exceptions.
EventListener[] list = listenerList.toArray(new EventListener[0]);
for (EventListener l : list) {
{ // vvvv DEVEL vvvv
//System.err.println("notifying listener.  (type= "+l.getClass().getSimpleName()+")");
//System.err.println("                     (type= "+l.getClass().getName()+")");
} // ^^^^ DEVEL ^^^^
if (l instanceof ComponentChangeListener) {
((ComponentChangeListener) l).componentChanged(cce);
}
else if (l instanceof StateChangeListener) {
((StateChangeListener) l).stateChanged(cce);
}
}
}
```
The `OpenRocketDocument` is both a ComponentChangeListener …
> [#2679] Don't use exclusive if for component changes

- core/src/main/java/info/openrocket/core/file/openrocket/importt/DoubleSetter.java
- core/src/main/java/info/openrocket/core/rocketcomponent/MassObject.java
- swing/src/main/java/info/openrocket/swing/gui/configdialog/MassComponentConfig.java
- swing/src/main/java/info/openrocket/swing/gui/configdialog/ParachuteConfig.java
- swing/src/main/java/info/openrocket/swing/gui/configdialog/ShockCordConfig.java
- swing/src/main/java/info/openrocket/swing/gui/configdialog/StreamerConfig.java
This PR fixes #2660. When the parent of a MassObject (parachute, streamer, shock cord, mass component) has a max inner radius of 0 (e.g. when a body tube is filled), the autoRadius feature is bypassed. Additionally, there is a general sanity check in `DoubleSetter` to verify that the double value is valid (not infinite or NaN). If it is invalid, it is ignored and a warning is shown when opening the .ork file. Finally, when the auto radius is 0, the auto length value is not based on the auto radius.
> [#2660] Fix importing of invalid Double values & MassObject auto radius if the parent radius is 0

- swing/src/main/java/info/openrocket/swing/gui/dialogs/componentanalysis/CAExportPanel.java
This PR fixes #2695. For some reason, the indexing of the `selectedComponentsMap` map was done using the for-loop integer `i`, instead of CADataType `types[i]`.
> [#2695] Fix incorrect map keys for CA export

- core/src/main/java/info/openrocket/core/util/FileUtils.java
- core/src/test/java/info/openrocket/core/util/FileUtilsTest.java
This PR fixes #2701. The issue was with the `removeExtension` method in `FileUtils` which was not robust against file paths with a period in it.
> [#2701] Make remove file extension method robust against periods in the file path

- core/src/main/java/info/openrocket/core/rocketcomponent/FlightConfiguration.java
- core/src/main/java/info/openrocket/core/simulation/FlightDataType.java
- core/src/main/java/info/openrocket/core/simulation/SimulationStatus.java
- core/src/main/resources/l10n/messages.properties
- core/src/test/java/info/openrocket/core/ServicesForTesting.java
- core/src/test/java/info/openrocket/core/document/SimulationTest.java
- core/src/test/java/info/openrocket/core/simulation/FlightDataTest.java
This PR fixes #2700 and adds "Altitude above sea level" as a new flight data type. Example for launch site altitude set to 190 m:
> [#2700] Add "Altitude above sea level" flight data type

- build.gradle
- core/build.gradle
- core/gradle/wrapper/gradle-wrapper.properties
- core/src/main/java/info/openrocket/core/models/atmosphere/AtmosphericConditions.java
- core/src/main/java/info/openrocket/core/models/atmosphere/AtmosphericModel.java
- core/src/main/java/info/openrocket/core/models/atmosphere/ExtendedISAModel.java
- core/src/main/java/info/openrocket/core/models/atmosphere/InterpolatingAtmosphericModel.java
- core/src/main/java/info/openrocket/core/simulation/SimulationOptions.java
- core/src/main/java/info/openrocket/core/simulation/SimulationOptionsInterface.java
- core/src/main/java/module-info.java
- core/src/test/java/info/openrocket/core/models/atmosphere/AtmosphericConditionsTest.java
- core/src/test/java/info/openrocket/core/models/atmosphere/ExtendedISAModelTest.java
- core/src/test/java/info/openrocket/core/models/atmosphere/InterpolatingAtmosphericModelTest.java
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
- swing/build.gradle
- swing/gradle/wrapper/gradle-wrapper.properties
- swing/src/main/java/info/openrocket/swing/gui/simulation/SimulationConditionsPanel.java
This PR fixes 2 issues:
Fixes #2699, where air temperature and pressure interpolation failed if the launch site altitude was above 0. The issue was caused by `ExtendedISAModel` setting `layer[0]` to the launch site conditions, affecting interpolation in `InterpolatingAtmosphericModel`. When `InterpolatingAtmosphericModel` runs the `computeLayers` method, it does so by calculating the atmospheric conditions at 500 m incrementing air layers, starting at sea level (altitude = 0 m), and ending at the maximum altitude for the model.
If you set the launch site altitude to 250 m, so in the middle of an air layer (between level 0 m and level 500 m), `InterpolatingAtmosphericModel.getConditions` will calculate the temperature and pressure at that altitude using interpolation of the level below it …
> [#2699] Extrapolate sea level atmospheric conditions if launch site altitude is above 0 &  [#2677] Limit launch site altitude to Troposphere 

- core/src/main/java/info/openrocket/core/simulation/BasicEventSimulationEngine.java
The cause of issue #2675 was that when a new simulation branch was started, the stepper to be used for the new branch was only selected based on whether the rocket was in the air (the flight stepper) or on the ground (the ground stepper). Consequently, even though the booster in the example rocket was under chute it was simulated by the flight stepper and came in ballistic.
This PR also checks if the rocket is under chute or tumbling, and selects the correct stepper for these cases. Here's the booster from the same sim as in the bug report:
This time, the booster can be seen to be descending under chute.
> Select between all the possible steppers when starting a new simulation branch

- core/build.gradle
- core/src/main/java/info/openrocket/core/plugin/JarMigrationHelper.java
- core/src/main/java/info/openrocket/core/simulation/SimulationOptions.java
- core/src/main/java/module-info.java
- core/src/main/resources/l10n/messages.properties
- swing/src/main/java/info/openrocket/swing/startup/SwingStartup.java
- swing/src/main/java/info/openrocket/swing/startup/jij/PluginClasspathProvider.java
This PR fixes #2676. When OR scans the Plugins directory at startup, it checks if the JAR uses the old package structure (`net.sf.openrocket`). If it does, and it does not find a migrated version of that JAR, it starts the migration process. The migration process involves creating a copy of the JAR file with suffix `-migrated-new`. E.g. for the `CDOverride.jar` plugin, a new file is created `CDOverride-migrate-new.jar`. The ASM library is then used to modify the byte-code if the `XX-migrate-new.jar` to migrate references from `net.sf.openrocket` to `info.openrocket.core/swing`. Finally, when the UI loaded in `SwingStartup`, it checks if there are any `XX-migrated-new.jar` files present in the Plugins directory. If so, it notifies the user and renames the JAR file from …
>  [#2676] Migrate old net.sf.openrocket plugins at startup 

- core/src/main/resources/l10n/messages.properties
- swing/src/main/java/info/openrocket/swing/gui/figureelements/RocketInfo.java
This PR fixes #2735. The flight configuration is now shown in the design view.
> [#2735] Show current flight configuration in the design view

- core/src/main/java/info/openrocket/core/formatting/MotorConfigurationSubstitutor.java
- core/src/main/java/info/openrocket/core/rocketcomponent/BodyTube.java
- core/src/main/java/info/openrocket/core/rocketcomponent/InnerTube.java
- core/src/main/java/info/openrocket/core/rocketcomponent/MotorMount.java
- core/src/test/java/info/openrocket/core/rocketcomponent/FlightConfigurationTest.java
- swing/src/main/java/info/openrocket/swing/gui/main/flightconfigpanel/MotorConfigurationPanel.java
- swing/src/main/java/info/openrocket/swing/gui/print/DesignReport.java
This PR fixes #2725.
Parallel booster staging example design:
Changed booster inner tube to 3-motor cluster:
No cluster and only one instance:
---
Note that there I discovered a bug while working on this (which was already present in 23.09). When opening the "Pods--powered with recovery deployment" example design, for the last flight config, the"A10-3" motor displayed as "217A10-3". The booster stage in that config has 2 A10-3 motors, which should display "2× A10-3". However, the '×' symbol is coded using `Chars.TIMES` (`u00D7`). In the motor config display code, there was this: `count + Chars.TIMES + " " + motorData`. But, since `count` is an integer, `Chars.TIMES` was also interpreted as an int (=215), instead of the '×' char. So you just did an integer sum... The solution was to force …
>  [#2725] Include assembly copies in motor count display 

- swing/src/main/java/info/openrocket/swing/gui/configdialog/RocketConfig.java
- swing/src/main/java/info/openrocket/swing/gui/main/BasicFrame.java
This change fixes the issue #2146 where the Rocket Config Dialog that opens up when opening an example is not focused.
The same was happening when opening it in full screen mode, so now it is focused when it opens and it can be closed with the 'esc' key or modified.
The change is just requesting focus from the Design Name text field component.
> [#2146] Focus Rocket Config Dialog when opening a file.

- core/src/main/java/info/openrocket/core/rocketcomponent/RocketComponent.java
The issue in #2745 is that when a new component is added to the component tree and its parent's CD is being overridden by an ancestor, the new component isn't getting marked as also being overridden by an ancestor. Rather than try to track down why, this PR takes the slightly more robust approach of eliminating the boolean and determining whether a component's CD is being overridden as needed.
Fixes #2745
> Calculate whether CD is being overridden by an ancestor as needed, instead of maintaining in a boolean variable

- swing/src/main/java/info/openrocket/swing/gui/figureelements/RocketInfo.java
- swing/src/main/java/info/openrocket/swing/gui/scalefigure/RocketPanel.java
This PR fixes #2749. The issue was that in `RocketPanel` in `updateExtras` that if the current config has no motors or computeFlightInBackground is disabled in preferences, that the flight data of `RocketInfo` was updated, but the simulation variable was not. That's fixed by this PR.
https://github.com/user-attachments/assets/8d44fd64-a1f4-488f-bcde-6a0f491e5dde
> [#2749] Also reset simulation when resetting flight data

- core/src/main/java/info/openrocket/core/aerodynamics/AerodynamicForces.java
- core/src/main/java/info/openrocket/core/aerodynamics/BarrowmanCalculator.java
- core/src/main/java/info/openrocket/core/aerodynamics/barrowman/FinSetCalc.java
- core/src/main/java/info/openrocket/core/aerodynamics/barrowman/SymmetricComponentCalc.java
- core/src/main/java/info/openrocket/core/aerodynamics/barrowman/TubeFinSetCalc.java
- core/src/main/java/info/openrocket/core/componentanalysis/CAParameterSweep.java
- core/src/main/java/info/openrocket/core/rocketcomponent/RocketComponent.java
- core/src/main/java/info/openrocket/core/simulation/extension/example/DampingMoment.java
- core/src/test/java/info/openrocket/core/aerodynamics/FinSetCalcTest.java
- core/src/test/java/info/openrocket/core/aerodynamics/SymmetricComponentCalcTest.java
- core/src/test/java/info/openrocket/core/rocketcomponent/FreeformFinSetTest.java
- swing/src/main/java/info/openrocket/swing/gui/dialogs/componentanalysis/ComponentAnalysisGeneralPanel.java
The discontinuity observed in #2751 when a component has a tailcone is caused by a divide-by-zero error when merging CPs for the components in the rocket.
At present, AerodynamicForces contains a member variable cp containing the center of pressure of the component or assembly, with CNa as its weight. It also redundantly stores CNa as a separate variable.
The discontinuity when there is a tailcone comes from the fact that, according to the Barrowman equations, a nose cone has a CNa of 2 and a tail cone has a CNa of -2. When taking the weighted average of the nose and tail cone the weight becomes 0; when dividing by the weight the CP is NaN.
This PR solves this by storing the moment defined by CP * CNa, with a weight of CNa. Now instead of combining CPs by performing a weighted average, we …
> Store moment calculated from CP and CNa instead of CP itself

- core/src/main/java/info/openrocket/core/models/wind/MultiLevelPinkNoiseWindModel.java
- core/src/main/java/info/openrocket/core/preferences/ApplicationPreferences.java
- core/src/main/resources/l10n/messages.properties
- core/src/test/java/info/openrocket/core/models/wind/MultiLevelWindModelTest.java
- swing/src/main/java/info/openrocket/swing/gui/simulation/CSVImportSettingsDialog.java
- swing/src/main/java/info/openrocket/swing/gui/simulation/MultiLevelWindEditDialog.java
- swing/src/main/java/info/openrocket/swing/gui/simulation/MultiLevelWindTable.java
This PR fixes #2715. When clicking the "Import levels" button in the multi-level wind dialog, a new dialog pops up where the user can change settings about how the CSV file is structured: what the column names are and which units are used. The user also has the option to check whether the file has a header row or not. If not, the column names entry is replaced with a column index entry. To further help the user, on the bottom of the dialog is a preview frame of what the contents of the CSV file may look like. Once the user confirms the settings with the "Ok" button, the settings dialog closes and the file chooser dialog appears.
Small notes:
- All settings are stored in preferences.
- After importing, the column units from the wind table in the "Wind profile editor" dialog are updated to …
>  [#2715] Allow more configurable multi-level wind import settings 

- swing/src/main/java/info/openrocket/swing/gui/simulation/MultiLevelWindTable.java
- swing/src/main/java/info/openrocket/swing/gui/simulation/SimulationConditionsPanel.java
The 10 m/s max wind speed probably came from the NAR, TRA, and UKRA safety code limits of 20 mph max ground wind; it doesn't apply at higher altitudes where the winds are pretty much always higher than that, and we also shouldn't be preventing a user from setting whatever they want.
Note that the slider for the average wind speed now works analogously to the sliders in some of the component configuration dialogs: you can only use the slider to set the wind speed up to 10 m/s, but you can enter any speed you want by typing it in.
There should be a warning that the wind speed exceeds safety codes; I'll make an issue for that so we don't forget it, but I'd rather wait to add it until the upcoming Warning rewrite.
The Extended ISA atmosphere model prohibits setting a launch site above 11km …
> Get rid of 10 m/s wind speed and 11km wind level limits

- core/src/main/java/info/openrocket/core/file/rasaero/export/SimulationDTO.java
- core/src/main/java/info/openrocket/core/file/rasaero/importt/SimulationHandler.java
- core/src/main/java/info/openrocket/core/file/rocksim/export/InnerBodyTubeDTO.java
- core/src/main/java/info/openrocket/core/rocketcomponent/FinSet.java
- core/src/main/java/info/openrocket/core/rocketcomponent/Instanceable.java
- core/src/main/java/info/openrocket/core/rocketcomponent/MotorMount.java
- core/src/main/java/info/openrocket/core/rocketcomponent/RocketComponent.java
- core/src/main/java/info/openrocket/core/simulation/MotorClusterState.java
- core/src/main/java/info/openrocket/core/util/Transformation.java
- core/src/test/java/info/openrocket/core/rocketcomponent/LaunchLugTest.java
- swing/src/main/java/info/openrocket/swing/gui/scalefigure/RocketFigure.java
This PR fixes #2776. The issue was not just a simple rendering glitch, but a more fundamental issue, namely that rocket component locations (the return value of `getComponentLocations()` in `RocketComponent`) did not account for rotations of super-parents. For example, take this structure:
```
Pod Set 1
├─ Phantom Body Tube
│  ├─ Pod Set 2
│  │  ├─ Body Tube
```
Conditions:
- Pod Set 1 rotation: -90°
- Pod Set 2 rotation: -90°
- Pod Set 2 radial offset: 10 cm
With a total rotation of -180°, you would expect the 10 cm offset to cause the body tube to move 10 cm in the negative y direction. However, it was moving 10 cm in the negative z direction, because only the -90° rotation of Pod Set 2 was taken into account in the pod set instance locations.
A very extreme example with a double-nested …
>  [#2776] Include super-parent angles in instance rotation 

- core/src/main/java/info/openrocket/core/rocketcomponent/SymmetricComponent.java
- core/src/main/java/info/openrocket/core/rocketcomponent/Transition.java
> Check for 0 mass transitions, set their moments of inertia to 0 instead of getting a NaN due to dividing by mass

- swing/src/main/java/info/openrocket/swing/gui/plot/PlotPanel.java
- swing/src/main/java/info/openrocket/swing/gui/simulation/SimulationConditionsPanel.java
- swing/src/main/java/info/openrocket/swing/gui/simulation/SimulationConfigDialog.java
- swing/src/main/java/info/openrocket/swing/gui/simulation/SimulationOptionsPanel.java
- swing/src/main/java/info/openrocket/swing/gui/simulation/SimulationPlotPanel.java
- swing/src/main/java/info/openrocket/swing/gui/widgets/CSVExportPanel.java
This PR is a first attempt at improving OpenRocket's UI for users that have a low resolution screen setting. We recently received feedback from a user who simply couldn't access some items in the dialog because they got out of screen.
This PR makes the following changes:
- Overall reduces the default size of the sim edit dialog
- Add a scrollpane so that when you resize the sim edit dialog to make it smaller, you can still scroll through the rest of the contents. Note that the window size is saved in the preferences, so the user would only have to do this once
https://github.com/user-attachments/assets/b859de1f-ae62-4439-87c3-5afff54aa26e
---
The dialog scrollpane behavior should eventually be implemented in every dialog, especially larger sized ones. I'll make an issue for it so we don't …
> Improve simulation edit dialog UI for low-resolution screens

- core/src/main/java/info/openrocket/core/simulation/SimulationStatus.java
This matches user expectations, labels in plots and data exports, and documentation (see https://openrocket.readthedocs.io/en/latest/dev_guide/codebase_walkthrough.html#units-used-in-openrocket)
> Save latitude and longitude as degrees, not radians.

- core/src/main/java/info/openrocket/core/aerodynamics/barrowman/TubeCalc.java
It was using TubeFinSetCalc.class. It doesn't really matter since there aren't actually any logger calls in the class, but if one is ever added it'll avoid some confusion.
> make TubeCalc logger reference correct class

- core/build.gradle
- core/gradle.properties
- core/src/main/java/info/openrocket/core/thrustcurve/SerializeThrustcurveMotors.java
- core/src/main/java/info/openrocket/core/thrustcurve/serialization/SerializeThrustcurveMotors.java
- core/src/main/java/module-info.java
This PR introduces asynchronous fetching of motor data from the ThrustCurve API, replacing the original single-threaded implementation.
This significantly reduces the build time of the serializeEnginesExecute Gradle Task. 
_(Cited single-threaded build time: **15 minutes**, Asynchronous Build Time with 16 Threads: around **70 seconds**)_ 
Closes #2797
> [#2797] Thrust curve serialization optimising

- core/src/main/java/info/openrocket/core/file/openrocket/OpenRocketSaver.java
- core/src/main/java/info/openrocket/core/file/openrocket/importt/SimulationConditionsHandler.java
When saving a simulation, save the launchintowind flag as an element in the .ork file, eg
&lt;launchintowind&gt;false&lt;/launchintowind&gt;
When loading, parse using parseBoolean.
Behavior with old sims saved without the flag is unchanged (ie flag is read from app preferences)
fixes #2802
> Save and restore launchintowind element in .ork files

- core/src/main/java/info/openrocket/core/thrustcurve/ThrustCurveAPI.java
- core/src/main/java/info/openrocket/core/thrustcurve/serialization/SerializeThrustcurveMotors.java
Retrieves the Manufacturers directly from an GET call to the ThrustCurveAPI. 
Removes need to hardcode a manufacturers String array within the Serialization Code. 
_Dev Note: Not sure why my other commits were not verified via my GPG key, issue seems to be resolved._
Closes #2721
> Motor Manufacturer determination via ThrustCurveAPI

- swing/src/main/java/info/openrocket/swing/gui/simulation/SimulationConfigDialog.java
in #2653 closing sim window without saving or cancelling applies sim changes quietly. This fix implements cancel-like behavior (uniformly to "cancel" button) upon closing the window without a save. The behavior honors preference setting about showing an "are you sure..." dialog, in identical manner to the "cancel" button.
`applyChangesToSimsListener()` renamed to `windowCloseCancelListener()` and targeted to new method `cancelClose()` (from prior target `copyChangesToAllSims()`, which was left alone). Cancel button's `actionPerformed()` method retargeted to `cancelClose()`. `cancelClose()` created with prior contents of Cancel button's `actionPerformed()` method. windowListener removal line changed to target `windowCloseCancelListner()`
Fixes #2653.
> Apply uniform "cancel" behavior to all window closes and cancel button in simulations to fix #2653

- swing/src/main/java/info/openrocket/swing/gui/choosers/OBJOptionChooser.java
- swing/src/main/java/info/openrocket/swing/gui/choosers/OptionChooser.java
- swing/src/main/java/info/openrocket/swing/gui/choosers/StorageOptionChooser.java
- swing/src/main/java/info/openrocket/swing/gui/main/BasicFrame.java
- swing/src/main/java/info/openrocket/swing/gui/main/DesignFileSaveAsFileChooser.java
Fixing the bug where storage options dialog would pop up, regardless of save as options being selected. 
Also done refactor of 2 of the Option Chooser classes to a new interface to allow for ease of scalability in the future. 
Resolves #2805
> StorageOptions dialog being shown twice fix / OptionChooser Refactor

- core/src/main/java/info/openrocket/core/file/openrocket/OpenRocketSaver.java
- core/src/main/java/info/openrocket/core/file/openrocket/importt/WarningHandler.java
- core/src/main/java/info/openrocket/core/logging/Message.java
- core/src/main/resources/l10n/messages.properties
Also, when saving a warning with a removed component, give component a nil UUID to help later developers see what happened.
Minor bugfix; make sure to use text from warning description element in file when present, not content.
Fixes #2777
> Make warning source text more robust if source is null

- swing/src/main/java/info/openrocket/swing/gui/configdialog/SaveDesignInfoPanel.java
Removed code from SaveDesignInfoPanel.java which was apparently pasted from RocketComponentConfig.java. The removed code was causing misbehavior from an unrelated preference setting (former lines 61-73 of `SaveDesignInfoPanel`) and causing spurious `document.undo()` actions upon dialog cancel (former line 81): there should be nothing to undo re: the `SaveDesignInfoPanel`. This resolves #2680
> Stop reverting prior changes by simply cancelling the "Save design info" dialog. Fixes #2680

- core/src/main/java/info/openrocket/core/file/GeneralRocketLoader.java
- core/src/main/java/info/openrocket/core/file/openrocket/importt/FlightDataBranchHandler.java
At present, when loading a .ork file, all exceptions are caught and a RocketLoadException is thrown. The RocketLoadException is then handled, and a simple dialog that only gives the error that caused the exception is shown. This is appropriate for handling errors related to the file system (eg file not found) or the contents of the .ork file (eg SAXExceptions, caused by malformed XML in the .ork file).
For things like null dereferences, this is not appropriate as we need a stack trace to look at.
This PR changes this behavior to only catch appropriate exceptions, and let everything else go uncaught se we have a stack trace.
> When loading files, only catch exceptions related to file contents; let others go so we stack traces for get bug reports

- core/src/main/java/info/openrocket/core/file/GeneralRocketLoader.java
- core/src/main/java/info/openrocket/core/file/openrocket/OpenRocketSaver.java
- core/src/main/java/info/openrocket/core/file/openrocket/importt/FlightDataBranchHandler.java
- core/src/main/java/info/openrocket/core/logging/Warning.java
- core/src/main/java/info/openrocket/core/simulation/BasicEventSimulationEngine.java
- core/src/main/java/info/openrocket/core/simulation/FlightDataBranch.java
- core/src/main/java/info/openrocket/core/simulation/FlightEvent.java
A sim warning event caused by an event after landing ends up having three parts:
The event triggering everything (for instance, a recovery deployment occurring after landing)
A warning about that event
A simulation warning event, caused by the warning.
Nothing was hooking the original event up to either the warning or the warning event in the .ork file; this ended up causing a null pointer exception.
With this PR, the original event and the warning are both hooked up to the sim warning event so the whole chain can be reconstructed. It would in a sense have been tidier to have hooked the original event up to the warning and the warning up to the sim warning event, but since warnings are saved in the .ork before events, this would have required saving the event's UUID with the warning until …
> Attach event causing warning to "event after landing" event when saving .ork

- core/src/main/java/info/openrocket/core/models/wind/MultiLevelPinkNoiseWindModel.java
- core/src/main/java/info/openrocket/core/util/TextLineReader.java
- core/src/main/resources/l10n/messages.properties
- swing/src/main/java/info/openrocket/swing/gui/help/tours/SlideSetLoader.java
- swing/src/main/java/info/openrocket/swing/gui/help/tours/SlideSetManager.java
- swing/src/main/java/info/openrocket/swing/gui/simulation/CSVImportSettingsDialog.java
This PR fixes #2830 by allowing comments, starting with a hash (#), and blank lines in multi-level wind CSV files.
> Allow for comments (#) and blank lines in CSV import

- core/src/main/java/info/openrocket/core/database/ComponentPresetDatabaseLoader.java
- core/src/main/java/info/openrocket/core/database/MotorDatabaseLoader.java
- swing/src/main/java/info/openrocket/swing/gui/dialogs/preferences/GeneralPreferencesPanel.java
- swing/src/main/java/info/openrocket/swing/gui/dialogs/preferences/PreferencesPanel.java
In light of #2855, this PR makes user-defined thrust curve and component preset loading more foolproof by:
- Disabling the "All files" option in the file chooser
- When loading thrust curves or component preset files, that the file extension is correct
> [#2855] Make user-defined thrust curve and component preset loading more foolproof

- .github/workflows/build.yml
- build.gradle
- core/build.gradle
- docs/source/dev_guide/testing_and_debugging.rst
- swing/build.gradle
**Title**: Add jacoco code coverage with project-specific thresholds
**Description**:
This PR adds jacoco code coverage verification to the OpenRocket project
- **jacoco Integration**: Added jacoco plugin to both core and swing modules
- **Coverage Verification**: Integrated coverage verification into JAR packaging process
- **Project-specific Thresholds**: 
- Core module: 60% coverage threshold
- Swing module: 0% coverage threshold (disabled due to limited test coverage)
- **Aggregate Reports**: Added `jacocoRootReport` task to generate combined coverage reports
- **Build Integration**: JAR packaging now fails if coverage thresholds are not met
- Ensures code quality through automated coverage verification
- Prevents deployment of code that doesn't meet quality standards
- Provides …
> Add jacoco code coverage with project-specific thresholds

- build.gradle
- core/src/main/java/info/openrocket/core/file/wavefrontobj/export/OBJExporterFactory.java
- core/src/main/java/info/openrocket/core/file/wavefrontobj/export/components/BodyTubeExporter.java
- core/src/main/java/info/openrocket/core/file/wavefrontobj/export/components/FinSetExporter.java
- core/src/main/java/info/openrocket/core/file/wavefrontobj/export/components/LaunchLugExporter.java
- core/src/main/java/info/openrocket/core/file/wavefrontobj/export/components/MassObjectExporter.java
- core/src/main/java/info/openrocket/core/file/wavefrontobj/export/components/MotorExporter.java
- core/src/main/java/info/openrocket/core/file/wavefrontobj/export/components/RailButtonExporter.java
- core/src/main/java/info/openrocket/core/file/wavefrontobj/export/components/RingComponentExporter.java
- core/src/main/java/info/openrocket/core/file/wavefrontobj/export/components/TransitionExporter.java
- core/src/main/java/info/openrocket/core/file/wavefrontobj/export/components/TubeFinSetExporter.java
- core/src/main/java/info/openrocket/core/file/wavefrontobj/export/shapes/TubeExporter.java
- core/src/test/java/info/openrocket/core/file/wavefrontobj/export/components/BodyTubeExporterTest.java
- core/src/test/java/info/openrocket/core/file/wavefrontobj/export/components/FinSetExporterTest.java
- core/src/test/java/info/openrocket/core/file/wavefrontobj/export/components/LaunchLugExporterTest.java
- core/src/test/java/info/openrocket/core/file/wavefrontobj/export/components/MassObjectExporterTest.java
- core/src/test/java/info/openrocket/core/file/wavefrontobj/export/components/RailButtonExporterTest.java
- core/src/test/java/info/openrocket/core/file/wavefrontobj/export/components/RingComponentExporterTest.java
- core/src/test/java/info/openrocket/core/file/wavefrontobj/export/components/TransitionExporterTest.java
- core/src/test/java/info/openrocket/core/file/wavefrontobj/export/components/TubeFinSetExporterTest.java
This PR fixes #2881, fixes #2794, and fixes #2611. OBJ exporting now better accounts for components that have a 0 thickness or length.
> Account for zero-thickness and zero-length components in OBJ export
